"""Unit tests for _upsert_token_table incremental body-stripping logic.

Tests focus on the string manipulation: given a stored comment body
(as returned by get_summary_body()), the function must correctly strip
the marker line, the footer, and the previous <details> accordion before
appending fresh token data.
"""
from __future__ import annotations

import anyio
import pytest

from ai_pr_review.vcs.marker import SUMMARY_MARKER_PREFIX


# ---------------------------------------------------------------------------
# Helpers — minimal fakes
# ---------------------------------------------------------------------------

_SHA = "abc1234def5678abc1234def5678abc1234def56"
_MARKER = f"{SUMMARY_MARKER_PREFIX} sha={_SHA} -->"
_FOOTER = "\n\n---\n*AI Review Summary — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
_OLD_ACCORDION = "<details>\n<summary>Token usage by agent</summary>\n\nold table\n</details>"
_NEW_ACCORDION = "<details>\n<summary>Token usage by agent</summary>\n\nnew table\n</details>"

_FIRST_RUN_CONTENT = "## PR Summary\n\nWalkthrough table here."
_STORED_BODY = f"{_MARKER}\n{_FIRST_RUN_CONTENT}\n\n{_OLD_ACCORDION}{_FOOTER}"


class _FakeProvider:
    """Minimal VcsProvider fake that records post_summary calls."""

    def __init__(self, stored_body: str | None = _STORED_BODY) -> None:
        self._stored_body = stored_body
        self.posted_bodies: list[str] = []

    def get_summary_body(self) -> str | None:
        return self._stored_body

    def post_summary(self, body: str, sha: str) -> object:
        self.posted_bodies.append(body)

        class _R:
            ok = True
            error = None

        return _R()

    # Unused protocol methods — satisfy structural typing for tests
    def get_last_reviewed_sha(self) -> str | None:
        return None

    def post_findings(self, *a: object, **kw: object) -> object:  # type: ignore[override]
        raise NotImplementedError

    def resolve_stale(self) -> object:  # type: ignore[override]
        raise NotImplementedError

    def post_skip_comment(self, reason: str) -> object:  # type: ignore[override]
        raise NotImplementedError


def _make_result() -> object:
    """Return a minimal object satisfying what _upsert_token_table reads.

    Accesses: agent_results (list of AgentResult), sarif_elapsed_s.
    """
    from ai_pr_review.agents.dispatch import AgentResult, TokenUsage

    tl = TokenUsage(model="claude-haiku-4-5", input=100, output=50,
                    cache_creation=0, cache_read=0)
    ar = AgentResult(name="code-reviewer", output="", token_log=tl,
                     truncated=False, context_tokens_used=0)

    class _FakeResult:
        agent_results = [ar]
        sarif_elapsed_s = None

    return _FakeResult()


def _run_upsert(
    provider: _FakeProvider,
    summary_text: str = "",
    is_incremental: bool = True,
) -> None:
    """Synchronous wrapper: run _upsert_token_table via anyio."""
    from pathlib import Path
    from ai_pr_review.cli import _upsert_token_table

    script_dir = Path(__file__).parents[2]
    result = _make_result()

    async def _go() -> None:
        await _upsert_token_table(
            result,  # type: ignore[arg-type]
            provider,  # type: ignore[arg-type]
            _SHA,
            script_dir,
            summary_text,
            is_incremental=is_incremental,
        )

    anyio.run(_go)


# ---------------------------------------------------------------------------
# Incremental path: body stripping
# ---------------------------------------------------------------------------


def test_incremental_strips_marker_and_footer() -> None:
    """The posted body must not contain the stored marker or footer."""
    provider = _FakeProvider()
    _run_upsert(provider, is_incremental=True)
    assert provider.posted_bodies, "expected at least one post_summary call"
    posted = provider.posted_bodies[-1]
    assert SUMMARY_MARKER_PREFIX not in posted
    assert "---\n*AI Review Summary" not in posted


def test_incremental_preserves_first_run_summary() -> None:
    """The first-run PR summary content must survive the accordion replacement."""
    provider = _FakeProvider()
    _run_upsert(provider, is_incremental=True)
    assert provider.posted_bodies
    posted = provider.posted_bodies[-1]
    assert _FIRST_RUN_CONTENT in posted


def test_incremental_replaces_old_accordion() -> None:
    """Old <details> block must be gone; new one must be present."""
    provider = _FakeProvider()
    _run_upsert(provider, is_incremental=True)
    assert provider.posted_bodies
    posted = provider.posted_bodies[-1]
    assert "old table" not in posted
    assert "<details>" in posted
    assert "<summary>Token usage by agent</summary>" in posted


def test_incremental_no_existing_comment_skips_post() -> None:
    """If get_summary_body() returns None, post_summary must not be called."""
    provider = _FakeProvider(stored_body=None)
    _run_upsert(provider, is_incremental=True)
    assert provider.posted_bodies == []


def test_incremental_body_without_previous_accordion() -> None:
    """First-run body with no accordion yet — incremental run adds one cleanly."""
    # Stored body has no <details> block (first-run posted before token table)
    stored = f"{_MARKER}\n{_FIRST_RUN_CONTENT}{_FOOTER}"
    provider = _FakeProvider(stored_body=stored)
    _run_upsert(provider, is_incremental=True)
    assert provider.posted_bodies
    posted = provider.posted_bodies[-1]
    assert _FIRST_RUN_CONTENT in posted
    assert "<details>" in posted


def test_incremental_body_without_footer() -> None:
    """Stored body missing the footer sentinel — stripping is still safe."""
    stored = f"{_MARKER}\n{_FIRST_RUN_CONTENT}\n\n{_OLD_ACCORDION}"
    provider = _FakeProvider(stored_body=stored)
    _run_upsert(provider, is_incremental=True)
    assert provider.posted_bodies
    posted = provider.posted_bodies[-1]
    assert _FIRST_RUN_CONTENT in posted
    assert "old table" not in posted


def test_incremental_body_without_marker_line() -> None:
    """Stored body where marker is absent — stripping skips that step safely."""
    stored = f"{_FIRST_RUN_CONTENT}\n\n{_OLD_ACCORDION}{_FOOTER}"
    provider = _FakeProvider(stored_body=stored)
    _run_upsert(provider, is_incremental=True)
    assert provider.posted_bodies
    posted = provider.posted_bodies[-1]
    assert "old table" not in posted
    assert "<details>" in posted


# ---------------------------------------------------------------------------
# First-run path
# ---------------------------------------------------------------------------


def test_first_run_uses_summary_text() -> None:
    """On first run, the posted body is built from summary_text, not fetched."""
    provider = _FakeProvider()
    _run_upsert(provider, summary_text="## My Summary", is_incremental=False)
    assert provider.posted_bodies
    posted = provider.posted_bodies[-1]
    assert "## My Summary" in posted
    assert "<details>" in posted
    # get_summary_body() must NOT have been called on the first-run path
    # (provider.posted_bodies would be the only side-effect; no stored_body
    # access is observable, but we verify no old content leaks through)
    assert "old table" not in posted


def test_first_run_falls_back_to_ai_review_header_when_no_summary() -> None:
    """Empty summary_text on first run produces the '## AI Review' fallback."""
    provider = _FakeProvider()
    _run_upsert(provider, summary_text="", is_incremental=False)
    assert provider.posted_bodies
    posted = provider.posted_bodies[-1]
    assert posted.startswith("## AI Review")
