"""Guards against issue #759/#761's bug class: an env var the engine reads
being silently absent from container-action/action.yml's ``docker run -e``
passthrough list, so it's inert on the container path even when the calling
workflow sets it.

This does NOT parse the YAML structurally (no PyYAML dependency needed) --
it regexes the raw file text for every ``-e VAR`` / ``-e VAR=value`` token,
wherever it appears (the main ``docker run \\`` continuation, the
``${VAR:+-e VAR}`` conditional forwards, and the ``SUMMARY_MOUNT`` array
literal). See that file's own comment block (just above ``docker run --rm``)
for why commentary can never be interleaved inside the continuation itself --
a ``#`` on a backslash-continued line silently truncates the whole command.
"""

import re
from pathlib import Path

from ai_pr_review.config import _KNOWN_AI_VARS

_ACTION_YML_PATH = Path(__file__).resolve().parent.parent.parent / "container-action" / "action.yml"

# AI_* vars that are known to the engine (registered in _KNOWN_AI_VARS) but
# deliberately never forwarded to the container. Each has a documented reason
# in container-action/action.yml's comment block above `docker run --rm`.
_DELIBERATELY_EXCLUDED_AI_VARS = frozenset(
    {
        "AI_AGENT",  # Claude Code's own agent environment, never user-configured.
        "AI_PR_REVIEW_CORRELATION_ID",  # generated by the engine at startup.
        "AI_PR_REVIEW_SCRIPT_DIR",  # baked into the image via Dockerfile ENV.
        "AI_PR_REVIEW_RECORD_DIR",  # output path; needs a -v mount this action doesn't provide.
        "AI_PR_REVIEW_COMPUTE_OUTPUT",  # same reason as AI_PR_REVIEW_RECORD_DIR.
    }
)

# Non-AI_*-prefixed vars expected in the passthrough list. Unlike AI_* vars,
# these have no central registry (_KNOWN_AI_VARS only covers the AI_ prefix),
# so this is the explicit source of truth for this test.
_EXPECTED_NON_AI_VARS = frozenset(
    {
        # LLM provider credentials/config
        "ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GOOGLE_API_KEY", "BEDROCK_API_KEY",
        "OPENAI_BASE_URL", "BEDROCK_API_URL", "LLM_RETRY_COUNT", "LLM_PROMPT_CACHING",
        # GitHub context (runner-provided or workflow-provided)
        "GH_TOKEN", "GITHUB_ACTIONS", "GITHUB_REPOSITORY", "GITHUB_SERVER_URL",
        "GITHUB_RUN_ID", "GITHUB_API_URL", "GITHUB_BOT_USERNAME", "GITHUB_WORKSPACE",
        "GITHUB_STEP_SUMMARY",
        # PR/diff identification
        "PR_NUMBER", "BASE_REF", "HEAD_REF", "HEAD_SHA", "REVIEW_TARGET", "MAX_DIFF_LINES",
        "FORCE_FULL_DIFF", "STANDALONE_DEPTH",
        # Analyzer-specific
        "PHPSTAN_LEVEL",
    }
)


def _forwarded_vars() -> frozenset[str]:
    """Every var name following a literal ``-e`` token anywhere in the file
    (covers the main continuation, ``${VAR:+-e VAR}`` conditionals, and the
    ``SUMMARY_MOUNT=(-e VAR ...)`` array literal), stripping any ``=value``
    suffix (e.g. ``-e GITHUB_WORKSPACE=/workspace`` -> ``GITHUB_WORKSPACE``).
    """
    text = _ACTION_YML_PATH.read_text()
    return frozenset(re.findall(r"-e\s+([A-Z][A-Z0-9_]*)(?:=\S*)?", text))


def test_action_yml_exists() -> None:
    assert _ACTION_YML_PATH.is_file(), f"expected {_ACTION_YML_PATH} to exist"


def test_every_known_ai_var_is_forwarded_or_deliberately_excluded() -> None:
    forwarded = _forwarded_vars()
    expected = _KNOWN_AI_VARS - _DELIBERATELY_EXCLUDED_AI_VARS
    missing = expected - forwarded
    assert not missing, (
        f"These AI_* vars are known to the engine (_KNOWN_AI_VARS) but missing "
        f"from container-action/action.yml's docker run -e passthrough list: "
        f"{sorted(missing)}. If genuinely user-facing, add '-e <VAR>' to the "
        f"docker run block. If deliberately internal/unsuitable for the "
        f"container path, add it to _DELIBERATELY_EXCLUDED_AI_VARS here with "
        f"a reason, and document it in action.yml's own comment block."
    )


def test_deliberately_excluded_vars_are_still_known_and_still_absent() -> None:
    """Catches drift in the other direction: an entry in the deny-list that
    either fell out of _KNOWN_AI_VARS (stale) or was actually added to the
    passthrough list without updating this test (the exclusion reason may no
    longer apply)."""
    forwarded = _forwarded_vars()
    stale_denylist_entries = _DELIBERATELY_EXCLUDED_AI_VARS - _KNOWN_AI_VARS
    assert not stale_denylist_entries, (
        f"These vars are in _DELIBERATELY_EXCLUDED_AI_VARS here but no longer "
        f"in ai_pr_review.config._KNOWN_AI_VARS -- remove them from this "
        f"test's denylist: {sorted(stale_denylist_entries)}"
    )
    now_forwarded = _DELIBERATELY_EXCLUDED_AI_VARS & forwarded
    assert not now_forwarded, (
        f"These vars are forwarded in container-action/action.yml but still "
        f"listed as deliberately excluded in this test -- remove them from "
        f"_DELIBERATELY_EXCLUDED_AI_VARS (and check whether the exclusion "
        f"reason still applies before doing so): {sorted(now_forwarded)}"
    )


def test_no_unexpected_ai_var_forwarded() -> None:
    """Every forwarded AI_*-prefixed var must be a real, known var -- catches
    a typo'd '-e AI_FOO' that would otherwise silently do nothing forever."""
    forwarded_ai_vars = {v for v in _forwarded_vars() if v.startswith("AI_")}
    unknown = forwarded_ai_vars - _KNOWN_AI_VARS
    assert not unknown, (
        f"These AI_* vars are forwarded in container-action/action.yml but "
        f"not registered in ai_pr_review.config._KNOWN_AI_VARS -- likely a "
        f"typo, or a new var that needs registering there: {sorted(unknown)}"
    )


def test_expected_non_ai_vars_all_forwarded() -> None:
    forwarded = _forwarded_vars()
    missing = _EXPECTED_NON_AI_VARS - forwarded
    assert not missing, (
        f"These non-AI_* vars are expected in container-action/action.yml's "
        f"docker run -e passthrough list (per this test's _EXPECTED_NON_AI_VARS) "
        f"but are missing: {sorted(missing)}"
    )


def test_no_unexpected_non_ai_var_forwarded() -> None:
    """Catches an accidental removal being masked by this test's own
    allowlist going stale in the other direction, and flags any newly added
    non-AI_* var that should be reviewed and added to _EXPECTED_NON_AI_VARS
    deliberately rather than silently."""
    forwarded = _forwarded_vars()
    non_ai_forwarded = {v for v in forwarded if not v.startswith("AI_")}
    unexpected = non_ai_forwarded - _EXPECTED_NON_AI_VARS
    assert not unexpected, (
        f"These non-AI_* vars are forwarded in container-action/action.yml but "
        f"not in this test's _EXPECTED_NON_AI_VARS allowlist -- if this is a "
        f"deliberate new addition, add it to _EXPECTED_NON_AI_VARS here: "
        f"{sorted(unexpected)}"
    )
