"""Integration tests for canonical-review reuse wired into
`GitHubProvider.post_findings` -- the read side that actually stops the
PR-comment clutter the write side (verdict-marker recording, PR #714) set up
for. Uses the `_make_provider`/`_Recorder` MockTransport pattern from
`test_github_findings.py`.
"""

from __future__ import annotations

import json as _json
from collections.abc import Callable
from dataclasses import dataclass, field

import httpx
import pytest

from ai_pr_review.findings.models import Finding
from ai_pr_review.vcs._finding_ids import fingerprint
from ai_pr_review.vcs.github import GitHubConfig, GitHubProvider, _build_inline_comment_body
from ai_pr_review.vcs.http import RecordingClient, RetryPolicy, TapeRecorder
from ai_pr_review.vcs.marker import build_verdicts_marker, upsert_verdicts_marker
from ai_pr_review.vcs.protocol import DiffContext

_VALID_SHA = "abc1234def5678abc1234def5678abc1234def56"
_NEW_SHA = "def5678abc1234def5678abc1234def5678abcd"

_DIFF = """diff --git a/app.py b/app.py
--- a/app.py
+++ b/app.py
@@ -1,3 +1,6 @@
 context_line_1
 context_line_2
 context_line_3
+added_line_4
+added_line_5
+added_line_6
"""


@dataclass
class _Recorder:
    calls: list[tuple[str, str, dict | None]] = field(default_factory=list)


def _make_provider(
    handler: Callable[[httpx.Request], httpx.Response],
) -> tuple[GitHubProvider, _Recorder]:
    rec = _Recorder()

    def _wrap(request: httpx.Request) -> httpx.Response:
        body = None
        if request.content:
            try:
                body = _json.loads(request.content)
            except Exception:
                body = None
        rec.calls.append((request.method, str(request.url), body))
        return handler(request)

    transport = httpx.MockTransport(_wrap)
    http = httpx.Client(transport=transport, base_url="https://api.github.com")
    client = RecordingClient(
        http=http,
        recorder=TapeRecorder(record_dir=None),
        retry_policy=RetryPolicy(
            attempts=2, base_backoff=0, jitter=False, sleep=lambda _s: None
        ),
    )
    config = GitHubConfig(owner="o", repo="r", pr_number=1, token="t")
    return GitHubProvider(config=config, client=client), rec


def _finding(
    text: str = "issue",
    *,
    source: str = "code-reviewer",
    file: str = "app.py",
    line: int = 5,
    severity: str = "Medium",
    category: str = "other",
) -> Finding:
    return Finding(
        severity=severity, confidence=80, finding=text, source=source,
        file=file, line=line, category=category,
    )


def _footer_body(inner: str = "some body") -> str:
    return (
        f"## AI Review Findings\n\n{inner}\n\n---\n"
        "*AI Review — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
    )


def _thread_node(
    *,
    thread_id: str,
    comment_id: int,
    review_id: int,
    body: str,
    is_resolved: bool = False,
    is_outdated: bool = False,
    path: str = "app.py",
    line: int = 5,
    start_line: int | None = None,
    resolved_by: str | None = None,
) -> dict:
    return {
        "id": thread_id,
        "isResolved": is_resolved,
        "resolvedBy": {"login": resolved_by} if resolved_by is not None else None,
        "isOutdated": is_outdated,
        "path": path,
        "line": line,
        "originalLine": line,
        "startLine": start_line,
        "comments": {
            "nodes": [
                {
                    "databaseId": comment_id,
                    "body": body,
                    # GitHub's GraphQL API reports the bot's login without
                    # the REST-style "[bot]" suffix (verified live) --
                    # deliberately not "github-actions[bot]" here, so this
                    # fixture would catch a regression to comparing against
                    # that REST-style constant in the ownership gate.
                    "author": {"login": "github-actions"},
                    "pullRequestReview": {"databaseId": review_id},
                }
            ]
        },
    }


def _threads_response(nodes: list[dict]) -> httpx.Response:
    return httpx.Response(
        200,
        json={
            "data": {
                "repository": {
                    "pullRequest": {
                        "reviewThreads": {
                            "pageInfo": {"hasNextPage": False, "endCursor": None},
                            "nodes": nodes,
                        }
                    }
                }
            }
        },
    )


def _is_graphql(req: httpx.Request, body: dict | None, needle: str) -> bool:
    return (
        req.method == "POST"
        and str(req.url).endswith("/graphql")
        and bool(body)
        and needle in (body.get("query") or "")
    )


# ---------------------------------------------------------------------------
# Quiet rerun: nothing new -> PUT only, zero POST /reviews
# ---------------------------------------------------------------------------


def test_quiet_rerun_puts_canonical_body_posts_nothing_new() -> None:
    existing_finding = _finding("existing issue", severity="Medium")
    existing_comment_body = _build_inline_comment_body(existing_finding)
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews") or (
            req.method == "GET" and "/reviews?" in url
        ):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=5,
                )]
            )
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    # Identical finding re-detected this run -> classifies "update" (same
    # severity), no side effect that changes anything material, no new
    # findings at all.
    result = prov.post_findings(
        [existing_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is True
    assert result.review_id == 10
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    posts = [c for c in rec.calls if c[0] == "POST" and "/reviews" in c[1] and not c[1].endswith("/graphql")]
    assert len(puts) == 1
    assert posts == []


def test_quiet_rerun_reuses_canonical_despite_higher_id_empty_body_reply_review() -> None:
    """Same quiet-rerun scenario as `test_quiet_rerun_puts_canonical_body_posts_nothing_new`,
    but GitHub's review list also carries review 11 -- an empty-body,
    `COMMENTED` review auto-created when the bot replied to an inline
    comment (`GitHubProvider.reply_to_review_comment`), with a *higher* id
    than the real canonical review 10. Confirmed live on a real consumer PR:
    this shape is routine, not a fabricated edge case, and existed on the
    PR whose incident this fix addresses. `select_canonical` must skip the
    empty-body review so `post_findings` still treats review 10 as
    canonical and reuses it (`PUT`) -- not fall back to `POST`ing a fresh
    review because the naive highest-id pick (11) carries no footer, and
    never attempt to `PUT` review 11 at all (GitHub 422s on that)."""
    existing_finding = _finding("existing issue", severity="Medium")
    existing_comment_body = _build_inline_comment_body(existing_finding)
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews") or (
            req.method == "GET" and "/reviews?" in url
        ):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    },
                    {
                        "id": 11, "state": "COMMENTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": "",
                    },
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=5,
                )]
            )
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        if req.method == "PUT" and url.endswith("/reviews/11"):
            return httpx.Response(422, json={"message": "Could not edit a review with a missing body."})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [existing_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is True
    assert result.review_id == 10
    puts_10 = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    puts_11 = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/11")]
    posts = [c for c in rec.calls if c[0] == "POST" and "/reviews" in c[1] and not c[1].endswith("/graphql")]
    assert len(puts_10) == 1
    assert puts_11 == []
    assert posts == []


def test_new_medium_finding_over_max_inline_puts_not_posts() -> None:
    """Issue #719: any_new_inline_eligible must reflect which findings
    actually landed an inline comment, not raw eligibility. A Medium
    finding that's in-diff (so is_inline_eligible would say True) but gets
    bumped to the body by max_inline=0 must not force a fresh POST -- it
    never got a new inline comment at all, and it's below the High/Critical
    body-level exemption's threshold too."""
    canonical_body = _footer_body()
    new_finding = _finding("in-diff but bumped to body", severity="Medium")

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            raise AssertionError(
                "must PUT the canonical -- the finding never actually got "
                "an inline comment (max_inline=0 bumped it to the body) and "
                "is below the High/Critical body-level exemption"
            )
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [new_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
        max_inline=0,
    )

    assert result.ok
    assert result.reused_review is True
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert len(puts) == 1


# ---------------------------------------------------------------------------
# Genuinely new finding -> exactly one POST, old CR left standing (has
# unresolved threads) or dismissed (none left)
# ---------------------------------------------------------------------------


def test_new_finding_posts_fresh_review_and_dismisses_cleared_canonical() -> None:
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            # No threads at all this cycle: the canonical review has nothing
            # unresolved left owned by us.
            return _threads_response([])
        if req.method == "POST" and url.endswith("/reviews/10/dismissals"):
            return httpx.Response(200, json={"id": 10, "state": "DISMISSED"})
        if req.method == "PUT" and url.endswith("/reviews/10/dismissals"):
            return httpx.Response(200, json={"id": 10, "state": "DISMISSED"})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [_finding("brand new issue", severity="High")],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is False
    assert result.review_id == 20
    dismissals = [c for c in rec.calls if "/reviews/10/dismissals" in c[1]]
    assert len(dismissals) == 1
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1


def test_persistent_out_of_diff_critical_finding_puts_on_second_run() -> None:
    """Issue #719: a body-level Critical finding with no diff anchor (so it
    can never become an inline thread to fuzzy-match against) forces a
    fresh POST the first time it's seen -- but once its exact fingerprint
    is visible in the canonical's own body (via the id-map marker), an
    unchanged rerun must PUT instead of repeating the dismiss+POST cycle
    forever."""
    persistent = _finding(
        "structural issue with no diff anchor",
        severity="Critical",
        file="unrelated_file.py",
        line=1,
    )

    # Cycle 1: no prior review at all -> canonical is None -> must POST.
    def handler_cycle1(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 50, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov1, rec1 = _make_provider(handler_cycle1)
    result1 = prov1.post_findings(
        [persistent],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )
    assert result1.reused_review is False
    assert result1.review_id == 50
    posts_cycle1 = [c for c in rec1.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts_cycle1) == 1
    posted_body = posts_cycle1[0][2]["body"]

    # Cycle 2: same exact finding again. The canonical review now carries
    # this fingerprint's id-map entry from cycle 1's posted body.
    def handler_cycle2(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 50, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": posted_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/50"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": posted_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/50"):
            return httpx.Response(200, json={"id": 50})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            raise AssertionError(
                "must PUT the canonical, not POST a fresh review, for an "
                "unchanged persistent finding already visible in its body"
            )
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov2, rec2 = _make_provider(handler_cycle2)
    result2 = prov2.post_findings(
        [persistent],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )
    assert result2.ok
    assert result2.reused_review is True
    puts = [c for c in rec2.calls if c[0] == "PUT" and c[1].endswith("/reviews/50")]
    assert len(puts) == 1


def test_new_finding_does_not_dismiss_canonical_with_unresolved_owned_threads() -> None:
    """If the canonical CR review still has an unresolved thread we own, it
    must never be dismissed -- that's the exact hole a prior draft of this
    design had: dismissing it would let the slash-command PR-wide
    auto-approve path see zero unresolved threads on any CR review and
    approve a PR with a High finding still open."""
    existing_finding = _finding("still open issue", severity="High", line=4)
    existing_comment_body = _build_inline_comment_body(existing_finding)
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=4, is_resolved=False,
                )]
            )
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError(
                "must never dismiss a CR review with an unresolved owned thread"
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [existing_finding, _finding("brand new critical issue", severity="Critical", line=6)],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.review_id == 20


# ---------------------------------------------------------------------------
# Escalation: PATCH comment + reply, no new review
# ---------------------------------------------------------------------------


def test_escalated_finding_patches_and_replies_no_new_review() -> None:
    old_finding = _finding("weak validation", severity="Low", line=5, category="other")
    existing_comment_body = _build_inline_comment_body(old_finding)
    canonical_body = _footer_body()

    escalated_finding = _finding("weak validation", severity="Critical", line=5, category="other")

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=5,
                )]
            )
        if req.method == "PATCH" and url.endswith("/pulls/comments/1"):
            return httpx.Response(200, json={"id": 1})
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 2})
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [escalated_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is True
    assert result.inline_updated == 1
    assert result.replies_posted == 1
    patches = [c for c in rec.calls if c[0] == "PATCH" and c[1].endswith("/pulls/comments/1")]
    replies = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/comments/1/replies")]
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(patches) == 1
    assert len(replies) == 1
    assert "Critical" in replies[0][2]["body"]
    assert posts == []


def test_resolve_stale_does_not_resolve_thread_post_findings_just_updated() -> None:
    """Issue #718: orchestrate.py calls resolve_stale immediately after
    post_findings, on the same provider instance. Without
    _kept_alive_thread_ids, once #717's bot_login fix makes resolve_stale's
    ownership gate actually recognize real threads, it would immediately
    re-resolve the same thread post_findings just PATCHed for an
    update/escalate classification -- undoing the entire point of keeping
    it alive."""
    old_finding = _finding("weak validation", severity="Low", line=5, category="other")
    existing_comment_body = _build_inline_comment_body(old_finding)
    canonical_body = _footer_body()
    escalated_finding = _finding("weak validation", severity="Critical", line=5, category="other")

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "resolveReviewThread"):
            raise AssertionError(
                "must not resolve th1 -- post_findings just PATCHed it for "
                "an escalate classification this same run"
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=5,
                )]
            )
        if req.method == "PATCH" and url.endswith("/pulls/comments/1"):
            return httpx.Response(200, json={"id": 1})
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 2})
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, _ = _make_provider(handler)
    findings_result = prov.post_findings(
        [escalated_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )
    assert findings_result.ok

    stale_result = prov.resolve_stale(current_review_id=findings_result.review_id)
    assert stale_result.threads_resolved == 0


# ---------------------------------------------------------------------------
# Recurrence: fixed finding reappears -> reply + unresolve, verdict tombstone
# ---------------------------------------------------------------------------


def test_recurred_finding_replies_and_unresolves_thread() -> None:
    f = _finding("leaked key", severity="High", line=5, source="code-reviewer", category="secret")
    fp = fingerprint(f)
    resolved_comment_body = _build_inline_comment_body(f)
    canonical_body = _footer_body() + "\n" + build_verdicts_marker({fp: "fixed"})

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "unresolveReviewThread"):
            return httpx.Response(200, json={"data": {"unresolveReviewThread": {"thread": {"id": "th1", "isResolved": False}}}})
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=resolved_comment_body, line=5, is_resolved=True,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 2})
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.replies_posted == 1
    replies = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/comments/1/replies")]
    unresolves = [
        c for c in rec.calls
        if c[0] == "POST" and c[1].endswith("/graphql") and c[2]
        and "unresolveReviewThread" in (c[2].get("query") or "")
    ]
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert len(replies) == 1
    assert len(unresolves) == 1
    assert len(puts) == 1
    # The verdict must become "recurred", not stay "fixed" (which would
    # re-trigger this same reply/unresolve every subsequent run) and not be
    # silently deleted (which a union merge with an older body could then
    # resurrect).
    from ai_pr_review.vcs.marker import extract_verdicts
    assert extract_verdicts(puts[0][2]["body"])[fp] == "recurred"


def test_resolved_unverdicted_thread_triggers_reincarnation_note_on_repost() -> None:
    """Issue #779: a human resolved a bot-owned thread via GitHub's native
    "Resolve conversation" button, with no verdict command ever recorded
    against it. classify() correctly still returns "new" for the reappearing
    finding (there is no verdict to suppress or recur against, and #771/ADR
    0003 already settled that a heuristic that can't reliably tell "resolved
    because handled" from "resolved for any other reason" must never
    silently drop it) -- but the freshly posted inline comment must explain
    why, not just look like an unexplained duplicate."""
    f = _finding("secret detected", severity="High", line=5, source="trufflehog", category="secret")
    resolved_comment_body = _build_inline_comment_body(f, finding_id=1)

    def handler(req: httpx.Request) -> httpx.Response:
        body = _json.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=resolved_comment_body, line=5, is_resolved=True,
                    resolved_by="a-human",
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1
    comments = posts[0][2]["comments"]
    assert len(comments) == 1
    assert "previously resolved without a" in comments[0]["body"]
    assert "verdict command" in comments[0]["body"]


def test_bot_resolved_stale_thread_does_not_trigger_reincarnation_note() -> None:
    """Issue #779's precision requirement: resolve_stale()'s own routine
    housekeeping resolves any unresolved bot-owned thread whose finding
    didn't reappear in a given run, on every successful run, recording no
    verdict -- the identical is_resolved=True + no-verdict shape a human's
    native resolve produces. A finding that returns after that kind of
    resolve (a transient analyzer/agent gap, not a human decision) must not
    be told it was "previously resolved without a verdict command" -- nobody
    made that decision."""
    f = _finding("secret detected", severity="High", line=5, source="trufflehog", category="secret")
    resolved_comment_body = _build_inline_comment_body(f, finding_id=1)

    def handler(req: httpx.Request) -> httpx.Response:
        body = _json.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=resolved_comment_body, line=5, is_resolved=True,
                    resolved_by="github-actions",
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1
    comments = posts[0][2]["comments"]
    assert len(comments) == 1
    assert "previously resolved" not in comments[0]["body"]


def test_dedupe_demoted_finding_still_checked_for_reincarnation() -> None:
    """`reincarnated_fps` (post_findings, github.py) is computed against the
    *post*-`dedupe_thread_claims` classified list. A finding that loses its
    fuzzy claim on a still-open thread to a higher-severity sibling is
    demoted from "escalate"/"update" back to "new" by dedupe -- this checks
    that demoted finding is still evaluated against find_resolved_match (a
    genuinely reachable case: it independently exact-fingerprint-matches an
    unrelated, already-resolved thread), not silently skipped just because
    it briefly claimed a different thread this run."""
    low = _finding("nit", severity="Low", line=99, category="other")
    high = _finding("real bug", severity="Critical", line=101, category="other")
    open_thread_body = _build_inline_comment_body(
        _finding("existing", severity="Low", line=100, category="other")
    )
    resolved_comment_body = _build_inline_comment_body(low, finding_id=2)

    def handler(req: httpx.Request) -> httpx.Response:
        body = _json.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([
                _thread_node(
                    thread_id="open1", comment_id=1, review_id=10,
                    body=open_thread_body, line=100,
                ),
                _thread_node(
                    thread_id="resolved1", comment_id=2, review_id=10,
                    body=resolved_comment_body, line=99,
                    is_resolved=True, resolved_by="a-human",
                ),
            ])
        if req.method == "PATCH" and url.endswith("/pulls/comments/1"):
            return httpx.Response(200, json={"id": 1})
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 3})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [low, high],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    # "high" keeps the escalate claim on open1 (PATCH + reply); "low" is
    # demoted to "new" by dedupe_thread_claims and must still pick up the
    # reincarnation note from its own, unrelated resolved-thread match.
    patches = [c for c in rec.calls if c[0] == "PATCH" and c[1].endswith("/pulls/comments/1")]
    assert len(patches) == 1
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1
    posted_body = posts[0][2]["body"]
    assert "resolved earlier with no verdict recorded" in posted_body


def test_fixed_verdict_body_level_recurrence_never_gets_reincarnation_note() -> None:
    """`reincarnated_fps` (post_findings, github.py) only ever considers
    `kind == "new"` findings -- a body-level "recurred" finding (a `fixed`
    verdict whose finding came back, with no thread to reopen) must never
    also pick up the #779 note. Regression guard for the invariant the #779
    fix depends on, distinct from #771's own "fixed"->"recurred" coverage:
    that one never reaches `_render_body_bullets` at all, since it's a
    thread-anchored recurrence handled by reply/unresolve, not a body
    bullet."""
    f = _finding(
        "structural issue with no diff anchor", severity="Critical",
        file="unrelated_file.py", line=1,
    )
    fp = fingerprint(f)
    canonical_body = _footer_body() + "\n" + build_verdicts_marker({fp: "fixed"})

    def handler(req: httpx.Request) -> httpx.Response:
        body = _json.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            # Body-level recurrence: no inline thread ever existed for this
            # finding, so nothing here for find_resolved_match to match
            # against even if the "new"-only guard were removed.
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is True
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert len(puts) == 1
    posted_body = puts[0][2]["body"]
    assert "*(recurred)*" in posted_body
    assert "resolved earlier with no verdict recorded" not in posted_body


def test_genuinely_new_finding_has_no_reincarnation_note() -> None:
    """Negative case for #779: a finding with no prior thread at all (the
    ordinary "new" path) must not carry the reincarnation note -- it isn't
    reappearing from anywhere."""
    f = _finding("brand new issue", severity="Medium", line=5)

    def handler(req: httpx.Request) -> httpx.Response:
        body = _json.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    comments = posts[0][2]["comments"]
    assert len(comments) == 1
    assert "previously resolved" not in comments[0]["body"]


def test_resolved_unverdicted_thread_triggers_reincarnation_note_body_level() -> None:
    """Same #779 scenario as the inline case above, but for a finding with
    no diff anchor that falls to a body bullet instead of an inline comment
    -- _render_body_bullets is a separate render path from
    _build_inline_comment_body and needs its own coverage."""
    f = _finding(
        "structural issue with no diff anchor", severity="Critical",
        file="unrelated_file.py", line=1,
    )
    resolved_comment_body = _build_inline_comment_body(f, finding_id=1)

    def handler(req: httpx.Request) -> httpx.Response:
        body = _json.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=resolved_comment_body, line=1, path="unrelated_file.py",
                    is_resolved=True, resolved_by="a-human",
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1
    posted_body = posts[0][2]["body"]
    assert "resolved earlier with no verdict recorded" in posted_body


def test_reopened_recurrence_thread_protects_canonical_from_dismissal() -> None:
    """A recurrence reopens th1 on canonical review 10 via unresolveReviewThread.
    The same run also has a brand-new Critical finding, which forces
    decide_action to "post". Without syncing the in-memory `all_threads`
    snapshot after the reopen succeeds, _has_unresolved_owned_threads would
    still see th1's pre-side-effect is_resolved=True and wrongly let review
    10 be dismissed with a thread this very run just reopened sitting on it
    -- invisible to the slash-command PR-wide auto-approve check, which only
    counts unresolved threads on reviews whose *current* state is
    CHANGES_REQUESTED."""
    recurred = _finding("leaked key", severity="High", line=5, source="code-reviewer", category="secret")
    fp = fingerprint(recurred)
    resolved_comment_body = _build_inline_comment_body(recurred)
    canonical_body = _footer_body() + "\n" + build_verdicts_marker({fp: "fixed"})
    new_finding = _finding("brand new critical issue", severity="Critical", line=30)

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "unresolveReviewThread"):
            return httpx.Response(200, json={"data": {"unresolveReviewThread": {"thread": {"id": "th1", "isResolved": False}}}})
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=resolved_comment_body, line=5, is_resolved=True,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 2})
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError(
                "must not dismiss review 10 -- th1 was just reopened on it "
                "this run and is therefore still unresolved"
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [recurred, new_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.review_id == 20
    unresolves = [
        c for c in rec.calls if c[0] == "POST" and c[1].endswith("/graphql") and c[2]
        and "unresolveReviewThread" in (c[2].get("query") or "")
    ]
    assert len(unresolves) == 1


def test_canonical_reuse_false_always_posts_fresh_review() -> None:
    """AI_CANONICAL_REUSE=false (GitHubConfig.canonical_reuse=False) is the
    kill switch: even a run with zero findings against an existing
    CHANGES_REQUESTED canonical must behave exactly like every release
    before this feature -- a fresh POST, no PUT, no thread fetch, no
    dismissal."""
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            raise AssertionError(
                "canonical_reuse=False must not fetch review threads at all"
            )
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError("canonical_reuse=False must never dismiss anything")
        if req.method == "PUT" and url.endswith("/reviews/10"):
            raise AssertionError("canonical_reuse=False must never PUT the canonical")
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 30, "state": "APPROVED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    rec = _Recorder()

    def _wrap(request: httpx.Request) -> httpx.Response:
        import json as _j2
        b = None
        if request.content:
            try:
                b = _j2.loads(request.content)
            except Exception:
                b = None
        rec.calls.append((request.method, str(request.url), b))
        return handler(request)

    transport = httpx.MockTransport(_wrap)
    http = httpx.Client(transport=transport, base_url="https://api.github.com")
    client = RecordingClient(
        http=http, recorder=TapeRecorder(record_dir=None),
        retry_policy=RetryPolicy(attempts=2, base_backoff=0, jitter=False, sleep=lambda _s: None),
    )
    config = GitHubConfig(owner="o", repo="r", pr_number=1, token="t", canonical_reuse=False)
    prov = GitHubProvider(config=config, client=client)

    result = prov.post_findings(
        [], DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA), event="APPROVE",
    )

    assert result.ok
    assert result.review_id == 30
    assert result.reused_review is False
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1


# ---------------------------------------------------------------------------
# Dismissed verdict: suppressed, nothing posted for it
# ---------------------------------------------------------------------------


def test_dismissed_finding_is_suppressed_not_reposted(
    caplog: pytest.LogCaptureFixture,
) -> None:
    f = _finding("style nit", severity="Low", line=5)
    fp = fingerprint(f)
    canonical_body = _footer_body() + "\n" + build_verdicts_marker({fp: "dismissed"})

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        if req.method == "POST" and "/pulls/1/comments" in url:
            raise AssertionError("a suppressed finding must never be (re)posted")
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    with caplog.at_level("INFO", logger="ai_pr_review.vcs.github"):
        result = prov.post_findings(
            [f],
            DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
            event="REQUEST_CHANGES",
        )

    assert result.ok
    assert result.suppressed == 1
    # #771 review finding: classify()'s suppression decision (the actual
    # harm surface -- a live finding silently vanishing) had zero logging
    # anywhere. Pin down that the new observability point fires with the
    # fingerprint, since it's the only forensic trail for a suppression
    # that turns out to be spurious.
    assert any(
        rec.levelname == "INFO" and fp in rec.message for rec in caplog.records
    )


def test_dismissed_finding_stays_suppressed_after_fuzzy_update_drift() -> None:
    """#720 regression: a fuzzy "update" match PATCHes an open thread's
    comment in place, replacing its private metadata marker's fingerprint
    with the reworded finding's exact one while the visible **[F<n>]**
    token stays put. If a human then dismisses that thread, dismiss.py
    records the verdict against whatever fingerprint was current *at dismiss
    time* -- per #720's own narrative, that can be the finding's original
    (now-superseded) fingerprint. The next run must still suppress the same
    (still-reworded) finding rather than reposting it as "new" just because
    the thread's own marker has moved on to a different fingerprint than the
    one recorded in the verdicts map.
    """
    old_finding = _finding("SQL built via string concatenation", severity="Medium", line=5)
    old_fp = fingerprint(old_finding)
    original_comment_body = _build_inline_comment_body(old_finding, finding_id=3)

    # Reworded -- fingerprint changes -- but same file/severity/category and
    # within PROXIMITY_LINES, so classify() fuzzy-matches it to th1 as an
    # "update" rather than "new".
    reworded_finding = _finding(
        "SQL query concatenates untrusted input", severity="Medium", line=6
    )
    reworded_fp = fingerprint(reworded_finding)
    assert reworded_fp != old_fp

    state = {"canonical_body": _footer_body(), "comment_body": original_comment_body, "resolved": False}

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": state["canonical_body"],
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=state["comment_body"], line=5, is_resolved=state["resolved"],
                )]
            )
        if req.method == "PATCH" and url.endswith("/pulls/comments/1"):
            state["comment_body"] = (body or {}).get("body", state["comment_body"])
            return httpx.Response(200, json={"id": 1})
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": state["canonical_body"]})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            state["canonical_body"] = (body or {}).get("body", state["canonical_body"])
            return httpx.Response(200, json={"id": 10})
        if req.method == "POST" and "/pulls/1/comments" in url:
            raise AssertionError(
                "an update-classified finding must be PATCHed in place, "
                "never reposted as a brand new comment"
            )
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)

    # Run 1: the reworded finding fuzzy-matches th1 as "update" -- PATCHes
    # the comment in place. Its metadata marker now carries reworded_fp, not
    # old_fp, but the visible F3 token is untouched.
    result1 = prov.post_findings(
        [reworded_finding], DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA), event="REQUEST_CHANGES",
    )
    assert result1.ok
    patches = [c for c in rec.calls if c[0] == "PATCH" and c[1].endswith("/pulls/comments/1")]
    assert len(patches) == 1

    # Simulate dismiss.py: a human replies `/ai-pr-review dismiss` on that
    # thread, reads the still-visible F3 token, and records a "dismissed"
    # verdict -- against the finding's original fingerprint, per #720's own
    # narrative of what the reverse F-id lookup can return. dismiss.py also
    # always resolves the underlying GraphQL thread.
    state["canonical_body"] = upsert_verdicts_marker(state["canonical_body"], {old_fp: "dismissed"})
    state["resolved"] = True

    # Run 2: same reworded finding, unchanged. Must be suppressed, not
    # reposted as "new".
    result2 = prov.post_findings(
        [reworded_finding], DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA), event="REQUEST_CHANGES",
    )
    assert result2.ok
    assert result2.suppressed == 1


# ---------------------------------------------------------------------------
# Concurrency guard: PUT abandoned when canonical changed / head advanced
# ---------------------------------------------------------------------------


def test_put_falls_back_to_post_when_canonical_changed_concurrently() -> None:
    """Regression note: this test previously passed `event="APPROVE"` against
    a `CHANGES_REQUESTED` canonical -- decide_action's event/state-mismatch
    check (`_EVENT_FOR_STATE.get(canonical.state) != event`) forces `"post"`
    on its own for that combination, before `_try_put_canonical` (and thus
    the mocked GET /reviews/10 concurrent-write detection this test exists
    to cover) is ever reached. `rec.calls` proves GET /reviews/10 was never
    even called under the old setup. `event` now matches the canonical's
    state (REQUEST_CHANGES <-> CHANGES_REQUESTED) so decide_action actually
    reaches "put" and this test exercises what its name claims."""
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            # Concurrent write happened: state flipped to DISMISSED since selection.
            return httpx.Response(200, json={"state": "DISMISSED", "body": canonical_body})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 30, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )
    assert result.ok
    assert result.reused_review is False
    assert result.review_id == 30
    rechecks = [c for c in rec.calls if c[0] == "GET" and c[1].endswith("/reviews/10")]
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert len(rechecks) == 1
    assert len(posts) == 1
    assert puts == []


def test_put_falls_back_to_post_when_recheck_fetch_fails() -> None:
    """Distinct from the concurrent-write case above: here the re-fetch
    itself fails at the HTTP level (GET /reviews/{id} errors), so
    get_review_state_and_body returns None rather than a changed
    state/body. _try_put_canonical's contract is "None means don't trust
    this write" -- must fall back to posting a fresh review, not raise or
    silently skip."""
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(500, text="internal error")
        # Both of these would let a "trust the original canonical
        # state/body when the re-fetch fails" regression sail through as a
        # successful PUT instead of falling back to POST -- present so this
        # test actually discriminates between the two behaviors rather than
        # having both fall through to the same POST via an unrelated 404.
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 30, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )
    assert result.ok
    assert result.reused_review is False
    assert result.review_id == 30
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert len(posts) == 1
    assert puts == []


def test_head_sha_advanced_skips_canonical_write() -> None:
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "APPROVED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "APPROVED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            # A newer run has already advanced the PR's head.
            return httpx.Response(200, json={"head": {"sha": _NEW_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            raise AssertionError("must not PUT once the PR head has advanced past this diff")
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    assert result.reused_review is True
    # skipped=True distinguishes "no write happened, a newer run owns the
    # canonical" from an actual PUT -- orchestrate.py must not advance the
    # SHA watermark to this run's now-stale diff.head_sha on this result.
    assert result.skipped is True
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert puts == []


# ---------------------------------------------------------------------------
# Fail-soft: GraphQL 4xx degrades to legacy "post everything" behavior
# ---------------------------------------------------------------------------


def test_graphql_failure_degrades_to_posting_everything_as_new() -> None:
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return httpx.Response(500, text="internal error")
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 40, "state": "CHANGES_REQUESTED"})
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            return httpx.Response(200, json={"id": 10, "state": "DISMISSED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [_finding("new issue", severity="High")],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.review_id == 40
    assert result.reused_review is False
    # A failed/incomplete thread fetch must never be treated as "zero
    # unresolved owned threads" -- that would let the canonical CR review be
    # dismissed based on a fetch that could easily be missing an open High
    # finding's thread, reopening the auto-approve hole this feature's own
    # dismiss gate exists to close.
    dismissals = [c for c in rec.calls if "/dismissals" in c[1]]
    assert dismissals == []


def test_dismiss_superseded_review_only_after_replacement_confirmed_posted() -> None:
    """Dismissing the superseded canonical review before confirming the
    replacement actually posted as REQUEST_CHANGES would, on a mid-run
    failure, leave the PR with no blocking review at all -- silently
    unblocking something that should still be blocked. The canonical must
    stay standing when the fresh post degrades."""
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError(
                "must never dismiss the canonical before the replacement "
                "review is confirmed to have posted as REQUEST_CHANGES"
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            # Both the initial POST and the COMMENT-retry fallback fail,
            # degrading _post_new_review all the way to a plain issue
            # comment (event becomes "COMMENT", degraded_to_comment=True).
            return httpx.Response(422, text="validation failed")
        if req.method == "POST" and url.endswith("/issues/1/comments"):
            return httpx.Response(201, json={"id": 99})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [_finding("brand new issue", severity="High")],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.degraded_to_comment is True
    assert result.event != "REQUEST_CHANGES"


def test_escalate_patch_failure_does_not_count_updated_or_send_notification() -> None:
    """`_apply_thread_update` only returns True (and `post_findings` only
    counts `inline_updated`/sends the escalation reply) when the PATCH
    actually landed -- documented in `_apply_thread_update`'s own docstring:
    a failed PATCH leaves the comment showing the old content/severity, so a
    reply claiming "severity escalated" would itself be a silent-failure
    risk. This locks that behavior in against a regression that always
    counts/notifies regardless of the PATCH outcome."""
    old_finding = _finding("weak validation", severity="Low", line=5, category="other")
    existing_comment_body = _build_inline_comment_body(old_finding)
    canonical_body = _footer_body()
    escalated_finding = _finding("weak validation", severity="Critical", line=5, category="other")

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=5,
                )]
            )
        if req.method == "PATCH" and url.endswith("/pulls/comments/1"):
            return httpx.Response(500, text="internal error")
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [escalated_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.inline_updated == 0
    replies = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/comments/1/replies")]
    assert replies == []


# ---------------------------------------------------------------------------
# Carried-forward findings (#766): counted-but-invisible headline fix
# ---------------------------------------------------------------------------


def test_carried_forward_medium_thread_rendered_and_stays_approved() -> None:
    """Reproduces the reported bug: this run finds nothing new, but a
    Medium-severity bot-owned thread from an earlier run is still open and
    untouched. Before #766 the headline claimed "Findings: 1 (0 inline)"
    with no finding text and no link anywhere in the body. The count must
    now be backed by a visible, linked bullet, the inline count must count
    the thread it's actually counting, and Medium must not force the
    APPROVE away (only Critical/High does)."""
    open_finding = _finding("pin apt versions", severity="Medium", file="Dockerfile", line=44)
    open_comment_body = _build_inline_comment_body(open_finding, finding_id=2)

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th-open", comment_id=3919758142, review_id=5,
                    body=open_comment_body, path="Dockerfile", line=44,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 40, "state": "APPROVED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    assert result.event == "APPROVE"
    assert result.degraded_to_comment is False

    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1
    posted_body = posts[0][2]["body"]
    assert "**Findings:** 1 (1 inline)" in posted_body
    assert "### Still open from earlier reviews (1)" in posted_body
    assert "**[F2]**" in posted_body
    assert "Dockerfile:44" in posted_body
    assert "#discussion_r3919758142" in posted_body
    assert "https://github.com/o/r/pull/1#discussion_r3919758142" in posted_body


def test_carried_forward_critical_thread_downgrades_approve_to_comment() -> None:
    """A still-open Critical thread must block a fresh APPROVE: on GitHub a
    newer APPROVE from the same reviewer supersedes an older
    CHANGES_REQUESTED review, so posting one here would silently unblock a
    PR that should stay blocked. `post_findings` must downgrade to COMMENT
    (a no-op on review state) and flag `degraded_to_comment` so
    reporting.py's existing "intended event was APPROVE but posted as
    COMMENT" warning fires."""
    open_finding = _finding("SQL built from request input", severity="Critical", file="app.py", line=12)
    open_comment_body = _build_inline_comment_body(open_finding, finding_id=1)

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th-crit", comment_id=555, review_id=5,
                    body=open_comment_body, path="app.py", line=12,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            posted = _j.loads(req.content)
            assert posted["event"] == "COMMENT"
            return httpx.Response(201, json={"id": 41, "state": "COMMENTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    assert result.event == "COMMENT"
    assert result.degraded_to_comment is True
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1
    posted_body = posts[0][2]["body"]
    assert "## AI Review Findings" in posted_body
    assert "### Still open from earlier reviews (1)" in posted_body
    assert "**[Critical]**" in posted_body


def test_carried_forward_thread_without_finding_id_omits_fid_token() -> None:
    """A legacy thread (posted before the F-ID feature, or whose finding_id
    can't be recovered) must still render -- just without inventing an
    `[F<n>]` token."""
    open_finding = _finding("legacy finding", severity="Low", file="README.md", line=3)
    open_comment_body = _build_inline_comment_body(open_finding)  # no finding_id

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th-legacy", comment_id=99, review_id=5,
                    body=open_comment_body, path="README.md", line=3,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 42, "state": "APPROVED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    posted_body = posts[0][2]["body"]
    assert "### Still open from earlier reviews (1)" in posted_body
    assert "**[F" not in posted_body.split("### Still open")[1]
    assert "README.md:3" in posted_body


def test_carried_forward_thread_path_with_backtick_cannot_break_code_span() -> None:
    """A PR author fully controls the diff's file paths, and both backticks
    and newlines are valid in a filename on most filesystems. The rendered
    location is wrapped in a single Markdown code span (`` `{location}` ``);
    a raw backtick or newline in the path must not be able to close that
    span early and let attacker-chosen text render as live Markdown (e.g. a
    fake link) under the bot's own trusted identity."""
    evil_path = "src/x`[Approved by maintainer](https://evil.example)`.py"
    open_finding = _finding("evil path finding", severity="Low", file=evil_path, line=1)
    open_comment_body = _build_inline_comment_body(open_finding, finding_id=9)

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th-evil", comment_id=1, review_id=5,
                    body=open_comment_body, path=evil_path, line=1,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 44, "state": "APPROVED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    posted_body = posts[0][2]["body"]
    section = posted_body.split("### Still open from earlier reviews")[1]
    bullet_line = next(line for line in section.splitlines() if line.startswith("- "))
    # The payload's own raw backticks would otherwise close the code span
    # early and let "[Approved by maintainer](https://evil.example)" parse
    # as a real Markdown link outside it. Exactly two backticks total means
    # the span was never broken, so that text -- still present, just inert
    # -- renders as plain monospace, not a clickable link.
    assert "`" in evil_path
    assert bullet_line.count("`") == 2
    span = bullet_line.split("`")[1]
    assert "[Approved by maintainer](https://evil.example)" in span


def test_carried_forward_incomplete_thread_fetch_blocks_approve_when_canonical_exists() -> None:
    """An incomplete thread fetch must not be treated as "found nothing to
    carry forward": if a canonical review already exists (this bot has an
    active review on this PR), a failed GraphQL fetch could easily be
    hiding one of its still-open Critical/High threads. Must downgrade to
    COMMENT exactly as if that thread had actually been found."""
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "APPROVED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return httpx.Response(500, text="internal error")
        if req.method == "PUT" and url.endswith("/reviews/10"):
            raise AssertionError("must not PUT an already-submitted review's state away")
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 45, "state": "COMMENTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    assert result.event == "COMMENT"
    assert result.degraded_to_comment is True
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert puts == []


def test_carried_forward_incomplete_thread_fetch_does_not_block_first_ever_approve() -> None:
    """The incomplete-fetch guard is deliberately narrower than "any fetch
    failure blocks approval": with no canonical review at all (this PR has
    never had a bot review before), there is nothing to carry forward
    regardless of whether the thread fetch succeeded, so a transient
    GraphQL blip must not needlessly downgrade this PR's first-ever clean
    APPROVE to a COMMENT."""

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return httpx.Response(500, text="internal error")
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 46, "state": "APPROVED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    assert result.event == "APPROVE"
    assert result.degraded_to_comment is False


def test_carried_forward_high_thread_forces_post_over_put() -> None:
    """`action == "put"` only ever PATCHes an existing review's body --
    GitHub's PUT /reviews/{id} cannot change a review's already-submitted
    state. If a High/Critical carried-forward thread would normally have
    let this run reuse an already-`APPROVED` canonical review (`put`), that
    reuse must be abandoned in favor of a fresh `post`: PUTting a
    findings-flavored body under a badge that still says "Approved" would
    be a worse, self-contradicting state than either alone."""
    canonical_body = _footer_body()
    open_finding = _finding("hardcoded credential", severity="High", file="config.py", line=8)
    open_comment_body = _build_inline_comment_body(open_finding, finding_id=3)

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "APPROVED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th-high", comment_id=77, review_id=10,
                    body=open_comment_body, path="config.py", line=8,
                )]
            )
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "APPROVED", "body": canonical_body})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            raise AssertionError("must not PUT an already-submitted review's state away")
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 43, "state": "COMMENTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    assert result.reused_review is False
    assert result.event == "COMMENT"
    assert result.degraded_to_comment is True
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert puts == []
    assert len(posts) == 1
