"""Tests for ai_pr_review.vcs._canonical — canonical-review reuse, read side.

Pure-logic module: no HTTP involved. Covers the full per-finding decision
table, canonical-review selection, verdict-union/tombstone semantics,
fingerprint<->location round-tripping, legacy-thread fallback parsing, and
decide_action's put-vs-post gate.
"""

from __future__ import annotations

from ai_pr_review.findings.models import Finding
from ai_pr_review.vcs._canonical import (
    CanonicalReview,
    Classified,
    PriorThread,
    classify,
    decide_action,
    dedupe_thread_claims,
    fingerprint_location,
    merge_verdicts,
    parse_prior_thread,
    select_canonical,
)
from ai_pr_review.vcs._finding_ids import fingerprint
from ai_pr_review.vcs.marker import build_inline_meta_marker, build_verdicts_marker

_FOOTER_BODY = (
    "## AI Review Findings\n\nsome body\n\n---\n"
    "*AI Review — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
)


def _finding(
    text: str = "issue",
    *,
    source: str = "code-reviewer",
    file: str = "app.py",
    line: int | None = 10,
    severity: str = "Medium",
    category: str = "other",
) -> Finding:
    return Finding(
        severity=severity,
        confidence=80,
        finding=text,
        source=source,
        file=file,
        line=line,
        category=category,
    )


def _thread(
    *,
    thread_id: str = "t1",
    comment_id: int = 1,
    review_id: int | None = 10,
    path: str = "app.py",
    line: int | None = 10,
    start_line: int | None = None,
    is_resolved: bool = False,
    is_outdated: bool = False,
    severity: str | None = "Medium",
    category: str | None = "other",
    fp: str | None = None,
    finding_id: int | None = None,
) -> PriorThread:
    return PriorThread(
        thread_id=thread_id,
        comment_id=comment_id,
        review_id=review_id,
        path=path,
        line=line,
        start_line=start_line,
        is_resolved=is_resolved,
        is_outdated=is_outdated,
        severity=severity,
        category=category,
        fingerprint=fp,
        finding_id=finding_id,
    )


# ---------------------------------------------------------------------------
# select_canonical
# ---------------------------------------------------------------------------


def test_select_canonical_picks_highest_id_regardless_of_state() -> None:
    reviews = [
        {"id": 5, "state": "DISMISSED", "body": "old"},
        {"id": 9, "state": "CHANGES_REQUESTED", "body": "newest"},
        {"id": 7, "state": "APPROVED", "body": "middle"},
    ]
    canonical = select_canonical(reviews)
    assert canonical == CanonicalReview(review_id=9, state="CHANGES_REQUESTED", body="newest")


def test_select_canonical_empty_returns_none() -> None:
    assert select_canonical([]) is None


def test_select_canonical_skips_non_int_id() -> None:
    assert select_canonical([{"id": "not-an-int", "state": "COMMENTED", "body": ""}]) is None


# ---------------------------------------------------------------------------
# merge_verdicts — union + tombstone precedence
# ---------------------------------------------------------------------------


def test_merge_verdicts_unions_across_bodies() -> None:
    reviews = [
        {"id": 1, "body": build_verdicts_marker({"fp-a": "dismissed"})},
        {"id": 2, "body": build_verdicts_marker({"fp-b": "fixed"})},
    ]
    assert merge_verdicts(reviews) == {"fp-a": "dismissed", "fp-b": "fixed"}


def test_merge_verdicts_recurred_tombstone_in_older_body_wins_over_stale_fixed_in_newer() -> None:
    """The newest review's marker only ever reflects the state *as of when it
    was written* -- a "fixed" entry seeded from an even-older body before the
    write side's union-seeding fix would otherwise resurrect a finding this
    run already flagged as recurred. Folding bodies in ascending id order
    means the later "recurred" write wins regardless of which review it
    physically landed on."""
    reviews = [
        {"id": 1, "body": build_verdicts_marker({"fp-a": "fixed"})},
        {"id": 2, "body": build_verdicts_marker({"fp-a": "recurred"})},
    ]
    assert merge_verdicts(reviews) == {"fp-a": "recurred"}
    # Order in the input sequence must not matter -- only review id order.
    reversed_input = list(reversed(reviews))
    assert merge_verdicts(reversed_input) == {"fp-a": "recurred"}


def test_merge_verdicts_empty() -> None:
    assert merge_verdicts([]) == {}


# ---------------------------------------------------------------------------
# fingerprint_location round-trip
# ---------------------------------------------------------------------------


def test_fingerprint_location_round_trips() -> None:
    f = _finding("some issue", file="app.py", line=42, source="code-reviewer")
    fp = fingerprint(f)
    file_, line = fingerprint_location(fp)
    assert file_ == "app.py"
    assert line == 42


def test_fingerprint_location_handles_pipe_in_path() -> None:
    f = _finding("issue", file="weird|path/app.py", line=3)
    fp = fingerprint(f)
    file_, line = fingerprint_location(fp)
    assert file_ == "weird|path/app.py"
    assert line == 3


def test_fingerprint_location_malformed_returns_empty() -> None:
    assert fingerprint_location("not-a-fingerprint") == ("", None)


# ---------------------------------------------------------------------------
# classify() — the full per-finding decision table
# ---------------------------------------------------------------------------


def test_classify_no_match_is_new() -> None:
    f = _finding(file="app.py", line=100)
    result = classify(f, verdicts={}, all_threads=[])
    assert result.kind == "new"
    assert result.thread is None


def test_classify_exact_dismissed_match_suppresses() -> None:
    f = _finding(file="app.py", line=10)
    fp = fingerprint(f)
    result = classify(f, verdicts={fp: "dismissed"}, all_threads=[])
    assert result.kind == "suppressed"


def test_classify_fuzzy_dismissed_match_compatible_category_and_severity_suppresses() -> None:
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="lint")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="lint", is_resolved=True)
    new_finding = _finding("similar nit", file="app.py", line=12, severity="Low", category="lint")

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "suppressed"


def test_classify_fuzzy_dismissed_match_incompatible_category_falls_through() -> None:
    """This is the exact information-loss case the per-comment metadata
    marker exists to prevent: a dismissed Low lint nit two lines away must
    never silently swallow an unrelated new secret-leak finding."""
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="lint")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="lint", is_resolved=True)
    new_finding = _finding(
        "leaked API key", file="app.py", line=11, severity="Critical", category="secret"
    )

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_higher_severity_falls_through() -> None:
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="other")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="other", is_resolved=True)
    new_finding = _finding("real bug", file="app.py", line=11, severity="Critical", category="other")

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_unrecoverable_severity_never_suppresses() -> None:
    """A body-level dismissed finding has no comment, hence no metadata
    marker -- its severity is permanently unrecoverable and must never be
    treated as an escalation waiver. Only an exact fingerprint match can
    suppress a body-level dismissal."""
    dismissed = _finding("body-level nit", file="app.py", line=10, severity="Low")
    dismissed_fp = fingerprint(dismissed)
    new_finding = _finding("nearby issue", file="app.py", line=11, severity="Low")

    result = classify(new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[])
    assert result.kind == "new"


def test_classify_exact_fixed_match_is_recurred_with_thread() -> None:
    f = _finding(file="app.py", line=10, severity="High")
    fp = fingerprint(f)
    thread = _thread(fp=fp, is_resolved=True, severity="High")
    result = classify(f, verdicts={fp: "fixed"}, all_threads=[thread])
    assert result.kind == "recurred"
    assert result.thread is thread


def test_classify_exact_fixed_match_body_level_recurred_without_thread() -> None:
    f = _finding(file="app.py", line=10)
    fp = fingerprint(f)
    result = classify(f, verdicts={fp: "fixed"}, all_threads=[])
    assert result.kind == "recurred"
    assert result.thread is None


def test_classify_fuzzy_only_fixed_match_is_not_recurred() -> None:
    """Row: 'matches a fixed thread, fuzzy-only (not exact) match' -> falls
    through as genuinely new (or update/escalate if it also fuzzy-matches an
    *open* thread) -- the recurrence check is deliberately exact-only."""
    fixed = _finding("original", file="app.py", line=10)
    fixed_fp = fingerprint(fixed)
    reworded = _finding("reworded text", file="app.py", line=11)

    result = classify(reworded, verdicts={fixed_fp: "fixed"}, all_threads=[])
    assert result.kind == "new"


def test_classify_open_thread_same_severity_is_update() -> None:
    thread = _thread(path="app.py", line=10, severity="Medium", category="other")
    f = _finding(file="app.py", line=11, severity="Medium", category="other")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "update"
    assert result.thread is thread


def test_classify_open_thread_lower_severity_is_update() -> None:
    thread = _thread(path="app.py", line=10, severity="High", category="other")
    f = _finding(file="app.py", line=11, severity="Low", category="other")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "update"


def test_classify_open_thread_escalated_severity_is_escalate() -> None:
    thread = _thread(path="app.py", line=10, severity="Low", category="other")
    f = _finding(file="app.py", line=11, severity="Critical", category="other")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "escalate"
    assert result.thread is thread


def test_classify_outdated_thread_match_reclassifies_as_new() -> None:
    thread = _thread(path="app.py", line=10, severity="Low", is_outdated=True)
    f = _finding(file="app.py", line=11, severity="Critical")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"
    assert result.thread is None


def test_classify_incompatible_category_does_not_match_open_thread() -> None:
    thread = _thread(path="app.py", line=10, severity="Medium", category="secret")
    f = _finding(file="app.py", line=11, severity="Critical", category="injection")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"


def test_classify_beyond_proximity_window_does_not_match() -> None:
    thread = _thread(path="app.py", line=10, severity="Medium")
    f = _finding(file="app.py", line=20, severity="Medium")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"


def test_dedupe_thread_claims_keeps_highest_severity_demotes_rest_to_new() -> None:
    """Two distinct findings within PROXIMITY_LINES of the same open thread
    both fuzzy-match it independently (classify() has no cross-finding
    visibility). Applying both side effects would PATCH the same comment
    twice, silently dropping one finding. dedupe_thread_claims keeps the
    higher-severity claim and sends the other back through as "new" so it
    gets its own slot instead of disappearing."""
    thread = _thread(thread_id="shared", line=100, severity="Low")
    low = _finding("nit", line=99, severity="Low")
    high = _finding("real bug", line=101, severity="Critical")
    classified = [
        Classified(low, "update", thread),
        Classified(high, "escalate", thread),
    ]
    result = dedupe_thread_claims(classified)
    kept = [c for c in result if c.thread is not None]
    demoted = [c for c in result if c.thread is None]
    assert len(kept) == 1
    assert kept[0].finding is high
    assert kept[0].kind == "escalate"
    assert len(demoted) == 1
    assert demoted[0].finding is low
    assert demoted[0].kind == "new"


def test_dedupe_thread_claims_is_a_noop_when_no_collision() -> None:
    t1 = _thread(thread_id="t1", line=10)
    t2 = _thread(thread_id="t2", line=50)
    f1 = _finding("a", line=10)
    f2 = _finding("b", line=50)
    classified = [Classified(f1, "update", t1), Classified(f2, "update", t2)]
    result = dedupe_thread_claims(classified)
    assert result == classified


def test_classify_resolved_non_fixed_thread_is_not_a_fuzzy_open_match() -> None:
    """A resolved thread with no verdict at all (e.g. resolved by
    resolve_stale's routine housekeeping sweep, not a human verdict) must not
    be treated as still-open for the update/escalate check."""
    thread = _thread(path="app.py", line=10, severity="Medium", is_resolved=True)
    f = _finding(file="app.py", line=10, severity="Medium")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"


# ---------------------------------------------------------------------------
# parse_prior_thread — meta marker fast path + legacy fallback
# ---------------------------------------------------------------------------


def _thread_node(
    *,
    body: str,
    author: str = "github-actions",
    thread_id: str = "th1",
    comment_id: int = 100,
    review_id: int = 10,
    is_resolved: bool = False,
    is_outdated: bool = False,
    path: str = "app.py",
    line: int | None = 10,
    original_line: int | None = None,
    start_line: int | None = None,
) -> dict:
    return {
        "id": thread_id,
        "isResolved": is_resolved,
        "isOutdated": is_outdated,
        "path": path,
        "line": line,
        "originalLine": original_line,
        "startLine": start_line,
        "comments": {
            "nodes": [
                {
                    "databaseId": comment_id,
                    "body": body,
                    "author": {"login": author},
                    "pullRequestReview": {"databaseId": review_id},
                }
            ]
        },
    }


def test_parse_prior_thread_reads_meta_marker() -> None:
    f = _finding(file="app.py", line=10, severity="High", category="secret")
    fp = fingerprint(f)
    marker = build_inline_meta_marker(fingerprint=fp, category="secret", severity="High")
    body = f"🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->\n{marker}"
    node = _thread_node(body=body)

    thread = parse_prior_thread(node, bot_login="github-actions")
    assert thread is not None
    assert thread.fingerprint == fp
    assert thread.category == "secret"
    assert thread.severity == "High"
    assert thread.path == "app.py"
    assert thread.line == 10


def test_parse_prior_thread_not_owned_by_us_returns_none() -> None:
    node = _thread_node(body="some comment", author="someone-else")
    assert parse_prior_thread(node, bot_login="github-actions") is None


def test_parse_prior_thread_legacy_falls_back_to_header_severity() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body)

    thread = parse_prior_thread(node, bot_login="github-actions")
    assert thread is not None
    assert thread.severity == "High"
    assert thread.category is None
    assert thread.fingerprint is None


def test_parse_prior_thread_legacy_recovers_fingerprint_via_id_map_bodies() -> None:
    f = _finding("leaked key", file="app.py", line=10, source="code-reviewer", severity="High")
    fp = fingerprint(f)
    from ai_pr_review.vcs.marker import build_id_map_marker

    id_map_body = "## AI Review Findings\n" + build_id_map_marker({fp: 3})
    body = "🔴 **[High]** **[F3]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body)

    thread = parse_prior_thread(
        node, bot_login="github-actions", id_map_bodies=[id_map_body]
    )
    assert thread is not None
    assert thread.fingerprint == fp
    assert thread.finding_id == 3


def test_parse_prior_thread_no_comments_returns_none() -> None:
    node = {
        "id": "th1", "isResolved": False, "isOutdated": False,
        "path": "app.py", "line": 10, "originalLine": None, "startLine": None,
        "comments": {"nodes": []},
    }
    assert parse_prior_thread(node, bot_login="github-actions") is None


def test_parse_prior_thread_falls_back_to_original_line_when_line_absent() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, line=None, original_line=7)
    thread = parse_prior_thread(node, bot_login="github-actions")
    assert thread is not None
    assert thread.line == 7


def test_parse_prior_thread_recognizes_graphql_style_login_when_normalized() -> None:
    """GitHub's GraphQL API reports the bot's login without the REST-style
    "[bot]" suffix (verified live against a real thread). GitHubProvider
    passes graphql_bot_login(self.config.bot_login) (issue #717's fix) --
    which strips that suffix -- to parse_prior_thread for exactly this
    reason; this test locks that in with the exact normalized value the
    call site produces."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, author="github-actions")
    assert parse_prior_thread(node, bot_login="github-actions") is not None


def test_parse_prior_thread_rest_style_bot_login_rejects_graphql_login() -> None:
    """Documents the exact bug fixed by issue #717: comparing a
    GraphQL-sourced "github-actions" author against the raw, un-normalized
    REST-style "github-actions[bot]" constant makes every real thread look
    unowned. This is why the call site normalizes via graphql_bot_login()
    before comparing, rather than passing the raw constant."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, author="github-actions")
    assert parse_prior_thread(node, bot_login="github-actions[bot]") is None


def test_parse_prior_thread_normalized_login_still_rejects_different_bot() -> None:
    """Defense in depth is preserved by normalization, not lost: a
    different bot's GraphQL login (also suffix-less) must still fail to
    match our normalized bot_login."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, author="other-automation-bot")
    assert parse_prior_thread(node, bot_login="github-actions") is None


# ---------------------------------------------------------------------------
# decide_action
# ---------------------------------------------------------------------------


def test_decide_action_no_canonical_posts() -> None:
    action = decide_action(None, event="COMMENT", classified=[], any_new_inline_eligible=False)
    assert action == "post"


def test_decide_action_dismissed_canonical_posts() -> None:
    canonical = CanonicalReview(review_id=1, state="DISMISSED", body=_FOOTER_BODY)
    action = decide_action(
        canonical, event="COMMENT", classified=[], any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_event_mismatch_posts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    action = decide_action(
        canonical, event="APPROVE", classified=[], any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_event_matches_state_puts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=[], any_new_inline_eligible=False
    )
    assert action == "put"


def test_decide_action_missing_footer_posts() -> None:
    """Guards against PUTing a findings body over a human-facing message
    (e.g. GitHubProvider.submit_approval's marker-less APPROVE)."""
    canonical = CanonicalReview(
        review_id=1, state="APPROVED", body="Auto-approved: all findings resolved."
    )
    action = decide_action(
        canonical, event="APPROVE", classified=[], any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_new_inline_eligible_posts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(_finding(severity="Low"), verdicts={}, all_threads=[])]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=True
    )
    assert action == "post"


def test_decide_action_new_high_severity_body_level_still_posts() -> None:
    """A High/Critical finding that can't get an inline anchor (out-of-diff,
    over max_inline) must still surface as a fresh review -- new information
    has to be visible, not silently PUT into the body."""
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(_finding(severity="High"), verdicts={}, all_threads=[])]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_new_high_severity_known_fingerprint_puts() -> None:
    """Issue #719: a persistent body-level High/Critical finding whose exact
    fingerprint is already visible in the canonical's own prior body (a
    known fingerprint) is not genuinely new information to a human -- the
    PUT still renders it in the body every time, so it should not force a
    fresh review on every single rerun."""
    f = _finding(severity="High")
    fp = fingerprint(f)
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(f, verdicts={}, all_threads=[])]
    action = decide_action(
        canonical,
        event="REQUEST_CHANGES",
        classified=classified,
        any_new_inline_eligible=False,
        known_fingerprints=frozenset({fp}),
    )
    assert action == "put"


def test_decide_action_new_high_severity_unknown_fingerprint_still_posts() -> None:
    """A different High/Critical finding (not in known_fingerprints) must
    still force post even when the canonical carries some other known
    fingerprint -- the exemption is per-fingerprint, not a blanket pass."""
    f = _finding(severity="High")
    other_fp = fingerprint(_finding("a different finding entirely", severity="Low"))
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(f, verdicts={}, all_threads=[])]
    action = decide_action(
        canonical,
        event="REQUEST_CHANGES",
        classified=classified,
        any_new_inline_eligible=False,
        known_fingerprints=frozenset({other_fp}),
    )
    assert action == "post"


def test_decide_action_new_low_severity_body_level_puts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(_finding(severity="Low"), verdicts={}, all_threads=[])]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=False
    )
    assert action == "put"


def test_decide_action_only_update_and_escalate_puts() -> None:
    thread = _thread(path="app.py", line=10, severity="Low")
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [
        classify(_finding(file="app.py", line=11, severity="Critical"), verdicts={}, all_threads=[thread])
    ]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=False
    )
    assert action == "put"
