"""Tests for ai_pr_review.vcs._canonical — canonical-review reuse, read side.

Pure-logic module: no HTTP involved. Covers the full per-finding decision
table, canonical-review selection, verdict-union/tombstone semantics,
fingerprint<->location round-tripping, legacy-thread fallback parsing, and
decide_action's put-vs-post gate.
"""

from __future__ import annotations

import pytest

from ai_pr_review.findings.models import Finding
from ai_pr_review.vcs._canonical import (
    CanonicalReview,
    Classified,
    PriorThread,
    classify,
    decide_action,
    dedupe_thread_claims,
    fingerprint_location,
    merge_verdicts,
    parse_gitlab_prior_thread,
    parse_prior_thread,
    select_canonical,
)
from ai_pr_review.vcs._finding_ids import fingerprint
from ai_pr_review.vcs.marker import (
    build_id_map_marker,
    build_inline_meta_marker,
    build_verdicts_marker,
)

_FOOTER_BODY = (
    "## AI Review Findings\n\nsome body\n\n---\n"
    "*AI Review — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
)


def _finding(
    text: str = "issue",
    *,
    source: str = "code-reviewer",
    file: str = "app.py",
    line: int | None = 10,
    severity: str = "Medium",
    category: str = "other",
) -> Finding:
    return Finding(
        severity=severity,
        confidence=80,
        finding=text,
        source=source,
        file=file,
        line=line,
        category=category,
    )


def _thread(
    *,
    thread_id: str = "t1",
    comment_id: int = 1,
    review_id: int | None = 10,
    path: str = "app.py",
    line: int | None = 10,
    start_line: int | None = None,
    is_resolved: bool = False,
    is_outdated: bool = False,
    severity: str | None = "Medium",
    category: str | None = "other",
    fp: str | None = None,
    finding_id: int | None = None,
    prior_fingerprints: frozenset[str] = frozenset(),
) -> PriorThread:
    return PriorThread(
        thread_id=thread_id,
        comment_id=comment_id,
        review_id=review_id,
        path=path,
        line=line,
        start_line=start_line,
        is_resolved=is_resolved,
        is_outdated=is_outdated,
        severity=severity,
        category=category,
        fingerprint=fp,
        finding_id=finding_id,
        prior_fingerprints=prior_fingerprints,
    )


# ---------------------------------------------------------------------------
# select_canonical
# ---------------------------------------------------------------------------


def test_select_canonical_picks_highest_id_regardless_of_state() -> None:
    reviews = [
        {"id": 5, "state": "DISMISSED", "body": "old"},
        {"id": 9, "state": "CHANGES_REQUESTED", "body": "newest"},
        {"id": 7, "state": "APPROVED", "body": "middle"},
    ]
    canonical = select_canonical(reviews)
    assert canonical == CanonicalReview(review_id=9, state="CHANGES_REQUESTED", body="newest")


def test_select_canonical_empty_returns_none() -> None:
    assert select_canonical([]) is None


def test_select_canonical_skips_non_int_id() -> None:
    # Non-empty body, so the empty-body filter (added for the reply-created
    # implicit-review fix) isn't what makes this None -- it's genuinely the
    # non-int `id` branch being exercised.
    assert (
        select_canonical([{"id": "not-an-int", "state": "COMMENTED", "body": "some body"}])
        is None
    )


def test_select_canonical_skips_empty_and_whitespace_bodies() -> None:
    """GitHub auto-creates a body-less review (state COMMENTED) every time
    the bot replies to an inline comment via the REST replies endpoint. Left
    unfiltered, that review -- often the highest id -- becomes canonical and
    GitHub then rejects any PUT to it (HTTP 422: "Could not edit a review
    with a missing body"), silently dropping every verdict recorded from
    then on. The next non-empty review, regardless of its own id gap, must
    be selected instead."""
    reviews = [
        {"id": 5, "state": "CHANGES_REQUESTED", "body": "## AI Review Findings\n..."},
        {"id": 6, "state": "COMMENTED", "body": ""},
        {"id": 7, "state": "COMMENTED", "body": "   \n\t  "},
    ]
    canonical = select_canonical(reviews)
    assert canonical == CanonicalReview(
        review_id=5, state="CHANGES_REQUESTED", body="## AI Review Findings\n..."
    )


def test_select_canonical_all_bodies_empty_returns_none() -> None:
    reviews = [
        {"id": 1, "state": "COMMENTED", "body": ""},
        {"id": 2, "state": "COMMENTED", "body": None},
    ]
    assert select_canonical(reviews) is None


def test_select_canonical_keeps_footerless_non_empty_body() -> None:
    """A non-empty body with no footer marker (e.g. `GitHubProvider.
    submit_approval`'s human-facing auto-approve message, issue #590) must
    still be eligible as canonical -- the empty-body filter is not a footer
    check. `decide_action` is what separately falls back to `"post"` for a
    footer-less canonical; `select_canonical` must not pre-empt that by
    excluding it here on a different criterion."""
    reviews = [
        {"id": 3, "state": "CHANGES_REQUESTED", "body": "## AI Review Findings\n..."},
        {"id": 9, "state": "APPROVED", "body": "@alice cleared the last active finding."},
    ]
    canonical = select_canonical(reviews)
    assert canonical == CanonicalReview(
        review_id=9, state="APPROVED", body="@alice cleared the last active finding."
    )


# ---------------------------------------------------------------------------
# merge_verdicts — union + tombstone precedence
# ---------------------------------------------------------------------------


def test_merge_verdicts_unions_across_bodies() -> None:
    reviews = [
        {"id": 1, "body": build_verdicts_marker({"fp-a": "dismissed"})},
        {"id": 2, "body": build_verdicts_marker({"fp-b": "fixed"})},
    ]
    assert merge_verdicts(reviews) == {"fp-a": "dismissed", "fp-b": "fixed"}


def test_merge_verdicts_recurred_tombstone_in_older_body_wins_over_stale_fixed_in_newer() -> None:
    """The newest review's marker only ever reflects the state *as of when it
    was written* -- a "fixed" entry seeded from an even-older body before the
    write side's union-seeding fix would otherwise resurrect a finding this
    run already flagged as recurred. Folding bodies in ascending id order
    means the later "recurred" write wins regardless of which review it
    physically landed on."""
    reviews = [
        {"id": 1, "body": build_verdicts_marker({"fp-a": "fixed"})},
        {"id": 2, "body": build_verdicts_marker({"fp-a": "recurred"})},
    ]
    assert merge_verdicts(reviews) == {"fp-a": "recurred"}
    # Order in the input sequence must not matter -- only review id order.
    reversed_input = list(reversed(reviews))
    assert merge_verdicts(reversed_input) == {"fp-a": "recurred"}


def test_merge_verdicts_empty() -> None:
    assert merge_verdicts([]) == {}


def test_merge_verdicts_drops_dismissed_entry_contradicted_by_own_id_map() -> None:
    """Issue #755: a review whose own body renders a finding (id-map entry)
    cannot legitimately also claim, in that same body's verdicts marker,
    that the identical fingerprint is "dismissed" -- classify() excludes a
    truly-dismissed finding from rendering entirely. A body making both
    claims at once is self-contradictory; the rendered claim (visible to a
    human) wins and the "dismissed" entry must not be trusted, since
    trusting it would permanently suppress a finding no human ever acted on."""
    contradictory_body = (
        build_id_map_marker({"fp-a": 1, "fp-b": 2})
        + "\n"
        + build_verdicts_marker({"fp-a": "dismissed", "fp-c": "dismissed"})
    )
    reviews = [{"id": 1, "body": contradictory_body}]
    # fp-a: dropped (rendered in this same body's id-map -- contradiction).
    # fp-c: kept ("dismissed" and never rendered here -- no contradiction).
    assert merge_verdicts(reviews) == {"fp-c": "dismissed"}


def test_merge_verdicts_drops_fixed_entry_contradicted_by_own_id_map() -> None:
    """Same self-consistency guard, "fixed" variant: a recurring finding's
    verdict is overwritten to the "recurred" tombstone in the same call that
    renders it (github.py's _apply_classification_side_effects), so a body
    that renders a fingerprint while its own marker still claims "fixed" for
    it is equally contradictory."""
    contradictory_body = (
        build_id_map_marker({"fp-a": 1})
        + "\n"
        + build_verdicts_marker({"fp-a": "fixed"})
    )
    reviews = [{"id": 1, "body": contradictory_body}]
    assert merge_verdicts(reviews) == {}


def test_merge_verdicts_recurred_not_contradicted_by_own_id_map() -> None:
    """The "recurred" tombstone is expected to coexist with a rendered
    id-map entry in the very same body (that's exactly how it gets written
    -- github.py sets it in the same pass that renders the recurrence as a
    body bullet), so it must never trip the self-consistency guard."""
    body = (
        build_id_map_marker({"fp-a": 1})
        + "\n"
        + build_verdicts_marker({"fp-a": "recurred"})
    )
    reviews = [{"id": 1, "body": body}]
    assert merge_verdicts(reviews) == {"fp-a": "recurred"}


# ---------------------------------------------------------------------------
# fingerprint_location round-trip
# ---------------------------------------------------------------------------


def test_fingerprint_location_round_trips() -> None:
    f = _finding("some issue", file="app.py", line=42, source="code-reviewer")
    fp = fingerprint(f)
    file_, line = fingerprint_location(fp)
    assert file_ == "app.py"
    assert line == 42


def test_fingerprint_location_handles_pipe_in_path() -> None:
    f = _finding("issue", file="weird|path/app.py", line=3)
    fp = fingerprint(f)
    file_, line = fingerprint_location(fp)
    assert file_ == "weird|path/app.py"
    assert line == 3


def test_fingerprint_location_malformed_returns_empty() -> None:
    assert fingerprint_location("not-a-fingerprint") == ("", None)


# ---------------------------------------------------------------------------
# classify() — the full per-finding decision table
# ---------------------------------------------------------------------------


def test_classify_no_match_is_new() -> None:
    f = _finding(file="app.py", line=100)
    result = classify(f, verdicts={}, all_threads=[])
    assert result.kind == "new"
    assert result.thread is None


def test_classify_exact_dismissed_match_suppresses() -> None:
    f = _finding(file="app.py", line=10)
    fp = fingerprint(f)
    result = classify(f, verdicts={fp: "dismissed"}, all_threads=[])
    assert result.kind == "suppressed"


def test_classify_fuzzy_dismissed_match_compatible_category_and_severity_suppresses() -> None:
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="lint")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="lint", is_resolved=True)
    new_finding = _finding("similar nit", file="app.py", line=12, severity="Low", category="lint")

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "suppressed"


def test_classify_fuzzy_dismissed_match_incompatible_category_falls_through() -> None:
    """This is the exact information-loss case the per-comment metadata
    marker exists to prevent: a dismissed Low lint nit two lines away must
    never silently swallow an unrelated new secret-leak finding."""
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="lint")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="lint", is_resolved=True)
    new_finding = _finding(
        "leaked API key", file="app.py", line=11, severity="Critical", category="secret"
    )

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_higher_severity_falls_through() -> None:
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="other")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="other", is_resolved=True)
    new_finding = _finding("real bug", file="app.py", line=11, severity="Critical", category="other")

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_unrecoverable_severity_never_suppresses() -> None:
    """A body-level dismissed finding has no comment, hence no metadata
    marker -- its severity is permanently unrecoverable and must never be
    treated as an escalation waiver. Only an exact fingerprint match can
    suppress a body-level dismissal."""
    dismissed = _finding("body-level nit", file="app.py", line=10, severity="Low")
    dismissed_fp = fingerprint(dismissed)
    new_finding = _finding("nearby issue", file="app.py", line=11, severity="Low")

    result = classify(new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[])
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_body_level_finding_never_matches() -> None:
    """A body-level finding (no line, e.g. can't be anchored to a diff line)
    has nothing for a fuzzy location match to compare against -- it must
    fall through to "new" even when a dismissed verdict sits in the exact
    same file, never raise trying to compare against a None `.line`."""
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="lint")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="lint", is_resolved=True)
    body_level_finding = _finding(
        "no location info", file="app.py", line=None, severity="Low", category="lint"
    )

    result = classify(
        body_level_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_different_file_does_not_suppress() -> None:
    """Same line number, same category/severity, but a different file --
    fuzzy dismissed matching is scoped per-file and must not cross files."""
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="lint")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="lint", is_resolved=True)
    new_finding = _finding("similar nit elsewhere", file="other.py", line=10, severity="Low", category="lint")

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_beyond_proximity_window_does_not_suppress() -> None:
    """A dismissed verdict outside PROXIMITY_LINES of the new finding must
    not suppress it, even with identical file/category/severity -- mirrors
    test_classify_beyond_proximity_window_does_not_match, which covers the
    same proximity gate for the still-open-thread fuzzy match, not this
    dismissed-verdict fuzzy match."""
    dismissed = _finding("nit", file="app.py", line=10, severity="Low", category="lint")
    dismissed_fp = fingerprint(dismissed)
    thread = _thread(fp=dismissed_fp, severity="Low", category="lint", is_resolved=True)
    new_finding = _finding("similar nit far away", file="app.py", line=20, severity="Low", category="lint")

    result = classify(
        new_finding, verdicts={dismissed_fp: "dismissed"}, all_threads=[thread]
    )
    assert result.kind == "new"


def test_classify_fuzzy_dismissed_match_finds_thread_via_prior_fingerprint() -> None:
    """#720 regression: a fuzzy "update" match PATCHes a thread's comment in
    place, replacing its metadata marker's fingerprint with the reworded
    finding's exact one while the verdict recorded by a since-dismissed
    reply is still keyed against the *old* fingerprint. Without
    `prior_fingerprints`, `_find_thread_by_fingerprint(all_threads, old_fp)`
    would come back `None` (the thread's own `.fingerprint` is now `new_fp`),
    `d_severity` would be unrecoverable, and the dismissed finding would
    repost as "new" -- exactly the failure this thread's own comment history
    is supposed to prevent."""
    old_fp = "code-reviewer|app.py|10|deadbeef0000"
    thread = _thread(
        path="app.py",
        line=11,
        severity="Low",
        category="lint",
        fp="new-fingerprint-after-reword",
        prior_fingerprints=frozenset({old_fp}),
        is_resolved=True,
    )
    reworded = _finding("similar nit, reworded", file="app.py", line=11, severity="Low", category="lint")

    result = classify(reworded, verdicts={old_fp: "dismissed"}, all_threads=[thread])
    assert result.kind == "suppressed"


def test_classify_exact_fixed_match_is_recurred_with_thread() -> None:
    f = _finding(file="app.py", line=10, severity="High")
    fp = fingerprint(f)
    thread = _thread(fp=fp, is_resolved=True, severity="High")
    result = classify(f, verdicts={fp: "fixed"}, all_threads=[thread])
    assert result.kind == "recurred"
    assert result.thread is thread


def test_classify_exact_fixed_match_body_level_recurred_without_thread() -> None:
    f = _finding(file="app.py", line=10)
    fp = fingerprint(f)
    result = classify(f, verdicts={fp: "fixed"}, all_threads=[])
    assert result.kind == "recurred"
    assert result.thread is None


def test_classify_fuzzy_only_fixed_match_is_not_recurred() -> None:
    """Row: 'matches a fixed thread, fuzzy-only (not exact) match' -> falls
    through as genuinely new (or update/escalate if it also fuzzy-matches an
    *open* thread) -- the recurrence check is deliberately exact-only."""
    fixed = _finding("original", file="app.py", line=10)
    fixed_fp = fingerprint(fixed)
    reworded = _finding("reworded text", file="app.py", line=11)

    result = classify(reworded, verdicts={fixed_fp: "fixed"}, all_threads=[])
    assert result.kind == "new"


def test_classify_open_thread_same_severity_is_update() -> None:
    thread = _thread(path="app.py", line=10, severity="Medium", category="other")
    f = _finding(file="app.py", line=11, severity="Medium", category="other")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "update"
    assert result.thread is thread


def test_classify_open_thread_lower_severity_is_update() -> None:
    thread = _thread(path="app.py", line=10, severity="High", category="other")
    f = _finding(file="app.py", line=11, severity="Low", category="other")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "update"


def test_classify_open_thread_escalated_severity_is_escalate() -> None:
    thread = _thread(path="app.py", line=10, severity="Low", category="other")
    f = _finding(file="app.py", line=11, severity="Critical", category="other")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "escalate"
    assert result.thread is thread


def test_classify_open_thread_multiple_candidates_prefers_closest_line() -> None:
    """Two open threads both fall within PROXIMITY_LINES of the new finding
    -- the closer one (by line distance) must win, not the first one in
    `all_threads` order."""
    far_thread = _thread(thread_id="far", path="app.py", line=8, comment_id=1, severity="Medium", category="other")
    close_thread = _thread(thread_id="close", path="app.py", line=10, comment_id=2, severity="Medium", category="other")
    f = _finding(file="app.py", line=11, severity="Medium", category="other")
    # far_thread listed first so a naive "first match wins" implementation
    # would pick the wrong one.
    result = classify(f, verdicts={}, all_threads=[far_thread, close_thread])
    assert result.thread is close_thread


def test_classify_open_thread_equidistant_candidates_prefers_oldest_comment() -> None:
    """Two open threads tie on line distance -- the older comment (lower
    comment_id) wins, per _fuzzy_open_match's documented tie-break."""
    newer_thread = _thread(thread_id="newer", path="app.py", line=9, comment_id=99, severity="Medium", category="other")
    older_thread = _thread(thread_id="older", path="app.py", line=13, comment_id=1, severity="Medium", category="other")
    f = _finding(file="app.py", line=11, severity="Medium", category="other")
    # Both threads are exactly 2 lines away from line 11.
    result = classify(f, verdicts={}, all_threads=[newer_thread, older_thread])
    assert result.thread is older_thread


def test_classify_outdated_thread_match_reclassifies_as_new() -> None:
    thread = _thread(path="app.py", line=10, severity="Low", is_outdated=True)
    f = _finding(file="app.py", line=11, severity="Critical")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"
    assert result.thread is None


def test_classify_incompatible_category_does_not_match_open_thread() -> None:
    thread = _thread(path="app.py", line=10, severity="Medium", category="secret")
    f = _finding(file="app.py", line=11, severity="Critical", category="injection")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"


def test_classify_legacy_thread_with_unrecoverable_category_matches_any_category() -> None:
    """A legacy thread posted before the per-comment metadata marker existed
    has category=None (never rendered anywhere, permanently unrecoverable --
    see PriorThread's docstring). categories_compatible treats None as a
    wildcard, so this thread must still fuzzy-match a new finding regardless
    of that finding's own category -- unlike a *known*, different category,
    which correctly blocks the match (see the incompatible-category test
    above)."""
    thread = _thread(path="app.py", line=10, severity="Medium", category=None)
    f = _finding(file="app.py", line=11, severity="Medium", category="secret")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "update"
    assert result.thread is thread


def test_classify_beyond_proximity_window_does_not_match() -> None:
    thread = _thread(path="app.py", line=10, severity="Medium")
    f = _finding(file="app.py", line=20, severity="Medium")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"


# ---------------------------------------------------------------------------
# Classified -- invariant enforcement
# ---------------------------------------------------------------------------


def test_classified_update_without_thread_raises() -> None:
    """"update"/"escalate" exist to PATCH/reply on a specific prior thread --
    constructing one without a thread to act on is a caller bug, not a valid
    state, and must fail loudly rather than silently propagate a None where
    every real call site treats `thread` as guaranteed present."""
    with pytest.raises(ValueError, match="update"):
        Classified(_finding(), "update", None)


def test_classified_escalate_without_thread_raises() -> None:
    with pytest.raises(ValueError, match="escalate"):
        Classified(_finding(), "escalate", None)


def test_classified_new_with_thread_raises() -> None:
    """"new" means genuinely new information with no existing thread to
    associate it with -- a non-None thread here would be silently ignored by
    every real consumer (post_findings only reads `.thread` for
    update/escalate/recurred), masking a caller bug."""
    thread = _thread()
    with pytest.raises(ValueError, match="new"):
        Classified(_finding(), "new", thread)


def test_classified_suppressed_with_thread_raises() -> None:
    thread = _thread()
    with pytest.raises(ValueError, match="suppressed"):
        Classified(_finding(), "suppressed", thread)


def test_classified_recurred_allows_either_thread_or_none() -> None:
    """The one classification exempt from the invariant: a recurrence can be
    body-level (no thread, nothing to reopen) or thread-anchored (the
    original inline comment still exists)."""
    Classified(_finding(), "recurred", None)
    Classified(_finding(), "recurred", _thread())


def test_dedupe_thread_claims_keeps_highest_severity_demotes_rest_to_new() -> None:
    """Two distinct findings within PROXIMITY_LINES of the same open thread
    both fuzzy-match it independently (classify() has no cross-finding
    visibility). Applying both side effects would PATCH the same comment
    twice, silently dropping one finding. dedupe_thread_claims keeps the
    higher-severity claim and sends the other back through as "new" so it
    gets its own slot instead of disappearing."""
    thread = _thread(thread_id="shared", line=100, severity="Low")
    low = _finding("nit", line=99, severity="Low")
    high = _finding("real bug", line=101, severity="Critical")
    classified = [
        Classified(low, "update", thread),
        Classified(high, "escalate", thread),
    ]
    result = dedupe_thread_claims(classified)
    kept = [c for c in result if c.thread is not None]
    demoted = [c for c in result if c.thread is None]
    assert len(kept) == 1
    assert kept[0].finding is high
    assert kept[0].kind == "escalate"
    assert len(demoted) == 1
    assert demoted[0].finding is low
    assert demoted[0].kind == "new"


def test_dedupe_thread_claims_tie_in_severity_keeps_earlier_claim() -> None:
    """Docstring contract: "ties broken by keeping the earlier one." Two
    same-severity claims on the same thread must not both flip to "new" (nor
    both survive, which would double-PATCH) -- the first (lower index) wins
    and the second is demoted."""
    thread = _thread(thread_id="shared", line=100, severity="Low")
    first = _finding("first claim", line=99, severity="Critical")
    second = _finding("second claim", line=101, severity="Critical")
    classified = [
        Classified(first, "escalate", thread),
        Classified(second, "escalate", thread),
    ]
    result = dedupe_thread_claims(classified)
    kept = [c for c in result if c.thread is not None]
    demoted = [c for c in result if c.thread is None]
    assert len(kept) == 1
    assert kept[0].finding is first
    assert len(demoted) == 1
    assert demoted[0].finding is second
    assert demoted[0].kind == "new"


def test_dedupe_thread_claims_is_a_noop_when_no_collision() -> None:
    t1 = _thread(thread_id="t1", line=10)
    t2 = _thread(thread_id="t2", line=50)
    f1 = _finding("a", line=10)
    f2 = _finding("b", line=50)
    classified = [Classified(f1, "update", t1), Classified(f2, "update", t2)]
    result = dedupe_thread_claims(classified)
    assert result == classified


def test_classify_resolved_non_fixed_thread_is_not_a_fuzzy_open_match() -> None:
    """A resolved thread with no verdict at all (e.g. resolved by
    resolve_stale's routine housekeeping sweep, not a human verdict) must not
    be treated as still-open for the update/escalate check."""
    thread = _thread(path="app.py", line=10, severity="Medium", is_resolved=True)
    f = _finding(file="app.py", line=10, severity="Medium")
    result = classify(f, verdicts={}, all_threads=[thread])
    assert result.kind == "new"


# ---------------------------------------------------------------------------
# parse_prior_thread — meta marker fast path + legacy fallback
# ---------------------------------------------------------------------------


def _thread_node(
    *,
    body: str,
    author: str = "github-actions",
    thread_id: str = "th1",
    comment_id: int = 100,
    review_id: int = 10,
    is_resolved: bool = False,
    is_outdated: bool = False,
    path: str = "app.py",
    line: int | None = 10,
    original_line: int | None = None,
    start_line: int | None = None,
) -> dict:
    return {
        "id": thread_id,
        "isResolved": is_resolved,
        "isOutdated": is_outdated,
        "path": path,
        "line": line,
        "originalLine": original_line,
        "startLine": start_line,
        "comments": {
            "nodes": [
                {
                    "databaseId": comment_id,
                    "body": body,
                    "author": {"login": author},
                    "pullRequestReview": {"databaseId": review_id},
                }
            ]
        },
    }


def test_parse_prior_thread_reads_meta_marker() -> None:
    f = _finding(file="app.py", line=10, severity="High", category="secret")
    fp = fingerprint(f)
    marker = build_inline_meta_marker(fingerprint=fp, category="secret", severity="High")
    body = f"🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->\n{marker}"
    node = _thread_node(body=body)

    thread = parse_prior_thread(node, bot_login="github-actions")
    assert thread is not None
    assert thread.fingerprint == fp
    assert thread.category == "secret"
    assert thread.severity == "High"
    assert thread.path == "app.py"
    assert thread.line == 10


def test_parse_prior_thread_not_owned_by_us_returns_none() -> None:
    node = _thread_node(body="some comment", author="someone-else")
    assert parse_prior_thread(node, bot_login="github-actions") is None


def test_parse_prior_thread_non_int_comment_database_id_returns_none() -> None:
    """Defensive type-narrowing: a malformed/unexpected GraphQL response
    shape (databaseId missing or not an int) must degrade to "unrecognized
    thread" rather than propagate a wrong-typed comment_id downstream."""
    node = _thread_node(body="🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->")
    node["comments"]["nodes"][0]["databaseId"] = None
    assert parse_prior_thread(node, bot_login="github-actions[bot]") is None


def test_parse_prior_thread_non_str_thread_id_returns_none() -> None:
    """Same defensive guard for the thread-level `id` field."""
    node = _thread_node(body="🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->")
    node["id"] = 12345
    assert parse_prior_thread(node, bot_login="github-actions[bot]") is None


def test_parse_prior_thread_legacy_falls_back_to_header_severity() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body)

    thread = parse_prior_thread(node, bot_login="github-actions")
    assert thread is not None
    assert thread.severity == "High"
    assert thread.category is None
    assert thread.fingerprint is None


def test_parse_prior_thread_legacy_recovers_fingerprint_via_id_map_bodies() -> None:
    f = _finding("leaked key", file="app.py", line=10, source="code-reviewer", severity="High")
    fp = fingerprint(f)
    from ai_pr_review.vcs.marker import build_id_map_marker

    id_map_body = "## AI Review Findings\n" + build_id_map_marker({fp: 3})
    body = "🔴 **[High]** **[F3]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body)

    thread = parse_prior_thread(
        node, bot_login="github-actions", id_map_bodies=[id_map_body]
    )
    assert thread is not None
    assert thread.fingerprint == fp
    assert thread.finding_id == 3


def test_parse_prior_thread_no_comments_returns_none() -> None:
    node = {
        "id": "th1", "isResolved": False, "isOutdated": False,
        "path": "app.py", "line": 10, "originalLine": None, "startLine": None,
        "comments": {"nodes": []},
    }
    assert parse_prior_thread(node, bot_login="github-actions") is None


def test_parse_prior_thread_falls_back_to_original_line_when_line_absent() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, line=None, original_line=7)
    thread = parse_prior_thread(node, bot_login="github-actions")
    assert thread is not None
    assert thread.line == 7


def test_parse_prior_thread_recognizes_graphql_style_login_when_normalized() -> None:
    """GitHub's GraphQL API reports the bot's login without the REST-style
    "[bot]" suffix (verified live against a real thread). GitHubProvider
    passes graphql_bot_login(self.config.bot_login) (issue #717's fix) --
    which strips that suffix -- to parse_prior_thread for exactly this
    reason; this test locks that in with the exact normalized value the
    call site produces."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, author="github-actions")
    assert parse_prior_thread(node, bot_login="github-actions") is not None


def test_parse_prior_thread_rest_style_bot_login_rejects_graphql_login() -> None:
    """Documents the exact bug fixed by issue #717: comparing a
    GraphQL-sourced "github-actions" author against the raw, un-normalized
    REST-style "github-actions[bot]" constant makes every real thread look
    unowned. This is why the call site normalizes via graphql_bot_login()
    before comparing, rather than passing the raw constant."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, author="github-actions")
    assert parse_prior_thread(node, bot_login="github-actions[bot]") is None


def test_parse_prior_thread_normalized_login_still_rejects_different_bot() -> None:
    """Defense in depth is preserved by normalization, not lost: a
    different bot's GraphQL login (also suffix-less) must still fail to
    match our normalized bot_login."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    node = _thread_node(body=body, author="other-automation-bot")
    assert parse_prior_thread(node, bot_login="github-actions") is None


# ---------------------------------------------------------------------------
# parse_gitlab_prior_thread (#710)
# ---------------------------------------------------------------------------

_GL_HEAD = "headsha1234"
_GL_BASE = "basesha5678"


def _gl_disc(
    *,
    body: str,
    author: str = "gl-bot",
    disc_id: str = "d1",
    note_id: int = 100,
    note_type: str | None = "DiffNote",
    resolved: bool = False,
    path: str | None = "app.py",
    line: int | None = 10,
    head_sha: str | None = _GL_HEAD,
    base_sha: str | None = _GL_BASE,
    position_type: str | None = "text",
) -> dict:
    position: dict | None = None
    if path is not None:
        position = {
            "position_type": position_type,
            "new_path": path,
            "old_path": path,
            "new_line": line,
            "old_line": None,
            "base_sha": base_sha,
            "start_sha": base_sha,
            "head_sha": head_sha,
        }
    note: dict = {
        "id": note_id,
        "type": note_type,
        "body": body,
        "author": {"username": author},
        "resolvable": True,
        "resolved": resolved,
    }
    if position is not None:
        note["position"] = position
    return {"id": disc_id, "notes": [note]}


def test_parse_gitlab_prior_thread_reads_meta_marker() -> None:
    f = _finding(file="app.py", line=10, severity="High", category="secret")
    fp = fingerprint(f)
    marker = build_inline_meta_marker(fingerprint=fp, category="secret", severity="High")
    body = f"🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->\n{marker}"
    disc = _gl_disc(body=body)

    thread = parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    )
    assert thread is not None
    assert thread.fingerprint == fp
    assert thread.category == "secret"
    assert thread.severity == "High"
    assert thread.path == "app.py"
    assert thread.line == 10
    assert thread.is_outdated is False


def test_parse_gitlab_prior_thread_not_owned_by_us_returns_none() -> None:
    disc = _gl_disc(body="some comment\n<!-- ai-pr-review-inline -->", author="someone-else")
    assert parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    ) is None


def test_parse_gitlab_prior_thread_no_notes_returns_none() -> None:
    disc = {"id": "d1", "notes": []}
    assert parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    ) is None


def test_parse_gitlab_prior_thread_non_diffnote_returns_none() -> None:
    """A body-only or file-level note has no line to fuzzy-match against."""
    disc = _gl_disc(
        body="🔴 **[High]** [x] y\n<!-- ai-pr-review-inline -->", note_type="DiscussionNote",
    )
    assert parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    ) is None


def test_parse_gitlab_prior_thread_non_text_position_returns_none() -> None:
    disc = _gl_disc(
        body="🔴 **[High]** [x] y\n<!-- ai-pr-review-inline -->", position_type="file",
    )
    assert parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    ) is None


def test_parse_gitlab_prior_thread_missing_position_returns_none() -> None:
    disc = _gl_disc(body="🔴 **[High]** [x] y\n<!-- ai-pr-review-inline -->", path=None)
    assert parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    ) is None


def test_parse_gitlab_prior_thread_non_int_note_id_returns_none() -> None:
    disc = _gl_disc(body="🔴 **[High]** [x] y\n<!-- ai-pr-review-inline -->")
    disc["notes"][0]["id"] = "not-an-int"
    assert parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    ) is None


def test_parse_gitlab_prior_thread_legacy_falls_back_to_header_severity() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    disc = _gl_disc(body=body)

    thread = parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    )
    assert thread is not None
    assert thread.severity == "High"
    assert thread.category is None
    assert thread.fingerprint is None


def test_parse_gitlab_prior_thread_resolved_flag_propagates() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    disc = _gl_disc(body=body, resolved=True)
    thread = parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    )
    assert thread is not None
    assert thread.is_resolved is True


def test_parse_gitlab_prior_thread_tier1_same_head_and_base_is_not_outdated() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    disc = _gl_disc(body=body, head_sha=_GL_HEAD, base_sha=_GL_BASE)
    thread = parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),  # empty on purpose: Tier 1 doesn't consult it
    )
    assert thread is not None
    assert thread.is_outdated is False


def test_parse_gitlab_prior_thread_tier2_head_moved_but_still_eligible() -> None:
    """Head advanced since posting, but this run's diff still has an added
    line at the exact same coordinate -- trust the anchor."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    disc = _gl_disc(body=body, path="app.py", line=10, head_sha="oldhead", base_sha=_GL_BASE)
    thread = parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new={("app.py", 10)},
    )
    assert thread is not None
    assert thread.is_outdated is False


def test_parse_gitlab_prior_thread_tier2_head_moved_and_no_longer_eligible_is_outdated() -> None:
    """Head advanced and the old anchor no longer lands on an added line --
    the code moved or was deleted; don't trust the coordinate."""
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    disc = _gl_disc(body=body, path="app.py", line=10, head_sha="oldhead", base_sha=_GL_BASE)
    thread = parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new={("app.py", 99)},
    )
    assert thread is not None
    assert thread.is_outdated is True


def test_parse_gitlab_prior_thread_base_sha_mismatch_alone_triggers_tier2() -> None:
    body = "🔴 **[High]** [code-reviewer] leaked key\n<!-- ai-pr-review-inline -->"
    disc = _gl_disc(body=body, path="app.py", line=10, head_sha=_GL_HEAD, base_sha="oldbase")
    thread = parse_gitlab_prior_thread(
        disc, bot_username="gl-bot", current_head_sha=_GL_HEAD,
        current_base_sha=_GL_BASE, eligible_new=set(),
    )
    assert thread is not None
    assert thread.is_outdated is True


# ---------------------------------------------------------------------------
# decide_action
# ---------------------------------------------------------------------------


def test_decide_action_no_canonical_posts() -> None:
    action = decide_action(None, event="COMMENT", classified=[], any_new_inline_eligible=False)
    assert action == "post"


def test_decide_action_dismissed_canonical_posts() -> None:
    canonical = CanonicalReview(review_id=1, state="DISMISSED", body=_FOOTER_BODY)
    action = decide_action(
        canonical, event="COMMENT", classified=[], any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_event_mismatch_posts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    action = decide_action(
        canonical, event="APPROVE", classified=[], any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_event_matches_state_puts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=[], any_new_inline_eligible=False
    )
    assert action == "put"


def test_decide_action_missing_footer_posts() -> None:
    """Guards against PUTing a findings body over a human-facing message
    (e.g. GitHubProvider.submit_approval's marker-less APPROVE)."""
    canonical = CanonicalReview(
        review_id=1, state="APPROVED", body="Auto-approved: all findings resolved."
    )
    action = decide_action(
        canonical, event="APPROVE", classified=[], any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_new_inline_eligible_posts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(_finding(severity="Low"), verdicts={}, all_threads=[])]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=True
    )
    assert action == "post"


def test_decide_action_new_high_severity_body_level_still_posts() -> None:
    """A High/Critical finding that can't get an inline anchor (out-of-diff,
    over max_inline) must still surface as a fresh review -- new information
    has to be visible, not silently PUT into the body."""
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(_finding(severity="High"), verdicts={}, all_threads=[])]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=False
    )
    assert action == "post"


def test_decide_action_new_high_severity_known_fingerprint_puts() -> None:
    """Issue #719: a persistent body-level High/Critical finding whose exact
    fingerprint is already visible in the canonical's own prior body (a
    known fingerprint) is not genuinely new information to a human -- the
    PUT still renders it in the body every time, so it should not force a
    fresh review on every single rerun."""
    f = _finding(severity="High")
    fp = fingerprint(f)
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(f, verdicts={}, all_threads=[])]
    action = decide_action(
        canonical,
        event="REQUEST_CHANGES",
        classified=classified,
        any_new_inline_eligible=False,
        known_fingerprints=frozenset({fp}),
    )
    assert action == "put"


def test_decide_action_new_high_severity_unknown_fingerprint_still_posts() -> None:
    """A different High/Critical finding (not in known_fingerprints) must
    still force post even when the canonical carries some other known
    fingerprint -- the exemption is per-fingerprint, not a blanket pass."""
    f = _finding(severity="High")
    other_fp = fingerprint(_finding("a different finding entirely", severity="Low"))
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(f, verdicts={}, all_threads=[])]
    action = decide_action(
        canonical,
        event="REQUEST_CHANGES",
        classified=classified,
        any_new_inline_eligible=False,
        known_fingerprints=frozenset({other_fp}),
    )
    assert action == "post"


def test_decide_action_new_low_severity_body_level_puts() -> None:
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [classify(_finding(severity="Low"), verdicts={}, all_threads=[])]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=False
    )
    assert action == "put"


def test_decide_action_only_update_and_escalate_puts() -> None:
    thread = _thread(path="app.py", line=10, severity="Low")
    canonical = CanonicalReview(review_id=1, state="CHANGES_REQUESTED", body=_FOOTER_BODY)
    classified = [
        classify(_finding(file="app.py", line=11, severity="Critical"), verdicts={}, all_threads=[thread])
    ]
    action = decide_action(
        canonical, event="REQUEST_CHANGES", classified=classified, any_new_inline_eligible=False
    )
    assert action == "put"
