"""Integration tests for canonical-review reuse wired into
`GitHubProvider.post_findings` -- the read side that actually stops the
PR-comment clutter the write side (verdict-marker recording, PR #714) set up
for. Uses the `_make_provider`/`_Recorder` MockTransport pattern from
`test_github_findings.py`.
"""

from __future__ import annotations

import json as _json
from collections.abc import Callable
from dataclasses import dataclass, field

import httpx

from ai_pr_review.findings.models import Finding
from ai_pr_review.vcs._finding_ids import fingerprint
from ai_pr_review.vcs.github import GitHubConfig, GitHubProvider, _build_inline_comment_body
from ai_pr_review.vcs.http import RecordingClient, RetryPolicy, TapeRecorder
from ai_pr_review.vcs.marker import build_verdicts_marker
from ai_pr_review.vcs.protocol import DiffContext

_VALID_SHA = "abc1234def5678abc1234def5678abc1234def56"
_NEW_SHA = "def5678abc1234def5678abc1234def5678abcd"

_DIFF = """diff --git a/app.py b/app.py
--- a/app.py
+++ b/app.py
@@ -1,3 +1,6 @@
 context_line_1
 context_line_2
 context_line_3
+added_line_4
+added_line_5
+added_line_6
"""


@dataclass
class _Recorder:
    calls: list[tuple[str, str, dict | None]] = field(default_factory=list)


def _make_provider(
    handler: Callable[[httpx.Request], httpx.Response],
) -> tuple[GitHubProvider, _Recorder]:
    rec = _Recorder()

    def _wrap(request: httpx.Request) -> httpx.Response:
        body = None
        if request.content:
            try:
                body = _json.loads(request.content)
            except Exception:
                body = None
        rec.calls.append((request.method, str(request.url), body))
        return handler(request)

    transport = httpx.MockTransport(_wrap)
    http = httpx.Client(transport=transport, base_url="https://api.github.com")
    client = RecordingClient(
        http=http,
        recorder=TapeRecorder(record_dir=None),
        retry_policy=RetryPolicy(
            attempts=2, base_backoff=0, jitter=False, sleep=lambda _s: None
        ),
    )
    config = GitHubConfig(owner="o", repo="r", pr_number=1, token="t")
    return GitHubProvider(config=config, client=client), rec


def _finding(
    text: str = "issue",
    *,
    source: str = "code-reviewer",
    file: str = "app.py",
    line: int = 5,
    severity: str = "Medium",
    category: str = "other",
) -> Finding:
    return Finding(
        severity=severity, confidence=80, finding=text, source=source,
        file=file, line=line, category=category,
    )


def _footer_body(inner: str = "some body") -> str:
    return (
        f"## AI Review Findings\n\n{inner}\n\n---\n"
        "*AI Review — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
    )


def _thread_node(
    *,
    thread_id: str,
    comment_id: int,
    review_id: int,
    body: str,
    is_resolved: bool = False,
    is_outdated: bool = False,
    path: str = "app.py",
    line: int = 5,
    start_line: int | None = None,
) -> dict:
    return {
        "id": thread_id,
        "isResolved": is_resolved,
        "isOutdated": is_outdated,
        "path": path,
        "line": line,
        "originalLine": line,
        "startLine": start_line,
        "comments": {
            "nodes": [
                {
                    "databaseId": comment_id,
                    "body": body,
                    # GitHub's GraphQL API reports the bot's login without
                    # the REST-style "[bot]" suffix (verified live) --
                    # deliberately not "github-actions[bot]" here, so this
                    # fixture would catch a regression to comparing against
                    # that REST-style constant in the ownership gate.
                    "author": {"login": "github-actions"},
                    "pullRequestReview": {"databaseId": review_id},
                }
            ]
        },
    }


def _threads_response(nodes: list[dict]) -> httpx.Response:
    return httpx.Response(
        200,
        json={
            "data": {
                "repository": {
                    "pullRequest": {
                        "reviewThreads": {
                            "pageInfo": {"hasNextPage": False, "endCursor": None},
                            "nodes": nodes,
                        }
                    }
                }
            }
        },
    )


def _is_graphql(req: httpx.Request, body: dict | None, needle: str) -> bool:
    return (
        req.method == "POST"
        and str(req.url).endswith("/graphql")
        and bool(body)
        and needle in (body.get("query") or "")
    )


# ---------------------------------------------------------------------------
# Quiet rerun: nothing new -> PUT only, zero POST /reviews
# ---------------------------------------------------------------------------


def test_quiet_rerun_puts_canonical_body_posts_nothing_new() -> None:
    existing_finding = _finding("existing issue", severity="Medium")
    existing_comment_body = _build_inline_comment_body(existing_finding)
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews") or (
            req.method == "GET" and "/reviews?" in url
        ):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=5,
                )]
            )
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    # Identical finding re-detected this run -> classifies "update" (same
    # severity), no side effect that changes anything material, no new
    # findings at all.
    result = prov.post_findings(
        [existing_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is True
    assert result.review_id == 10
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    posts = [c for c in rec.calls if c[0] == "POST" and "/reviews" in c[1] and not c[1].endswith("/graphql")]
    assert len(puts) == 1
    assert posts == []


def test_new_medium_finding_over_max_inline_puts_not_posts() -> None:
    """Issue #719: any_new_inline_eligible must reflect which findings
    actually landed an inline comment, not raw eligibility. A Medium
    finding that's in-diff (so is_inline_eligible would say True) but gets
    bumped to the body by max_inline=0 must not force a fresh POST -- it
    never got a new inline comment at all, and it's below the High/Critical
    body-level exemption's threshold too."""
    canonical_body = _footer_body()
    new_finding = _finding("in-diff but bumped to body", severity="Medium")

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            raise AssertionError(
                "must PUT the canonical -- the finding never actually got "
                "an inline comment (max_inline=0 bumped it to the body) and "
                "is below the High/Critical body-level exemption"
            )
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [new_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
        max_inline=0,
    )

    assert result.ok
    assert result.reused_review is True
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert len(puts) == 1


# ---------------------------------------------------------------------------
# Genuinely new finding -> exactly one POST, old CR left standing (has
# unresolved threads) or dismissed (none left)
# ---------------------------------------------------------------------------


def test_new_finding_posts_fresh_review_and_dismisses_cleared_canonical() -> None:
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            # No threads at all this cycle: the canonical review has nothing
            # unresolved left owned by us.
            return _threads_response([])
        if req.method == "POST" and url.endswith("/reviews/10/dismissals"):
            return httpx.Response(200, json={"id": 10, "state": "DISMISSED"})
        if req.method == "PUT" and url.endswith("/reviews/10/dismissals"):
            return httpx.Response(200, json={"id": 10, "state": "DISMISSED"})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [_finding("brand new issue", severity="High")],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is False
    assert result.review_id == 20
    dismissals = [c for c in rec.calls if "/reviews/10/dismissals" in c[1]]
    assert len(dismissals) == 1
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1


def test_persistent_out_of_diff_critical_finding_puts_on_second_run() -> None:
    """Issue #719: a body-level Critical finding with no diff anchor (so it
    can never become an inline thread to fuzzy-match against) forces a
    fresh POST the first time it's seen -- but once its exact fingerprint
    is visible in the canonical's own body (via the id-map marker), an
    unchanged rerun must PUT instead of repeating the dismiss+POST cycle
    forever."""
    persistent = _finding(
        "structural issue with no diff anchor",
        severity="Critical",
        file="unrelated_file.py",
        line=1,
    )

    # Cycle 1: no prior review at all -> canonical is None -> must POST.
    def handler_cycle1(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(200, json=[])
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 50, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov1, rec1 = _make_provider(handler_cycle1)
    result1 = prov1.post_findings(
        [persistent],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )
    assert result1.reused_review is False
    assert result1.review_id == 50
    posts_cycle1 = [c for c in rec1.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts_cycle1) == 1
    posted_body = posts_cycle1[0][2]["body"]

    # Cycle 2: same exact finding again. The canonical review now carries
    # this fingerprint's id-map entry from cycle 1's posted body.
    def handler_cycle2(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 50, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": posted_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/50"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": posted_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/50"):
            return httpx.Response(200, json={"id": 50})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            raise AssertionError(
                "must PUT the canonical, not POST a fresh review, for an "
                "unchanged persistent finding already visible in its body"
            )
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov2, rec2 = _make_provider(handler_cycle2)
    result2 = prov2.post_findings(
        [persistent],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )
    assert result2.ok
    assert result2.reused_review is True
    puts = [c for c in rec2.calls if c[0] == "PUT" and c[1].endswith("/reviews/50")]
    assert len(puts) == 1


def test_new_finding_does_not_dismiss_canonical_with_unresolved_owned_threads() -> None:
    """If the canonical CR review still has an unresolved thread we own, it
    must never be dismissed -- that's the exact hole a prior draft of this
    design had: dismissing it would let the slash-command PR-wide
    auto-approve path see zero unresolved threads on any CR review and
    approve a PR with a High finding still open."""
    existing_finding = _finding("still open issue", severity="High", line=4)
    existing_comment_body = _build_inline_comment_body(existing_finding)
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=4, is_resolved=False,
                )]
            )
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError(
                "must never dismiss a CR review with an unresolved owned thread"
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [existing_finding, _finding("brand new critical issue", severity="Critical", line=6)],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.review_id == 20


# ---------------------------------------------------------------------------
# Escalation: PATCH comment + reply, no new review
# ---------------------------------------------------------------------------


def test_escalated_finding_patches_and_replies_no_new_review() -> None:
    old_finding = _finding("weak validation", severity="Low", line=5, category="other")
    existing_comment_body = _build_inline_comment_body(old_finding)
    canonical_body = _footer_body()

    escalated_finding = _finding("weak validation", severity="Critical", line=5, category="other")

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=existing_comment_body, line=5,
                )]
            )
        if req.method == "PATCH" and url.endswith("/pulls/comments/1"):
            return httpx.Response(200, json={"id": 1})
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 2})
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [escalated_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.reused_review is True
    patches = [c for c in rec.calls if c[0] == "PATCH" and c[1].endswith("/pulls/comments/1")]
    replies = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/comments/1/replies")]
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(patches) == 1
    assert len(replies) == 1
    assert "Critical" in replies[0][2]["body"]
    assert posts == []


# ---------------------------------------------------------------------------
# Recurrence: fixed finding reappears -> reply + unresolve, verdict tombstone
# ---------------------------------------------------------------------------


def test_recurred_finding_replies_and_unresolves_thread() -> None:
    f = _finding("leaked key", severity="High", line=5, source="code-reviewer", category="secret")
    fp = fingerprint(f)
    resolved_comment_body = _build_inline_comment_body(f)
    canonical_body = _footer_body() + "\n" + build_verdicts_marker({fp: "fixed"})

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "unresolveReviewThread"):
            return httpx.Response(200, json={"data": {"unresolveReviewThread": {"thread": {"id": "th1", "isResolved": False}}}})
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=resolved_comment_body, line=5, is_resolved=True,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 2})
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    replies = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/comments/1/replies")]
    unresolves = [
        c for c in rec.calls
        if c[0] == "POST" and c[1].endswith("/graphql") and c[2]
        and "unresolveReviewThread" in (c[2].get("query") or "")
    ]
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert len(replies) == 1
    assert len(unresolves) == 1
    assert len(puts) == 1
    # The verdict must become "recurred", not stay "fixed" (which would
    # re-trigger this same reply/unresolve every subsequent run) and not be
    # silently deleted (which a union merge with an older body could then
    # resurrect).
    from ai_pr_review.vcs.marker import extract_verdicts
    assert extract_verdicts(puts[0][2]["body"])[fp] == "recurred"


def test_reopened_recurrence_thread_protects_canonical_from_dismissal() -> None:
    """A recurrence reopens th1 on canonical review 10 via unresolveReviewThread.
    The same run also has a brand-new Critical finding, which forces
    decide_action to "post". Without syncing the in-memory `all_threads`
    snapshot after the reopen succeeds, _has_unresolved_owned_threads would
    still see th1's pre-side-effect is_resolved=True and wrongly let review
    10 be dismissed with a thread this very run just reopened sitting on it
    -- invisible to the slash-command PR-wide auto-approve check, which only
    counts unresolved threads on reviews whose *current* state is
    CHANGES_REQUESTED."""
    recurred = _finding("leaked key", severity="High", line=5, source="code-reviewer", category="secret")
    fp = fingerprint(recurred)
    resolved_comment_body = _build_inline_comment_body(recurred)
    canonical_body = _footer_body() + "\n" + build_verdicts_marker({fp: "fixed"})
    new_finding = _finding("brand new critical issue", severity="Critical", line=30)

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "unresolveReviewThread"):
            return httpx.Response(200, json={"data": {"unresolveReviewThread": {"thread": {"id": "th1", "isResolved": False}}}})
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response(
                [_thread_node(
                    thread_id="th1", comment_id=1, review_id=10,
                    body=resolved_comment_body, line=5, is_resolved=True,
                )]
            )
        if req.method == "POST" and url.endswith("/pulls/1/comments/1/replies"):
            return httpx.Response(201, json={"id": 2})
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError(
                "must not dismiss review 10 -- th1 was just reopened on it "
                "this run and is therefore still unresolved"
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 20, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [recurred, new_finding],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.review_id == 20
    unresolves = [
        c for c in rec.calls if c[0] == "POST" and c[1].endswith("/graphql") and c[2]
        and "unresolveReviewThread" in (c[2].get("query") or "")
    ]
    assert len(unresolves) == 1


def test_canonical_reuse_false_always_posts_fresh_review() -> None:
    """AI_CANONICAL_REUSE=false (GitHubConfig.canonical_reuse=False) is the
    kill switch: even a run with zero findings against an existing
    CHANGES_REQUESTED canonical must behave exactly like every release
    before this feature -- a fresh POST, no PUT, no thread fetch, no
    dismissal."""
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            raise AssertionError(
                "canonical_reuse=False must not fetch review threads at all"
            )
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError("canonical_reuse=False must never dismiss anything")
        if req.method == "PUT" and url.endswith("/reviews/10"):
            raise AssertionError("canonical_reuse=False must never PUT the canonical")
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 30, "state": "APPROVED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    rec = _Recorder()

    def _wrap(request: httpx.Request) -> httpx.Response:
        import json as _j2
        b = None
        if request.content:
            try:
                b = _j2.loads(request.content)
            except Exception:
                b = None
        rec.calls.append((request.method, str(request.url), b))
        return handler(request)

    transport = httpx.MockTransport(_wrap)
    http = httpx.Client(transport=transport, base_url="https://api.github.com")
    client = RecordingClient(
        http=http, recorder=TapeRecorder(record_dir=None),
        retry_policy=RetryPolicy(attempts=2, base_backoff=0, jitter=False, sleep=lambda _s: None),
    )
    config = GitHubConfig(owner="o", repo="r", pr_number=1, token="t", canonical_reuse=False)
    prov = GitHubProvider(config=config, client=client)

    result = prov.post_findings(
        [], DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA), event="APPROVE",
    )

    assert result.ok
    assert result.review_id == 30
    assert result.reused_review is False
    posts = [c for c in rec.calls if c[0] == "POST" and c[1].endswith("/pulls/1/reviews")]
    assert len(posts) == 1


# ---------------------------------------------------------------------------
# Dismissed verdict: suppressed, nothing posted for it
# ---------------------------------------------------------------------------


def test_dismissed_finding_is_suppressed_not_reposted() -> None:
    f = _finding("style nit", severity="Low", line=5)
    fp = fingerprint(f)
    canonical_body = _footer_body() + "\n" + build_verdicts_marker({fp: "dismissed"})

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "CHANGES_REQUESTED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            return httpx.Response(200, json={"head": {"sha": _VALID_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"id": 10})
        if req.method == "POST" and "/pulls/1/comments" in url:
            raise AssertionError("a suppressed finding must never be (re)posted")
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [f],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.suppressed == 1


# ---------------------------------------------------------------------------
# Concurrency guard: PUT abandoned when canonical changed / head advanced
# ---------------------------------------------------------------------------


def test_put_falls_back_to_post_when_canonical_changed_concurrently() -> None:
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            # Concurrent write happened: state flipped to DISMISSED since selection.
            return httpx.Response(200, json={"state": "DISMISSED", "body": canonical_body})
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 30, "state": "CHANGES_REQUESTED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )
    assert result.ok


def test_head_sha_advanced_skips_canonical_write() -> None:
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "APPROVED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method == "GET" and url.endswith("/reviews/10"):
            return httpx.Response(200, json={"state": "APPROVED", "body": canonical_body})
        if req.method == "GET" and url.endswith("/pulls/1"):
            # A newer run has already advanced the PR's head.
            return httpx.Response(200, json={"head": {"sha": _NEW_SHA}})
        if req.method == "PUT" and url.endswith("/reviews/10"):
            raise AssertionError("must not PUT once the PR head has advanced past this diff")
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="APPROVE",
    )

    assert result.ok
    assert result.reused_review is True
    # skipped=True distinguishes "no write happened, a newer run owns the
    # canonical" from an actual PUT -- orchestrate.py must not advance the
    # SHA watermark to this run's now-stale diff.head_sha on this result.
    assert result.skipped is True
    puts = [c for c in rec.calls if c[0] == "PUT" and c[1].endswith("/reviews/10")]
    assert puts == []


# ---------------------------------------------------------------------------
# Fail-soft: GraphQL 4xx degrades to legacy "post everything" behavior
# ---------------------------------------------------------------------------


def test_graphql_failure_degrades_to_posting_everything_as_new() -> None:
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return httpx.Response(500, text="internal error")
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            return httpx.Response(201, json={"id": 40, "state": "CHANGES_REQUESTED"})
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            return httpx.Response(200, json={"id": 10, "state": "DISMISSED"})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [_finding("new issue", severity="High")],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.ok
    assert result.review_id == 40
    assert result.reused_review is False
    # A failed/incomplete thread fetch must never be treated as "zero
    # unresolved owned threads" -- that would let the canonical CR review be
    # dismissed based on a fetch that could easily be missing an open High
    # finding's thread, reopening the auto-approve hole this feature's own
    # dismiss gate exists to close.
    dismissals = [c for c in rec.calls if "/dismissals" in c[1]]
    assert dismissals == []


def test_dismiss_superseded_review_only_after_replacement_confirmed_posted() -> None:
    """Dismissing the superseded canonical review before confirming the
    replacement actually posted as REQUEST_CHANGES would, on a mid-run
    failure, leave the PR with no blocking review at all -- silently
    unblocking something that should still be blocked. The canonical must
    stay standing when the fresh post degrades."""
    canonical_body = _footer_body()

    def handler(req: httpx.Request) -> httpx.Response:
        import json as _j

        body = _j.loads(req.content) if req.content else None
        url = str(req.url)
        if req.method == "GET" and url.split("?")[0].endswith("/pulls/1/reviews"):
            return httpx.Response(
                200,
                json=[
                    {
                        "id": 10, "state": "CHANGES_REQUESTED",
                        "user": {"login": "github-actions[bot]"},
                        "body": canonical_body,
                    }
                ],
            )
        if _is_graphql(req, body, "reviewThreads"):
            return _threads_response([])
        if req.method in ("PUT", "POST") and "/dismissals" in url:
            raise AssertionError(
                "must never dismiss the canonical before the replacement "
                "review is confirmed to have posted as REQUEST_CHANGES"
            )
        if req.method == "POST" and url.endswith("/pulls/1/reviews"):
            # Both the initial POST and the COMMENT-retry fallback fail,
            # degrading _post_new_review all the way to a plain issue
            # comment (event becomes "COMMENT", degraded_to_comment=True).
            return httpx.Response(422, text="validation failed")
        if req.method == "POST" and url.endswith("/issues/1/comments"):
            return httpx.Response(201, json={"id": 99})
        return httpx.Response(404, text=f"unrouted: {req.method} {url}")

    prov, rec = _make_provider(handler)
    result = prov.post_findings(
        [_finding("brand new issue", severity="High")],
        DiffContext(diff_text=_DIFF, head_sha=_VALID_SHA),
        event="REQUEST_CHANGES",
    )

    assert result.degraded_to_comment is True
    assert result.event != "REQUEST_CHANGES"
