"""Canonical-review reuse — read side (GitHub only, see #710 for parity gap).

Pure classification logic for reducing PR-comment clutter across review
reruns: given the bot's prior reviews and review threads on a PR, decide
whether a newly-computed finding is genuinely new, a recurrence of something
previously marked `fixed`, an update to a still-open thread (same or higher
severity), or something a human has already dismissed forever. The actual
GitHub I/O (fetching reviews/threads, PATCHing comments, replying, PUTing
the canonical review's body) lives in `ai_pr_review.vcs.github`; this module
takes already-fetched data and returns decisions, so it can be tested
without any HTTP stubbing.

Design reference: the plan at the top of this PR's description and the
original design doc it implements (canonical-review-reuse). Two verdict
sources feed `classify()`:

- The **verdicts marker** (`ai_pr_review.vcs.marker.extract_verdicts`),
  written by `ai_pr_review.slash.dismiss._record_verdict` whenever a human
  runs `/ai-pr-review dismiss|false-positive|wont-fix|fixed`. Keyed by the
  *exact* `fingerprint()` (source|file|line|text-hash) of the finding the
  command was run against.
- The **per-comment metadata marker**
  (`ai_pr_review.vcs.marker.extract_inline_meta`), written by this PR onto
  every inline comment at post time, carrying that finding's own exact
  fingerprint plus its category and severity — the two pieces of
  information no other part of the rendered comment persists anywhere.
  Older threads (posted before this marker existed) fall back to
  `**[Sev]**` header re-parsing for severity and an id-map reverse lookup
  for fingerprint; their category is permanently unrecoverable (`None`,
  treated as a wildcard by `categories_compatible`).
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Literal

from ai_pr_review.findings.merge import _SEVERITY_ORDER, PROXIMITY_LINES, categories_compatible
from ai_pr_review.vcs._finding_ids import _ID_RE, fingerprint, fingerprint_for_finding_id
from ai_pr_review.vcs._stale import is_owned_by_us
from ai_pr_review.vcs.marker import extract_inline_meta, extract_verdicts

if TYPE_CHECKING:
    from ai_pr_review.findings.models import Finding
    from ai_pr_review.vcs.protocol import PostEvent

# The footer every rendered review body carries (github.py's _render_review_body).
# decide_action refuses to PUT over a canonical body that doesn't have it — most
# notably a human-facing message posted by GitHubProvider.submit_approval, which
# carries no footer at all (issue #590's "approve on clear" path).
_FOOTER_MARKER = "generated by [ai-pr-review]"

# GitHub review `state` -> the PostEvent that would have produced it. Used to
# decide whether reusing the canonical review as-is (a PUT) is even coherent
# for this run's outcome, or whether a state transition requires a fresh
# review object instead.
_EVENT_FOR_STATE: dict[str, str] = {
    "CHANGES_REQUESTED": "REQUEST_CHANGES",
    "APPROVED": "APPROVE",
    "COMMENTED": "COMMENT",
}

_HEADER_SEVERITY_RE = re.compile(r"\*\*\[(Critical|High|Medium|Low)\]\*\*")

# Plain str-keyed copy of merge._SEVERITY_ORDER (which is typed
# dict[Severity, int], a Literal-keyed dict mypy won't accept a bare `str`
# lookup against) -- same ranking, reused rather than redefined so the two
# never drift.
_SEVERITY_RANK: dict[str, int] = {str(k): v for k, v in _SEVERITY_ORDER.items()}


def _rank(severity: str) -> int:
    return _SEVERITY_RANK.get(severity, 99)


def _safe_review_id(review: Mapping[str, Any]) -> int:
    """Best-effort int coercion of a review dict's `id`, defaulting to 0 on
    anything that isn't already an int/float/str/bytes numeral -- mirrors
    `ai_pr_review.vcs.github._safe_int`'s tolerance so a single malformed
    entry from `list_bot_reviews()` degrades this module's ordering rather
    than raising and losing the whole selection/merge."""
    value = review.get("id")
    try:
        if isinstance(value, (int, float, str, bytes)):
            return int(value)
    except (ValueError, TypeError):
        pass
    return 0


@dataclass(frozen=True)
class CanonicalReview:
    """The bot review currently treated as canonical for this PR."""

    review_id: int
    state: str
    body: str


def select_canonical(reviews: Sequence[Mapping[str, Any]]) -> CanonicalReview | None:
    """Pick the canonical review: the highest-id bot review, any state.

    Identical rule to `ai_pr_review.slash.dismiss._record_verdict`'s
    `max(reviews, key=lambda r: r.get("id") or 0)` — both sides of the
    write/read split must agree on which review carries the markers, or a
    verdict written to one review is invisible to classification reading
    from another. `reviews` is expected in the shape
    `GitHubProvider.list_bot_reviews()` returns: `{"id": int, "state": str,
    "body": str, ...}` (extra keys ignored).
    """
    if not reviews:
        return None
    best = max(reviews, key=_safe_review_id)
    review_id = best.get("id")
    if not isinstance(review_id, int):
        return None
    return CanonicalReview(
        review_id=review_id,
        state=str(best.get("state") or ""),
        body=str(best.get("body") or ""),
    )


def merge_verdicts(reviews: Sequence[Mapping[str, Any]]) -> dict[str, str]:
    """Union the verdicts marker across every prior bot review body.

    Reviews are folded in ascending id order so a later review's entry for
    the same fingerprint overwrites an earlier one — this is what makes the
    `"recurred"` tombstone (see `ai_pr_review.vcs.marker`'s module comment)
    actually override a stale `"fixed"` entry sitting in an older body: a
    single-body read (just the canonical's own `extract_verdicts`) cannot
    guarantee that, since not every prior review is guaranteed to carry
    every verdict ever recorded (this is also why
    `ai_pr_review.slash.dismiss._record_verdict` seeds from this same
    union rather than from the canonical body alone).
    """
    ordered = sorted(reviews, key=_safe_review_id)
    result: dict[str, str] = {}
    for r in ordered:
        result.update(extract_verdicts(str(r.get("body") or "")))
    return result


def fingerprint_location(fp: str) -> tuple[str, int | None]:
    """Recover `(file, line)` from a `fingerprint()` string.

    Fingerprint shape is `source|file|line|hash`
    (`ai_pr_review.vcs._finding_ids.fingerprint`). `file` may itself contain
    `|`, so this peels the known-fixed-width outer fields (`source|` from
    the front, `|line|hash` from the back) rather than a naive `split("|")`.
    """
    try:
        _source, rest = fp.split("|", 1)
        file_part, line_part, _hash = rest.rsplit("|", 2)
    except ValueError:
        return "", None
    line = int(line_part) if line_part.isdigit() else None
    return file_part, line


@dataclass(frozen=True)
class PriorThread:
    """One prior review thread this bot owns, with enough metadata to
    classify a new finding against it.

    `severity`/`category`/`fingerprint` are `None` when unrecoverable
    (legacy thread with no metadata marker and, for category, no rendering
    of category anywhere ever) — callers must treat `None` as "unknown",
    never coerce it to a real value.
    """

    thread_id: str
    comment_id: int
    review_id: int | None
    path: str
    line: int | None
    start_line: int | None
    is_resolved: bool
    is_outdated: bool
    severity: str | None
    category: str | None
    fingerprint: str | None
    finding_id: int | None


def parse_prior_thread(
    node: Mapping[str, Any],
    *,
    bot_login: str | None,
    id_map_bodies: Sequence[str] = (),
) -> PriorThread | None:
    """Build a `PriorThread` from one `reviewThreads` GraphQL node.

    `node` is expected to carry, in addition to the fields
    `fetch_review_threads` already selected, the thread-level
    `path`/`line`/`originalLine`/`startLine`/`isOutdated` fields this PR
    adds to that query. Returns `None` when the thread has no comments, or
    its first comment isn't owned by us (`is_owned_by_us(..., kind="inline")`
    — the same ownership gate `resolve_stale` already applies elsewhere).

    Severity/category/fingerprint prefer the per-comment metadata marker.
    Legacy threads (posted before that marker existed) fall back to
    `**[Sev]**` header re-parsing for severity and, when the comment carries
    an `**[F<n>]**` token, an id-map reverse lookup via
    `id_map_bodies`/`fingerprint_for_finding_id` for fingerprint. Category
    has no legacy fallback — it was never rendered anywhere — and stays
    `None` (a wildcard to `categories_compatible`) for those threads.
    """
    nodes = ((node.get("comments") or {}).get("nodes")) or []
    if not nodes:
        return None
    first = nodes[0]
    body = str(first.get("body") or "")
    author = (first.get("author") or {}).get("login") or ""
    if not is_owned_by_us(body, author, bot_login, kind="inline"):
        return None

    comment_id = first.get("databaseId")
    if not isinstance(comment_id, int):
        return None
    review = first.get("pullRequestReview") or {}
    review_id_raw = review.get("databaseId")
    review_id = review_id_raw if isinstance(review_id_raw, int) else None

    meta = extract_inline_meta(body)
    fp = meta.fp if meta else None
    category = meta.cat if meta else None
    severity = meta.sev if meta else None

    if severity is None:
        first_line = body.splitlines()[0] if body else ""
        sev_match = _HEADER_SEVERITY_RE.search(first_line)
        severity = sev_match.group(1) if sev_match else None

    finding_id: int | None = None
    id_match = _ID_RE.search(body)
    if id_match:
        finding_id = int(id_match.group(1))
        if fp is None and id_map_bodies:
            fp = fingerprint_for_finding_id(id_map_bodies, finding_id)

    thread_id = node.get("id")
    if not isinstance(thread_id, str):
        return None
    line_raw = node.get("line")
    line: int | None
    if isinstance(line_raw, int):
        line = line_raw
    else:
        orig_raw = node.get("originalLine")
        line = orig_raw if isinstance(orig_raw, int) else None
    start_line_raw = node.get("startLine")
    start_line = start_line_raw if isinstance(start_line_raw, int) else None
    path_raw = node.get("path")
    path = path_raw if isinstance(path_raw, str) else ""

    return PriorThread(
        thread_id=thread_id,
        comment_id=comment_id,
        review_id=review_id,
        path=path,
        line=line,
        start_line=start_line,
        is_resolved=bool(node.get("isResolved")),
        is_outdated=bool(node.get("isOutdated")),
        severity=severity,
        category=category,
        fingerprint=fp,
        finding_id=finding_id,
    )


Kind = Literal["new", "suppressed", "recurred", "update", "escalate"]


@dataclass(frozen=True)
class Classified:
    finding: Finding
    kind: Kind
    thread: PriorThread | None


def _find_thread_by_fingerprint(
    threads: Sequence[PriorThread], fp: str
) -> PriorThread | None:
    for t in threads:
        if t.fingerprint == fp:
            return t
    return None


def _fuzzy_dismissed_match(
    finding: Finding,
    verdicts: Mapping[str, str],
    all_threads: Sequence[PriorThread],
) -> str | None:
    """Return a dismissed fingerprint fuzzy-matching `finding`'s location, or `None`.

    Applies the same `(file, ±PROXIMITY_LINES, compatible category)` key the
    original design's decision #5 specifies for *every* row of the decision
    table, including this one — suppressing on location alone (ignoring
    category/severity) would silently drop a new, unrelated, possibly more
    severe finding just because something else nearby was once dismissed,
    which is exactly the information-loss case the per-comment metadata
    marker exists to prevent.

    Only suppresses when the dismissed finding's severity is *recoverable
    and not lower* than `finding`'s. An unrecoverable severity (most
    commonly a body-level dismissed finding, which has no comment and
    therefore no metadata marker to recover it from) must never be treated
    as an escalation waiver — such a dismissal can only ever suppress an
    exact fingerprint match, not a fuzzy one.
    """
    if not finding.file or finding.line is None:
        return None
    for fp, verdict in verdicts.items():
        if verdict != "dismissed":
            continue
        d_file, d_line = fingerprint_location(fp)
        if d_file != finding.file or d_line is None:
            continue
        if abs(d_line - finding.line) > PROXIMITY_LINES:
            continue
        thread = _find_thread_by_fingerprint(all_threads, fp)
        d_category = thread.category if thread else None
        d_severity = thread.severity if thread else None
        if d_severity is None:
            continue
        if not categories_compatible(d_category, finding.category):
            continue
        if _rank(finding.severity) < _rank(d_severity):
            continue
        return fp
    return None


def _fuzzy_open_match(
    finding: Finding, open_threads: Sequence[PriorThread]
) -> PriorThread | None:
    if not finding.file or finding.line is None:
        return None
    candidates = [
        t
        for t in open_threads
        if t.path == finding.file
        and t.line is not None
        and abs(t.line - finding.line) <= PROXIMITY_LINES
        and categories_compatible(t.category, finding.category)
    ]
    if not candidates:
        return None
    # Prefer the closest line match; ties broken by the oldest comment.
    candidates.sort(key=lambda t: (abs((t.line or 0) - (finding.line or 0)), t.comment_id))
    return candidates[0]


def classify(
    finding: Finding,
    *,
    verdicts: Mapping[str, str],
    all_threads: Sequence[PriorThread],
) -> Classified:
    """Classify one candidate finding against everything this bot has ever
    posted on the PR, per the decision table:

    1. Exact `fingerprint(finding)` verdict `"dismissed"` -> suppress. A
       fuzzy (location + category + severity gated) dismissed match ->
       suppress. Otherwise fall through.
    2. Exact `fingerprint(finding)` verdict `"fixed"` -> recurred (thread is
       the resolved thread carrying that fingerprint, if any comment does —
       `None` for a body-level recurrence).
    3. Fuzzy match against a still-open, owned thread -> `escalate` if
       `finding.severity` outranks the thread's last-known severity, else
       `update`. A fuzzy match against an *outdated* thread reclassifies as
       `new` instead: GitHub already renders that thread as "Outdated" —
       effectively invisible — so a PATCH or reply there would be as good as
       silent for a diff-relevant finding.
    4. Otherwise: `new`.
    """
    fp = fingerprint(finding)
    open_threads = [t for t in all_threads if not t.is_resolved]

    if verdicts.get(fp) == "dismissed":
        return Classified(finding, "suppressed", None)
    if _fuzzy_dismissed_match(finding, verdicts, all_threads) is not None:
        return Classified(finding, "suppressed", None)

    if verdicts.get(fp) == "fixed":
        thread = _find_thread_by_fingerprint(all_threads, fp)
        return Classified(finding, "recurred", thread)

    thread = _fuzzy_open_match(finding, open_threads)
    if thread is not None:
        if thread.is_outdated:
            return Classified(finding, "new", None)
        thread_severity = thread.severity or finding.severity
        if _rank(finding.severity) < _rank(thread_severity):
            return Classified(finding, "escalate", thread)
        return Classified(finding, "update", thread)

    return Classified(finding, "new", None)


def dedupe_thread_claims(classified: Sequence[Classified]) -> list[Classified]:
    """Ensure at most one classified finding claims a given thread this run.

    `classify()` runs once per finding against a shared, unmodified
    `all_threads` snapshot, so two distinct findings within `PROXIMITY_LINES`
    of the same still-open thread can both fuzzy-match it and come back
    `"update"`/`"escalate"` referencing the identical `thread`. Applying both
    side effects would `PATCH` the same comment twice — the second write
    silently drops the first finding's content, since neither renders in the
    body — and, if both are `"escalate"`, post a duplicate reply. Keep only
    the highest-severity claim per `thread_id` (ties keep the earlier one);
    demote the rest to `"new"` so they get their own slot instead of
    disappearing.
    """
    best_index_by_thread: dict[str, int] = {}
    for i, c in enumerate(classified):
        if c.kind not in ("update", "escalate") or c.thread is None:
            continue
        tid = c.thread.thread_id
        current = best_index_by_thread.get(tid)
        if current is None or _rank(c.finding.severity) < _rank(
            classified[current].finding.severity
        ):
            best_index_by_thread[tid] = i

    kept = set(best_index_by_thread.values())
    return [
        Classified(c.finding, "new", None)
        if c.kind in ("update", "escalate") and c.thread is not None and i not in kept
        else c
        for i, c in enumerate(classified)
    ]


def decide_action(
    canonical: CanonicalReview | None,
    *,
    event: PostEvent,
    classified: Sequence[Classified],
    any_new_inline_eligible: bool,
) -> Literal["put", "post"]:
    """Decide whether this run can PUT the canonical review's body, or must
    POST a fresh review.

    `"post"` when:
    - there is no canonical review to reuse;
    - the canonical review is `DISMISSED` (superseded already; nothing left
      to reuse);
    - this run's outcome event doesn't correspond to the canonical review's
      current state (a state transition — e.g. the PR going from blocked to
      clean, or vice versa — is not something `PUT` can express: GitHub's
      `PUT /reviews/{id}` can only ever change a review's body, never its
      `state`/event, confirmed against GitHub's REST docs);
    - the canonical body doesn't carry our footer (most notably a
      human-facing message from `GitHubProvider.submit_approval`, issue
      #590's "approve on clear" path — PUTing a findings body over that
      message would erase it);
    - any classified finding is `"new"` and either `any_new_inline_eligible`
      (computed by the caller, which has the diff's eligible-line set) or
      the finding's severity is High/Critical: new information must be
      visible even when it can't get a diff anchor (out-of-diff, or over
      `max_inline`) — a silent body-only PUT would otherwise hide it.

    `"put"` otherwise, including when every `"new"` finding is body-level
    and below High severity (those still render in the reused body; they
    just don't force a fresh review object).
    """
    if canonical is None:
        return "post"
    if canonical.state == "DISMISSED":
        return "post"
    if _EVENT_FOR_STATE.get(canonical.state) != event:
        return "post"
    if _FOOTER_MARKER not in canonical.body:
        return "post"
    if any_new_inline_eligible:
        return "post"
    for c in classified:
        if c.kind == "new" and c.finding.severity in ("Critical", "High"):
            return "post"
    return "put"
