"""Bitbucket Cloud VCS provider — ports post-review-bitbucket.sh.

Implements the VcsProvider protocol for Bitbucket Cloud REST 2.0. Marker-gated
stale cleanup; cleanup runs after a successful post (2.FR-10).

Provider differences from GitHub/GitLab:
- No separate review entity — summary + findings collapse into a single
  PR comment. Inline-eligible findings anchor to the diff via Bitbucket
  Code Insights annotations (a display mechanism, not a real inline PR
  comment) rather than inline comments themselves. See
  docs/adr/0005-bitbucket-code-insights-not-inline-comment-threads.md for
  why. Everything else still renders as a flat bullet in the comment.
- Auth: HTTP Basic with email + API token (httpx.BasicAuth).
- Pagination via `next` URL in the response body (not Link header, not
  ?page=N counters).
- Comment body shape: `{"content": {"raw": "..."}}`.
- Body size limit: 32,768 chars on `content.raw`; we truncate at 32,000 to
  leave headroom for JSON encoding.
- No author info exposed uniformly on comments → marker-only ownership gating.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Sequence
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Final
from urllib.parse import quote

import httpx

if TYPE_CHECKING:
    # Deferred: `feedback.store` imports `vcs.http`, which would otherwise
    # import this module back (via `ai_pr_review.vcs`'s package `__init__`)
    # before it finishes executing. `from __future__ import annotations`
    # above means this is fine for annotations; `_get_feedback_store` does
    # the real (runtime, local) import itself.
    from ai_pr_review.feedback.store import FeedbackStore

from ai_pr_review.diff.linemap import parse_diff_sets
from ai_pr_review.findings.models import Finding, Severity
from ai_pr_review.vcs._bitbucket_verdicts import apply_pending_verdicts
from ai_pr_review.vcs._body import (
    compute_headline,
    format_body_finding,
    join_findings,
    render_skip_findings_section,
    sanitize_display_text,
    severity_icon,
    truncate_body,
)
from ai_pr_review.vcs._canonical import classify
from ai_pr_review.vcs._code_insights import post_code_insights
from ai_pr_review.vcs._finding_ids import assemble_id_map, fingerprint
from ai_pr_review.vcs._inline import partition_findings
from ai_pr_review.vcs._stale import is_owned_by_us
from ai_pr_review.vcs._upsert import advance_sha_marker, upsert_comment
from ai_pr_review.vcs.http import RecordingClient, RetryPolicy, TapeRecorder
from ai_pr_review.vcs.marker import (
    INLINE_MARKER_HIDDEN,
    SKIP_MARKER_HIDDEN,
    SUMMARY_MARKER_HIDDEN_PREFIX,
    SUMMARY_MARKER_PREFIX,
    USAGE_MARKER_HIDDEN,
    _hidden_marker_separator,
    append_inline_marker,
    append_skip_marker,
    build_acks_marker,
    build_id_map_marker,
    build_summary_marker,
    build_usage_block,
    build_verdicts_marker,
    extract_acks,
    extract_id_map,
    extract_summary_sha,
    extract_verdicts,
    has_skip_marker,
)
from ai_pr_review.vcs.protocol import (
    DiffContext,
    FindingsResult,
    PostEvent,
    StaleResult,
    SummaryResult,
)

_log = logging.getLogger(__name__)

_MAX_BITBUCKET_BODY_SIZE: Final[int] = 32_000
# Mirrors github.py's floor: never let the id-map marker crowd the visible
# body down to nothing -- if it would, drop the marker for this cycle instead
# (F-ID stability degrades gracefully rather than the review going blank).
_MIN_BODY_BYTES: Final[int] = 4_096
_FOOTER: Final[str] = (
    "---\n*AI Review — generated by "
    "[ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
)

_SEVERITY_RANK: Final[dict[Severity, int]] = {
    "Critical": 0,
    "High": 1,
    "Medium": 2,
    "Low": 3,
}


@dataclass(frozen=True)
class BitbucketConfig:
    """Identifies the Bitbucket Cloud PR target and auth credentials."""

    workspace: str
    repo_slug: str
    pr_id: int
    email: str
    api_token: str
    base_url: str = "https://api.bitbucket.org/2.0"
    # Bitbucket parity Phase 3 (#839/#873): render findings via Code Insights
    # annotations on the PR diff instead of only the flat comment body, and
    # gate the same flag on the id-map/verdict dedup this needs. Deliberately
    # one flag, not two (unlike AI_GITLAB_CROSS_RUN_DEDUP being separate from
    # AI_CANONICAL_REUSE) -- see ADR 0005's "second flag" rejected-alternative
    # section for why that precedent doesn't transfer here. Defaults True.
    # The kill switch is AI_BITBUCKET_CODE_INSIGHTS=false, which reproduces
    # pre-Phase-3 behavior (every finding rendered flat in the comment body,
    # no suppression) byte-for-byte.
    code_insights: bool = True
    # Bitbucket parity Phase 4 (#874): poll the PR's own top-level comments
    # for /ai-pr-review dismiss|false-positive|wont-fix|fixed F<n> commands
    # at review time (Bitbucket Pipelines has no comment-triggered event, so
    # this run IS the trigger). Defaults False -- unlike code_insights, this
    # gates a fail-closed authorization decision with real security-adjacent
    # consequences on a bug (see ai_pr_review.vcs._bitbucket_verdicts'
    # module docstring), so it stays opt-in through its own soak period
    # before a later phase defaults it on, mirroring how GitHub/GitLab's own
    # inline-comment work first shipped default-off.
    verdicts: bool = False
    # Minimum Bitbucket repository permission role required to apply a
    # verdict command: "read", "write", or "admin". Checked via
    # check_authority() against the commenter's account_id.
    verdict_min_role: str = "write"
    # Bitbucket parity (#918): actually call Bitbucket's approve/
    # request-changes/unapprove reviewer-state endpoints for the decided
    # review outcome, instead of only rendering it as heading text in the
    # comment body (which has zero effect on the PR's own reviewer-state
    # UI or on any branch-restriction rule keyed off "changes requested").
    # Defaults True for GitHub-parity: GitHub's provider already submits a
    # real review state for every run, and #918 asks for this to actually
    # do something on Bitbucket too. Still gets its own kill switch
    # (AI_BITBUCKET_REVIEW_STATE), following this dataclass's own
    # code_insights/verdicts precedent, because unlike a comment edit this
    # is a visible, potentially merge-affecting side effect on someone
    # else's PR that a workspace admin may want to opt out of.
    review_state: bool = True
    # Learning-loop store settings (issue #906). Gated by the same
    # AI_FEEDBACK_LOOP flag GitHub uses -- no separate Bitbucket-only flag,
    # since writing here needs no capability beyond what reading already
    # required plus Repository:Write on the token (see docs/bitbucket-setup.md's
    # security note on that scope). Only takes effect when `verdicts` is also
    # True: there is nothing to persist without the verdict poller running.
    enable_feedback_loop: bool = False
    feedback_branch: str = "ai-pr-review-bot"
    feedback_retention_count: int = 500
    feedback_retention_age_days: int = 365


def build_client(
    config: BitbucketConfig, retry: RetryPolicy | None = None
) -> RecordingClient:
    """Build a RecordingClient preconfigured for Bitbucket Cloud API calls."""
    http = httpx.Client(
        base_url=config.base_url,
        auth=httpx.BasicAuth(config.email, config.api_token),
        headers={
            "Accept": "application/json",
            "Content-Type": "application/json",
        },
        timeout=30.0,
    )
    return RecordingClient(
        http=http,
        recorder=TapeRecorder.from_env(provider="bitbucket"),
        retry_policy=retry or RetryPolicy(),
    )


@dataclass
class BitbucketProvider:
    """Bitbucket Cloud REST 2.0 implementation of VcsProvider."""

    config: BitbucketConfig
    client: RecordingClient
    _errors: list[str] = field(default_factory=list, init=False, repr=False)
    # Cache for _fetch_comments(): None means "not fetched yet this run",
    # not "fetched and empty" (an empty PR has an empty list cached as []).
    # Invalidated by every write this class makes to the comments endpoint
    # (see _write_request, post_findings, resolve_stale) so a later call in
    # the same run never reads stale data back.
    _comments_cache: list[dict[str, Any]] | None = field(
        default=None, init=False, repr=False
    )
    # Cache for _bot_account_id(): _UNRESOLVED means "not attempted yet this
    # run", None means "attempted and failed" -- both distinct from a real
    # account_id string, so a transient GET /2.0/user failure isn't retried
    # once-per-comment for the rest of the run.
    _bot_account_id_cache: str | None = field(default=None, init=False, repr=False)
    _bot_account_id_resolved: bool = field(default=False, init=False, repr=False)
    # Lazily built (issue #906): most runs never persist a verdict, so
    # there's no reason to construct a store up front. _UNRESOLVED
    # (sentinel, not None) distinguishes "not built yet" from "feedback
    # loop disabled" (a real, cached None), matching this class's own
    # _bot_account_id_cache/_bot_account_id_resolved precedent above.
    _feedback_store_cache: FeedbackStore | None = field(default=None, init=False, repr=False)
    _feedback_store_resolved: bool = field(default=False, init=False, repr=False)

    def _get_feedback_store(self) -> FeedbackStore | None:
        """Return this provider's `BitbucketSrcStore`, built over its own
        already-configured `RecordingClient` (so writes share the retry/
        tape-recording behavior every other Bitbucket call already has),
        or None when `AI_FEEDBACK_LOOP` is off. Local import: `feedback.store`
        imports `vcs.http`, which would otherwise import this module back
        (via `ai_pr_review.vcs`'s package `__init__`) before it finishes
        executing.
        """
        if self._feedback_store_resolved:
            return self._feedback_store_cache
        self._feedback_store_resolved = True
        if not self.config.enable_feedback_loop:
            return None
        from ai_pr_review.feedback.store import BitbucketSrcStore

        store = BitbucketSrcStore(
            workspace=self.config.workspace,
            repo_slug=self.config.repo_slug,
            branch=self.config.feedback_branch,
            client=self.client,
            retention_count=self.config.feedback_retention_count,
            retention_age_days=self.config.feedback_retention_age_days,
        )
        self._feedback_store_cache = store
        return store

    # ------------------------------------------------------------------
    # URL helpers
    # ------------------------------------------------------------------
    def _comments_url(self) -> str:
        c = self.config
        return f"/repositories/{c.workspace}/{c.repo_slug}/pullrequests/{c.pr_id}/comments"

    def _comment_url(self, comment_id: int) -> str:
        return f"{self._comments_url()}/{comment_id}"

    def _pull_request_url(self) -> str:
        c = self.config
        return f"/repositories/{c.workspace}/{c.repo_slug}/pullrequests/{c.pr_id}"

    # ------------------------------------------------------------------
    # Pagination — Bitbucket returns a `next` URL in the body
    # ------------------------------------------------------------------
    def _fetch_comments(self) -> list[dict[str, Any]]:
        """Fetch every PR comment in one paginated pass, cached per-instance.

        Previously `_list_summary_comments()` ran its own paginated fetch
        and filtered for the summary marker inline. This is the shared,
        unfiltered fetch it now sits on top of, so a later verdict-comment
        polling phase can reuse the same pass instead of paginating over
        the same endpoint a second time in the same run. The cache is
        invalidated by every write this class makes to the comments
        endpoint (see _write_request, post_findings, resolve_stale).

        Does not filter out comments with a `deleted` field. An earlier
        draft of this method did, on the theory that Bitbucket might mark
        removed comments that way, but that was unverified against a live
        API response and no `deleted` field precedent exists in this repo's
        Bitbucket fixtures. Filtering on unverified field semantics is a
        real behavior change, not appropriate for a PR whose only intended
        effect is sharing one paginated fetch across callers. If a later
        phase needs to exclude deleted comments (e.g. verdict polling),
        verify the field against real API output first and add the filter
        there with its own test coverage.
        """
        if self._comments_cache is not None:
            return self._comments_cache
        results: list[dict[str, Any]] = []
        url: str | None = self._comments_url()
        params: dict[str, Any] | None = {
            "pagelen": 100,
            "sort": "-updated_on",
        }
        while url:
            resp = self.client.request("GET", url, params=params)
            if resp.status_code >= 400:
                self._errors.append(
                    f"fetch_comments: HTTP {resp.status_code}: {resp.text[:200]}"
                )
                return results
            try:
                data = resp.json() or {}
            except ValueError as exc:
                # A malformed-but-2xx body (proxy error page, maintenance
                # banner) is a real Bitbucket failure mode -- degrade to
                # what's been paged so far rather than letting an unhandled
                # json.JSONDecodeError crash the whole review run. Mirrors
                # check_authority()'s identical guard in
                # ai_pr_review.vcs._bitbucket_verdicts, which this fetch is
                # now shared by (see this method's own docstring above).
                self._errors.append(
                    f"fetch_comments: non-JSON response body: {exc}"
                )
                return results
            results.extend(data.get("values") or [])
            next_url = data.get("next")
            if not isinstance(next_url, str) or not next_url:
                break
            # Strip the absolute base so the recording client's relative-URL
            # plumbing still works.
            url = _strip_base_url(next_url, self.config.base_url)
            params = None
        self._comments_cache = results
        return results

    def _list_summary_comments(self) -> list[dict[str, Any]]:
        """Return this bot's own summary comments, newest first.

        Security-critical (#894, the root-cause follow-up to #874's
        narrower verdicts-only fix): Bitbucket exposes no server-side "is
        this comment mine" filter and comments carry no privileged/
        verified-author flag, so a marker-substring match alone (the bash
        version's original behavior, kept client-side here defensively --
        Bitbucket sometimes ignores its own `q=` filter on rich-text
        fields) can be satisfied by ANY PR commenter, not just this bot.
        Every caller of this method -- SHA-watermark (`get_last_reviewed_
        sha`), `get_summary_body`, `post_findings`'s id-map/verdicts-marker
        read, and `resolve_stale`'s duplicate cleanup -- trusts whatever
        this returns as "the bot's own prior state", so filtering here once
        closes the gap for all of them at the root instead of each having
        its own (previously: only `post_findings`, and only for its
        verdicts read) independent check.

        Fails closed: when `_bot_account_id()` can't resolve this run's own
        identity (a transient `GET /2.0/user` error), returns `[]` rather
        than falling back to the unverified marker-substring match -- a
        forged comment must never be trusted as this bot's own state. The
        accepted cost of failing closed is a possible duplicate summary
        comment on that one run (the same "worst case" #874's narrower
        version already accepted for the verdicts marker specifically);
        the alternative (fail open) would silently reopen the exact
        forgery class this function exists to close, just scoped to
        whichever run happened to hit the transient lookup failure.
        """
        bot_account_id = self._bot_account_id()
        if bot_account_id is None:
            return []
        return [
            item
            for item in self._fetch_comments()
            if (
                SUMMARY_MARKER_PREFIX in _comment_body(item)
                or SUMMARY_MARKER_HIDDEN_PREFIX in _comment_body(item)
            )
            and (item.get("user") or {}).get("account_id") == bot_account_id
        ]

    def _bot_account_id(self) -> str | None:
        """Resolve and cache the account_id this run's credentials
        authenticate as, via ``GET /2.0/user``.

        Security-critical (#874 follow-up): Bitbucket exposes no
        server-side "is this comment mine" filter and comments carry no
        privileged/verified-author flag, so the only way to know a given
        comment was actually posted by this bot -- rather than by any PR
        commenter who happened to include the right marker text in their
        own comment -- is to compare `comment["user"]["account_id"]`
        against the identity these credentials actually resolve to.
        Without this check, `_list_summary_comments()`'s marker-substring
        filter (see its own comment) can be satisfied by ANY commenter, and
        `post_findings` would then trust whatever hidden verdicts marker
        that forged comment carries -- silently suppressing findings (a
        secret-scanner match, per #874's own motivating case) with no
        authorization check at all, defeating `check_authority()` entirely
        by skipping it. Resolved once per provider instance (one review
        run) and cached; returns `None` (not raised) on any failure, and
        callers must treat `None` as "cannot verify -- do not trust",
        mirroring `check_authority()`'s own fail-closed contract.
        """
        if self._bot_account_id_resolved:
            return self._bot_account_id_cache
        self._bot_account_id_resolved = True
        resp = self.client.request("GET", "/user")
        if resp.status_code >= 400:
            self._errors.append(
                f"_bot_account_id: HTTP {resp.status_code}: {resp.text[:200]}"
            )
            return None
        try:
            data = resp.json() or {}
        except ValueError as exc:
            self._errors.append(f"_bot_account_id: non-JSON response: {exc}")
            return None
        account_id = data.get("account_id")
        if not isinstance(account_id, str) or not account_id:
            self._errors.append(
                "_bot_account_id: response had no usable account_id field"
            )
            return None
        self._bot_account_id_cache = account_id
        return account_id

    def _write_request(self, method: str, url: str, **kwargs: Any) -> httpx.Response:
        """Issue a write (POST/PUT/DELETE) against the comments endpoint and
        invalidate the cached comment listing on success.

        Used in place of `self.client.request` wherever a caller in this
        file mutates PR comments through the shared upsert helpers in
        `_upsert.py`, so a later `_fetch_comments()` call in the same run
        re-fetches instead of returning what is now stale data.
        """
        resp = self.client.request(method, url, **kwargs)
        if resp.status_code < 400:
            self._comments_cache = None
        return resp

    # ------------------------------------------------------------------
    # get_last_reviewed_sha
    # ------------------------------------------------------------------
    def get_last_reviewed_sha(self) -> str | None:
        comments = self._list_summary_comments()
        if not comments:
            return None
        # sort=-updated_on means the first match is the most recent.
        latest = comments[0]
        body = ((latest.get("content") or {}).get("raw")) or ""
        return extract_summary_sha(
            body, context_hint=f"bitbucket_comment#{latest.get('id')}"
        )

    def get_summary_body(self) -> str | None:
        comments = self._list_summary_comments()
        if not comments:
            return None
        return ((comments[0].get("content") or {}).get("raw")) or None

    def get_pr_description(self) -> tuple[str, str] | None:
        """GET the PR's title and description. Returns `None` on any HTTP
        error (appended to `self._errors`) or a response missing a usable
        title. Unlike comment bodies, Bitbucket's pullrequest resource
        carries `description` as a plain markdown string, not a
        `{raw, markup, html}` object (#813).
        """
        resp = self.client.request("GET", self._pull_request_url())
        if resp.status_code >= 400:
            self._errors.append(
                f"get_pr_description: HTTP {resp.status_code}: {resp.text[:200]}"
            )
            return None
        try:
            data = resp.json()
        except ValueError:
            self._errors.append(
                f"get_pr_description: non-JSON body (status={resp.status_code})"
            )
            return None
        if not isinstance(data, dict):
            self._errors.append(
                f"get_pr_description: unexpected response shape {type(data).__name__}"
            )
            return None
        title = data.get("title")
        if not isinstance(title, str):
            return None
        description = data.get("description")
        return title, (description if isinstance(description, str) else "")

    # ------------------------------------------------------------------
    # post_summary / post_skip_comment / advance_sha_watermark
    # (delegated to module-level helpers for readability)
    # ------------------------------------------------------------------
    def post_summary(self, summary_body: str, head_sha: str) -> SummaryResult:
        return _post_summary_impl(self, summary_body, head_sha)

    def post_skip_comment(
        self, reason: str, *, findings: Sequence[Finding] = ()
    ) -> SummaryResult:
        return _post_skip_impl(self, reason, findings=findings)

    def advance_sha_watermark(self, new_sha: str) -> bool:
        return _advance_sha_impl(self, new_sha)

    # ------------------------------------------------------------------
    # post_findings — appends findings into the existing summary comment
    # ------------------------------------------------------------------
    def post_findings(
        self,
        findings: Sequence[Finding],
        diff: DiffContext,
        *,
        event: PostEvent,
        failed_agents: Sequence[str] = (),
        usage_block: str = "",
        usage_warning: str = "",
        agent_prompt: str = "",
        max_inline: int = 25,
        enable_suggestions: bool = True,
        summary_comment_id: int | None = None,
    ) -> FindingsResult:
        """Render the summary comment body, with inline-eligible findings
        also posted as Bitbucket Code Insights annotations when
        `self.config.code_insights` is enabled (default).

        We render the findings markdown and PUT the existing summary comment
        with the combined body. If no summary comment exists, this is a no-op
        (the orchestrator MUST call post_summary first per the AC5 ordering).

        `max_inline` caps how many findings get a Code Insights annotation
        this run, same semantics as GitHub/GitLab's inline-comment cap.
        `enable_suggestions` and `agent_prompt` are accepted for protocol
        compatibility but unused here -- Code Insights annotations have no
        code-suggestion mechanism, and Bitbucket has no per-run agent-prompt
        rendering surface the way GitHub's inline comments do.
        """
        existing = self._list_summary_comments()
        if not existing and summary_comment_id is not None:
            # #930: `_list_summary_comments()` is a list-and-filter query,
            # and Bitbucket's PR-comments listing endpoint isn't guaranteed
            # to immediately reflect a comment this exact run just created
            # via post_summary's POST a moment ago -- reproduced live on a
            # brand-new (POST-created, not PUT-updated) summary comment,
            # where nothing had this id indexed before this run started.
            # Fall back to a direct GET on the id post_summary already
            # resolved, which doesn't depend on that listing endpoint's
            # consistency. No separate authorship re-check is needed here:
            # `summary_comment_id` only ever reaches this call as this same
            # run's own `post_summary` result (`orchestrate.py`), i.e. a
            # comment these same credentials just created.
            resp = self.client.request("GET", self._comment_url(summary_comment_id))
            if resp.status_code < 400:
                try:
                    item = resp.json()
                except ValueError:
                    item = None
                if isinstance(item, dict) and (
                    SUMMARY_MARKER_PREFIX in _comment_body(item)
                    or SUMMARY_MARKER_HIDDEN_PREFIX in _comment_body(item)
                ):
                    existing = [item]
        if not existing:
            # This also means Code Insights annotations never get posted
            # for this run, even though they don't structurally depend on
            # the comment beyond the optional [F<n>] token (build_annotation_
            # payload already tolerates finding_id=None). Deliberate: the
            # comment is the source of the verdicts marker this same run
            # reads to decide what to suppress, and per the AC5 ordering the
            # orchestrator was already required to call post_summary first,
            # so reaching this branch means something upstream is already
            # broken. Diff decoration silently continuing while the actual
            # state layer failed to post would be a worse failure mode than
            # both failing together.
            err = "post_findings: no summary comment to attach findings to"
            self._errors.append(err)
            return FindingsResult(
                review_id=None,
                inline_posted=0,
                body_findings=len(findings),
                event=event,
                degraded_to_comment=False,
                error=err,
            )

        keep = existing[0]
        keep_id = int(keep["id"])
        existing_body = _comment_body(keep)

        # Stable F-IDs and a "new since last review" signal, mirroring
        # GitHub's assemble_id_map/fingerprint machinery -- Bitbucket already
        # fetched existing_body above, so it's reused directly as the sole
        # prior body rather than issuing a second lookup via
        # get_summary_body() (same data, one fewer HTTP round-trip).
        prior_id_map = extract_id_map(existing_body) if existing_body else {}
        id_map = assemble_id_map(
            [existing_body] if existing_body else [], list(findings)
        )

        # #894 (root-cause follow-up to #874's narrower fix): `keep` is now
        # guaranteed bot-authored by `_list_summary_comments()` itself (or
        # `existing` above would already be empty), so no separate
        # authorship check is needed here -- previously this block
        # independently re-verified authorship, scoped only to the
        # verdicts marker and only when `self.config.verdicts` was on,
        # leaving the SHA-watermark/id-map reads below (and every other
        # caller of `_list_summary_comments()`) with the same gap. See
        # `_list_summary_comments()`'s own docstring for the fail-closed
        # contract this now relies on uniformly.

        # Snapshot of whatever verdicts were already durably persisted
        # before this call, independent of anything the code_insights/
        # verdicts-polling block below does or fails to do. Computed
        # unconditionally (even with code_insights/verdicts off) so the
        # marker-build stage further down always has a known-good fallback
        # to preserve rather than silently dropping suppression state on an
        # overflow or a mid-cycle exception -- see the verdicts_marker
        # overflow handling below for why this matters.
        old_verdicts_snapshot: dict[str, str] = (
            extract_verdicts(existing_body) if existing_body else {}
        )

        # Bitbucket parity Phase 3 (#839/#873): Code Insights annotations as
        # the inline display layer, gated by one flag alongside the dedup it
        # needs (see BitbucketConfig.code_insights' docstring). Disabled,
        # this reproduces pre-Phase-3 behavior byte-for-byte: every finding
        # renders flat in the comment body below, no suppression.
        render_findings = list(findings)
        headline_findings: Sequence[Finding] = render_findings
        suppressed_count = 0
        annotated_count = 0
        # Which findings actually landed a Code Insights annotation this
        # cycle (issue #919) -- those get a shortened bullet in the body.
        # Empty here (code_insights disabled, or before the try block runs)
        # means every rendered finding gets its full bullet.
        annotated_fingerprints: frozenset[str] = frozenset()
        # Set only when this run wrote a change to the verdicts/acks state
        # that needs persisting back into the comment body -- see the
        # reserve-then-append block below, mirroring id_map_marker's own
        # "None means nothing to write" contract.
        verdicts_marker_payload: dict[str, str] | None = None
        acks_marker_ids: frozenset[int] | None = None
        # Set True the moment any ack reply is actually POSTed this call --
        # initialized outside the try block since the except handler below
        # needs to know this even if the exception happened before the
        # verdict-polling code ran far enough to set it itself.
        replies_sent_this_cycle = False
        if self.config.code_insights:
            try:
                verdicts = dict(old_verdicts_snapshot)
                # Fingerprints whose verdict this exact cycle just set (as
                # opposed to one already persisted from a prior run) -- the
                # recurred-tombstone rewrite below must never touch these.
                # Without this guard, a "fixed" command applied this same
                # cycle would immediately classify() as "recurred" (the
                # finding is still present in `findings`, since the command
                # doesn't retroactively remove it from the diff) and get
                # silently flipped back before the human's verdict ever
                # reaches the comment body -- the poll-at-review-time design
                # (unlike GitHub/GitLab, where a verdict command and the
                # next classify() pass are always separate runs) makes this
                # collision reachable in a single call here.
                freshly_set_fps: frozenset[str] = frozenset()

                # Bitbucket parity Phase 4 (#874): poll the PR's own
                # top-level comments for /ai-pr-review verdict commands
                # before classifying. Gated separately from code_insights
                # (self.config.verdicts) -- see BitbucketConfig.verdicts'
                # docstring for why this stays its own opt-in flag. Only
                # reachable inside the code_insights block because
                # classify() just below is the only place a verdict
                # actually changes anything; polling with code_insights
                # disabled would collect commands nothing acts on.
                if self.config.verdicts:
                    poll_result = apply_pending_verdicts(
                        self.client,
                        workspace=self.config.workspace,
                        repo_slug=self.config.repo_slug,
                        comments=self._fetch_comments(),
                        # apply_pending_verdicts independently re-derives
                        # its own baseline verdicts, acks, AND F<n> ->
                        # fingerprint resolution from this string.
                        # existing_body is safe to pass through unguarded
                        # here (#894): `keep` (and therefore existing_body)
                        # is now guaranteed bot-authored by
                        # `_list_summary_comments()` itself, or `existing`
                        # above would already be empty and this whole
                        # function would have returned before reaching
                        # here.
                        existing_body=existing_body,
                        min_role=self.config.verdict_min_role,
                        feedback_store=self._get_feedback_store(),
                    )
                    freshly_set_fps = frozenset(
                        fp
                        for fp, v in poll_result.verdicts.items()
                        if verdicts.get(fp) != v
                    )
                    verdicts = dict(poll_result.verdicts)
                    for poll_error in poll_result.errors:
                        # Logged explicitly, not just appended to
                        # self._errors: orchestrate.py never reads this
                        # provider's _errors list on a normal review run
                        # (only slash/github_ops.py's command handlers do,
                        # and that's GitHub-only), and self._errors only
                        # ever reaches FindingsResult.error when the final
                        # comment PUT itself fails -- a verdict-polling
                        # error (e.g. a malformed permission-lookup
                        # response) on an otherwise-successful run would
                        # otherwise be silently absorbed into a passing
                        # FindingsResult with no log trail at all.
                        _log.warning(
                            "bitbucket: verdict polling error for %s/%s PR "
                            "#%s: %s",
                            self.config.workspace, self.config.repo_slug,
                            self.config.pr_id, poll_error,
                        )
                        self._errors.append(
                            f"post_findings: verdict polling: {poll_error}"
                        )
                    # A comment whose ack-reply POST fails must NOT be
                    # recorded as acked: apply_pending_verdicts already
                    # applied its verdict into `verdicts` above (that part
                    # is durable once the body PUTs below), but the human
                    # never received their reply. Leaving the id off the
                    # acks marker means the same command comment is
                    # re-parsed next run -- re-applying an already-applied
                    # verdict is a no-op, but it gives the reply another
                    # chance to actually land, instead of being silently
                    # and permanently dropped.
                    reply_failed_comment_ids: set[int] = set()
                    for comment_id, reply_text in poll_result.replies:
                        replies_sent_this_cycle = True
                        reply_resp = self._write_request(
                            "POST",
                            self._comments_url(),
                            json_body={
                                "content": {"raw": reply_text},
                                "parent": {"id": comment_id},
                            },
                        )
                        if reply_resp.status_code >= 400:
                            reply_failed_comment_ids.add(comment_id)
                            _log.warning(
                                "bitbucket: verdict ack reply to comment %s "
                                "failed for %s/%s PR #%s: HTTP %d: %s",
                                comment_id, self.config.workspace,
                                self.config.repo_slug, self.config.pr_id,
                                reply_resp.status_code, reply_resp.text[:200],
                            )
                            self._errors.append(
                                "post_findings: verdict ack reply to comment "
                                f"{comment_id} failed: HTTP "
                                f"{reply_resp.status_code}: "
                                f"{reply_resp.text[:200]}"
                            )
                    acks_marker_ids = extract_acks(existing_body) | frozenset(
                        cid
                        for cid in poll_result.newly_acked_ids
                        if cid not in reply_failed_comment_ids
                    )

                classified = [
                    classify(f, verdicts=verdicts, all_threads=[]) for f in findings
                ]
                # A "recurred" classification (a stale "fixed" verdict whose
                # finding reappeared unchanged) must overwrite its verdict
                # entry to the "recurred" tombstone, or classify() keeps
                # re-deriving "recurred" off the same stale "fixed" entry
                # forever -- harmless in effect (classify() treats
                # "recurred" identically to no verdict) but a silent,
                # permanent drift from what the marker claims. Mirrors
                # github.py's _apply_classification_side_effects' recurred
                # handling. Only rewritten when verdicts polling is on:
                # with it off, `verdicts` was never mutated this run and
                # there is nothing new worth persisting.
                if self.config.verdicts:
                    for c in classified:
                        fp = fingerprint(c.finding)
                        if c.kind == "recurred" and fp not in freshly_set_fps:
                            verdicts[fp] = "recurred"
                    verdicts_marker_payload = verdicts

                active_findings = [
                    c.finding for c in classified if c.kind != "suppressed"
                ]
                suppressed_count = len(classified) - len(active_findings)
                # The headline (Overall Risk / Findings count) always
                # reflects every still-active finding, regardless of which
                # ones actually land an annotation this cycle -- mirrors
                # github.py's headline_findings/render_findings split for
                # the same reason: a finding shown only via Code Insights
                # must not silently drop out of "Overall Risk".
                headline_findings = active_findings

                added_lines, _new_files = parse_diff_sets(diff.diff_text)
                eligible_new = {(lr.file, lr.line) for lr in added_lines}
                # issue #919: only the inline candidates are used below now
                # -- every active finding renders in the body regardless of
                # inline eligibility, so the old body-only complement of
                # this split has no remaining consumer.
                inline_candidates, _body_only = partition_findings(
                    active_findings, eligible_new=eligible_new, max_inline=max_inline
                )

                ci_result = post_code_insights(
                    self.client,
                    workspace=self.config.workspace,
                    repo_slug=self.config.repo_slug,
                    commit=diff.head_sha,
                    findings=inline_candidates,
                    all_active_findings=active_findings,
                    id_map=id_map,
                )
                annotated_count = ci_result.posted
                # issue #919: every active finding renders in the body now
                # (previously only body_only did) -- a finding whose
                # fingerprint is in annotated_fingerprints gets a shortened
                # bullet (no remediation, see _render_combined_body) since
                # that detail already lives in its annotation. This is why
                # the body_only/unposted split that used to gate
                # render_findings is gone: rendering is unconditional now,
                # only the *shortened-vs-full* choice depends on which
                # findings actually got an annotation this cycle.
                annotated_fingerprints = frozenset(
                    fingerprint(f) for f in ci_result.posted_findings
                )
                render_findings = active_findings
                if not ci_result.ok:
                    # Code Insights unavailable on this workspace's plan
                    # (403/404), or a batch partway through the annotation
                    # POST failed. Every active finding still renders fully
                    # in the body regardless (only the ones actually in
                    # annotated_fingerprints get shortened), so nothing is
                    # lost here -- this branch only needs to log the
                    # degradation. Logged once per run, not once per
                    # finding.
                    _log.warning(
                        "bitbucket: Code Insights posting failed for %s/%s "
                        "PR #%s, findings still render fully in the "
                        "summary comment body: %s",
                        self.config.workspace, self.config.repo_slug,
                        self.config.pr_id, ci_result.error,
                    )
                    self._errors.append(f"post_findings: {ci_result.error}")
            except Exception as exc:  # noqa: BLE001
                # A bug anywhere in this block (classify/extract_verdicts on
                # a malformed existing_body, a future change to any of these
                # shared helpers) must not take down the whole post_findings
                # call -- the comment PUT below still has to run, or every
                # finding for this cycle is lost, not just the ones destined
                # for annotations. Degrade to the code_insights=False
                # behavior for this run only: every finding renders flat in
                # the body, no suppression, no annotations. Mirrors the
                # fail-soft treatment the id_map_marker build already gets
                # a few lines below.
                _log.warning(
                    "bitbucket: Code Insights processing raised unexpectedly "
                    "for %s/%s PR #%s, falling back to flat body rendering "
                    "for this cycle: %s",
                    self.config.workspace, self.config.repo_slug,
                    self.config.pr_id, exc,
                )
                self._errors.append(f"post_findings: Code Insights processing failed: {exc}")
                render_findings = list(findings)
                headline_findings = render_findings
                suppressed_count = 0
                annotated_count = 0
                annotated_fingerprints = frozenset()
                # Discard any verdict-polling side effects from this cycle
                # too: if classify() itself is what raised, `verdicts`/
                # `classified` may be partial or absent -- don't persist a
                # payload built from state this run never finished
                # computing.
                verdicts_marker_payload = None
                acks_marker_ids = None
                if replies_sent_this_cycle:
                    # This is worse than an ordinary degrade: at least one
                    # human already received an ack reply claiming their
                    # verdict command succeeded (not undoable -- Bitbucket
                    # has no reply-delete call in this provider), but the
                    # verdict/acks state that reply promised is being
                    # discarded right here. The command comment is not
                    # marked acked, so it WILL be re-parsed and re-applied
                    # next run (harmless -- verdict application is
                    # idempotent), but that also means a second, possibly
                    # redundant-looking reply will be posted then. Flagged
                    # at ERROR (not the surrounding WARNING) since this is
                    # the one failure mode in this block that has already
                    # made an externally-visible, incorrect claim.
                    _log.error(
                        "bitbucket: at least one verdict ack reply was "
                        "already posted for %s/%s PR #%s before Code "
                        "Insights processing failed -- the promised verdict "
                        "state was NOT persisted this cycle and will be "
                        "reprocessed (with a duplicate-looking reply) next "
                        "run: %s",
                        self.config.workspace, self.config.repo_slug,
                        self.config.pr_id, exc,
                    )
                    self._errors.append(
                        "post_findings: verdict ack reply already sent this "
                        "cycle, but Code Insights processing failed "
                        "afterward -- verdict/acks state was not persisted "
                        f"and will be reprocessed next run: {exc}"
                    )

        # usage_block/usage_warning are deliberately NOT passed into
        # _render_combined_body: findings_block alone can be arbitrarily
        # large (a real e2e run against a heavily-seeded test PR produced 63
        # findings, filling the entire 32,000-byte budget on its own), so
        # embedding either inside the pre-truncation string -- at any
        # position -- does not guarantee it survives. Both are reserved and
        # appended after truncation instead, the same way id_map_marker
        # already is, below.
        body = _render_combined_body(
            existing_body=existing_body,
            findings=render_findings,
            headline_findings=headline_findings,
            annotated_count=annotated_count,
            annotated_fingerprints=annotated_fingerprints,
            event=event,
            failed_agents=failed_agents,
            agent_prompt=agent_prompt,
            id_map=id_map,
            prior_id_map=prior_id_map,
            workspace=self.config.workspace,
            repo_slug=self.config.repo_slug,
            head_sha=diff.head_sha,
        )

        # Embed the ID map as a hidden marker so the next run (and the
        # dismiss workflow, once Bitbucket gets one) can reconstruct
        # fingerprint -> F-ID associations without re-parsing rendered bullet
        # text. Reserve its bytes before truncating -- same ordering as
        # github.py's post_findings -- so a near-the-limit body doesn't
        # silently drop the marker and renumber every F-ID next cycle.
        id_map_marker = ""
        try:
            id_map_marker = build_id_map_marker(id_map, hidden=True)
        except Exception as exc:  # noqa: BLE001
            # Logged (not just appended to self._errors): orchestrate.py never
            # reads this provider's _errors list for a normal review run
            # (only slash/github_ops.py's command handlers do), and
            # this failure must not set FindingsResult.error either -- the
            # comment itself still posts fine below, just without F-ID
            # stability for this cycle, and orchestrate.py gates
            # watermark-advance/stale-cleanup on .ok/.error (#493) -- failing
            # that gate over a cosmetic marker loss would force an
            # unnecessary full re-diff next cycle, a worse outcome than the
            # degraded F-IDs this is actually about. Mirrors github.py's
            # identical failure-class handling.
            _log.warning("bitbucket: failed to build id-map marker: %s", exc)
            self._errors.append(f"post_findings: failed to build id-map marker: {exc}")
        marker_bytes = len(id_map_marker.encode("utf-8")) if id_map_marker else 0
        # +2, not +1: the separator that will actually be prepended below is
        # `_hidden_marker_separator(body)`, and at this call site `body` (the
        # freshly-appended INLINE_MARKER_HIDDEN form) never ends in a
        # newline, so that separator is always the 2-byte "\n\n" -- never the
        # 1-byte "\n" case that function also supports for other callers.
        marker_reserve = marker_bytes + 2 if id_map_marker else 0
        if id_map_marker and marker_reserve > _MAX_BITBUCKET_BODY_SIZE - _MIN_BODY_BYTES:
            _log.warning(
                "bitbucket: id-map marker (%d bytes) too large to fit in "
                "comment body for %s/%s PR #%s; omitting marker for this "
                "cycle -- F-ID stability may degrade",
                marker_bytes,
                self.config.workspace, self.config.repo_slug, self.config.pr_id,
            )
            self._errors.append(
                f"post_findings: id-map marker ({marker_bytes} bytes) too large "
                "to fit in comment body; omitting for this cycle"
            )
            id_map_marker = ""
            marker_reserve = 0

        # Bitbucket parity Phase 4 (#874): persist this run's verdict/ack
        # state the same reserve-then-append way as id_map_marker just
        # above. Unlike id_map_marker, losing this marker isn't merely
        # cosmetic -- it IS the suppression state, so dropping it would let
        # every previously-dismissed finding on the PR reappear at once,
        # not just whatever changed this cycle. That is categorically worse
        # than the graceful "F-ID stability may degrade" the id_map_marker
        # accepts above, so this never just drops to "" on overflow the way
        # that one does: it first falls back to re-persisting exactly what
        # was ALREADY durably on the PR (`old_verdicts_snapshot`, captured
        # before this call touched anything), which -- having fit in a
        # previous cycle's body -- is very unlikely to overflow now unless
        # the budget shrank a lot this cycle. Only if even that still
        # doesn't fit does the marker actually get dropped, logged at
        # ERROR rather than WARNING since that is a genuine loss of
        # suppression state, not a degrade.
        #
        # Picking a payload to try, in priority order:
        #   1. This cycle's full merged payload (old + newly-applied
        #      commands + recurred tombstones), if this cycle produced one.
        #   2. The old snapshot (possibly empty), otherwise.
        #
        # #886 hardening: always try to write a marker, even an empty one,
        # regardless of `self.config.verdicts` -- extract_verdicts() trusts
        # whichever marker-shaped string appears LAST in the body, so a
        # summary comment with no real marker at all (the old `verdicts=False`
        # behavior) leaves any forged marker-shaped text elsewhere in the
        # rendered summary/findings as the last match by default. A trailing
        # `{}` (or the unchanged snapshot) marker guarantees the last match is
        # always ours. This is a body write, not a suppression-state change:
        # `verdicts=False` still means findings are never classified against
        # verdicts (see `classify(f, verdicts=verdicts, ...)` above), and
        # `old_verdicts_snapshot` is durable state already on the PR either
        # way, not something this write newly grants meaning to.
        _verdicts_payload_to_try: dict[str, str] = (
            verdicts_marker_payload
            if verdicts_marker_payload is not None
            else dict(old_verdicts_snapshot)
        )

        def _build_verdicts_marker_or_none(
            payload: dict[str, str],
        ) -> tuple[str, int, int]:
            try:
                marker_text = build_verdicts_marker(payload, hidden=True)
            except Exception as exc:  # noqa: BLE001
                _log.warning("bitbucket: failed to build verdicts marker: %s", exc)
                self._errors.append(
                    f"post_findings: failed to build verdicts marker: {exc}"
                )
                return "", 0, 0
            marker_bytes_ = len(marker_text.encode("utf-8"))
            return marker_text, marker_bytes_, marker_bytes_ + 2

        # Always non-empty now (#886 hardening; see the comment above), so
        # this always builds a marker -- unlike id_map_marker, `{}` is a
        # real, intentional payload here, not "nothing to write".
        verdicts_marker, verdicts_marker_bytes, verdicts_marker_reserve = (
            _build_verdicts_marker_or_none(_verdicts_payload_to_try)
        )

        if (
            verdicts_marker
            and marker_reserve + verdicts_marker_reserve
            > _MAX_BITBUCKET_BODY_SIZE - _MIN_BODY_BYTES
        ):
            is_already_fallback = _verdicts_payload_to_try is old_verdicts_snapshot
            fallback_payload: dict[str, str] | None = None
            if not is_already_fallback and old_verdicts_snapshot:
                fallback_payload = dict(old_verdicts_snapshot)
                # Tombstone corrections only ever overwrite a key that's
                # already in old_verdicts_snapshot (classify()'s "recurred"
                # requires a pre-existing "fixed" verdict) -- carrying them
                # into the fallback can't grow its size.
                if verdicts_marker_payload is not None:
                    for fp, v in verdicts_marker_payload.items():
                        if v == "recurred" and fp in fallback_payload:
                            fallback_payload[fp] = "recurred"

            fallback_marker, fallback_bytes, fallback_reserve = (
                _build_verdicts_marker_or_none(fallback_payload)
                if fallback_payload is not None
                else ("", 0, 0)
            )
            if fallback_marker and marker_reserve + fallback_reserve <= (
                _MAX_BITBUCKET_BODY_SIZE - _MIN_BODY_BYTES
            ):
                _log.warning(
                    "bitbucket: this cycle's verdicts payload (%d bytes) too "
                    "large to fit in comment body for %s/%s PR #%s; falling "
                    "back to re-persisting the %d previously-persisted "
                    "verdicts unchanged. Any verdict commands applied THIS "
                    "cycle were not saved and were left un-acked so they are "
                    "reprocessed next run.",
                    verdicts_marker_bytes,
                    self.config.workspace, self.config.repo_slug,
                    self.config.pr_id, len(old_verdicts_snapshot),
                )
                self._errors.append(
                    "post_findings: verdicts marker too large "
                    f"({verdicts_marker_bytes} bytes); fell back to the "
                    f"{len(old_verdicts_snapshot)} previously-persisted "
                    "verdicts, dropping this cycle's new commands until "
                    "the body has room again"
                )
                verdicts_marker = fallback_marker
                verdicts_marker_bytes = fallback_bytes
                verdicts_marker_reserve = fallback_reserve
                # New commands from this cycle weren't persisted -- leave
                # their comments unacked too, so they're retried next run
                # instead of silently forgotten (mirrors the reply-POST-
                # failure handling above).
                acks_marker_ids = (
                    extract_acks(existing_body) if existing_body else frozenset()
                )
            else:
                _log.error(
                    "bitbucket: verdicts marker still too large (%d bytes) "
                    "even falling back to only the %d previously-persisted "
                    "verdicts for %s/%s PR #%s -- dropping the verdicts "
                    "marker entirely this cycle. ALL suppression state will "
                    "be lost until the comment body has room again.",
                    verdicts_marker_bytes, len(old_verdicts_snapshot),
                    self.config.workspace, self.config.repo_slug, self.config.pr_id,
                )
                self._errors.append(
                    "post_findings: verdicts marker too large even with only "
                    f"previously-persisted verdicts ({len(old_verdicts_snapshot)} "
                    "entries); dropping the marker entirely this cycle -- all "
                    "suppression state will be lost"
                )
                verdicts_marker = ""
                verdicts_marker_reserve = 0
                acks_marker_ids = (
                    extract_acks(existing_body) if existing_body else frozenset()
                )

        acks_marker = ""
        if acks_marker_ids is not None:
            try:
                acks_marker = build_acks_marker(sorted(acks_marker_ids))
            except Exception as exc:  # noqa: BLE001
                _log.warning("bitbucket: failed to build acks marker: %s", exc)
                self._errors.append(
                    f"post_findings: failed to build acks marker: {exc}"
                )
        acks_marker_bytes = len(acks_marker.encode("utf-8")) if acks_marker else 0
        acks_marker_reserve = acks_marker_bytes + 2 if acks_marker else 0
        if (
            acks_marker
            and marker_reserve + verdicts_marker_reserve + acks_marker_reserve
            > _MAX_BITBUCKET_BODY_SIZE - _MIN_BODY_BYTES
        ):
            _log.warning(
                "bitbucket: acks marker (%d bytes) too large to fit in "
                "comment body for %s/%s PR #%s; omitting marker for this "
                "cycle -- a re-parsed command comment may get a duplicate "
                "ack reply next run",
                acks_marker_bytes,
                self.config.workspace, self.config.repo_slug, self.config.pr_id,
            )
            self._errors.append(
                f"post_findings: acks marker ({acks_marker_bytes} bytes) too "
                "large to fit in comment body; omitting for this cycle"
            )
            acks_marker = ""
            acks_marker_reserve = 0

        # Reserve room for the usage block too, and append it after
        # truncation rather than embedding it in `body` beforehand (#728) --
        # findings_block alone can exceed the entire byte budget (a real
        # heavily-seeded test PR produced 63 findings), so no position
        # inside the pre-truncation string guarantees survival; only an
        # explicit reservation does, same as id_map_marker above.
        #
        # Order matters here: _strip_details_wrapper runs on the BARE
        # usage_block (no marker prefix yet) so its `\A<details>...\Z`
        # anchor can still match a full-mode accordion; the mode-independent
        # marker (#758) is prepended via build_usage_block AFTER stripping,
        # in its Bitbucket-hidden reference-link form -- prepending it
        # first would put marker text before the `<details>` tag and make
        # the anchored regex fail to match, silently un-fixing #703. Under
        # `compact`/`off`, usage_block has no `<details>` wrapper for the
        # regex to match in the first place, so stripping is a no-op
        # pass-through for those modes; build_usage_block still always
        # prepends the marker, including onto "" (`off`, or no data), so
        # every posted comment carries the same anchor regardless of mode --
        # this always runs (unlike GitLab's gated update), since Bitbucket
        # composes and PUTs a full comment body on every call regardless.
        stripped_payload = _strip_details_wrapper(usage_block) if usage_block else ""
        usage_block_marked = build_usage_block(stripped_payload, hidden=True)
        usage_block_bytes = len(usage_block_marked.encode("utf-8"))
        usage_block_reserve = usage_block_bytes + 2
        if (
            marker_reserve + verdicts_marker_reserve + acks_marker_reserve
            + usage_block_reserve
            > _MAX_BITBUCKET_BODY_SIZE - _MIN_BODY_BYTES
        ):
            _log.warning(
                "bitbucket: token usage block (%d bytes) too large to fit "
                "alongside the id-map marker in comment body for %s/%s PR "
                "#%s; omitting it for this cycle",
                usage_block_bytes,
                self.config.workspace, self.config.repo_slug, self.config.pr_id,
            )
            # Still reserve/emit the bare marker alone (a handful of bytes)
            # rather than dropping the anchor entirely for this cycle.
            usage_block_marked = build_usage_block("", hidden=True)
            usage_block_bytes = len(usage_block_marked.encode("utf-8"))
            usage_block_reserve = usage_block_bytes + 2

        # The high-usage warning (#758) gets the same reserve-then-append
        # treatment, as its own segment -- never combined into usage_block
        # itself (see protocol.py's post_findings docstring for why: a
        # warning glued onto an accordion string would break the regex
        # above, which is anchored on the accordion being the *entire*
        # input).
        usage_warning_bytes = len(usage_warning.encode("utf-8")) if usage_warning else 0
        usage_warning_reserve = usage_warning_bytes + 2 if usage_warning else 0
        if usage_warning and (
            marker_reserve + verdicts_marker_reserve + acks_marker_reserve
            + usage_block_reserve + usage_warning_reserve
            > _MAX_BITBUCKET_BODY_SIZE - _MIN_BODY_BYTES
        ):
            _log.warning(
                "bitbucket: high-usage warning (%d bytes) too large to fit "
                "in comment body for %s/%s PR #%s; omitting it for this cycle",
                usage_warning_bytes,
                self.config.workspace, self.config.repo_slug, self.config.pr_id,
            )
            usage_warning = ""
            usage_warning_reserve = 0

        truncate_limit = max(
            0,
            _MAX_BITBUCKET_BODY_SIZE
            - marker_reserve
            - verdicts_marker_reserve
            - acks_marker_reserve
            - usage_block_reserve
            - usage_warning_reserve,
        )
        body = truncate_body(body, limit=truncate_limit)
        # rstrip+"\n\n" (rather than the bare "\n" _render_combined_body used
        # to join on) guarantees a real blank line before the block
        # regardless of whether it ends in its own trailing newline. Under
        # `full`, the stripped accordion inside usage_block_marked always
        # ends in exactly one "\n" -- that, plus this join, is what keeps
        # Bitbucket's table parser from absorbing whatever follows as a
        # spurious trailing row (#703). Under `compact`/`off`, the payload
        # isn't a table (no such hazard), but the same normalization keeps
        # it visually separated as its own paragraph. usage_block_marked
        # always carries at least the bare marker, so this always runs.
        body = body.rstrip("\n") + "\n\n" + usage_block_marked.rstrip("\n")
        if usage_warning:
            body = body.rstrip("\n") + "\n\n" + usage_warning
        # Footer is appended unconditionally, like INLINE_MARKER_HIDDEN below --
        # neither is reserved for, matching this function's existing tolerance
        # for a small overshoot past _MAX_BITBUCKET_BODY_SIZE (itself already a
        # conservative estimate of Bitbucket's actual server-side limit, not
        # an exact boundary -- see issue #728).
        body = body.rstrip("\n") + "\n\n" + _FOOTER
        body = append_inline_marker(body, marker=INLINE_MARKER_HIDDEN)
        if id_map_marker:
            # `[//]: # (...)` cannot interrupt a paragraph per CommonMark
            # (see marker.py's _hidden_marker_separator docstring) — a bare
            # "\n" after the footer's italic line would risk it rendering as
            # literal text on a stricter renderer than Bitbucket's own.
            body += _hidden_marker_separator(body) + id_map_marker
        if verdicts_marker:
            body += _hidden_marker_separator(body) + verdicts_marker
        if acks_marker:
            body += _hidden_marker_separator(body) + acks_marker

        resp = self.client.request(
            "PUT", self._comment_url(keep_id), json_body={"content": {"raw": body}}
        )
        if resp.status_code >= 400:
            err = f"post_findings PUT: HTTP {resp.status_code}: {resp.text[:200]}"
            self._errors.append(err)
            return FindingsResult(
                review_id=keep_id,
                inline_posted=annotated_count,
                body_findings=len(render_findings),
                event=event,
                degraded_to_comment=False,
                suppressed=suppressed_count,
                error=err,
            )
        self._comments_cache = None
        if self.config.review_state:
            self._set_review_state(event)
        return FindingsResult(
            review_id=keep_id,
            inline_posted=annotated_count,
            body_findings=len(render_findings),
            event=event,
            degraded_to_comment=False,
            suppressed=suppressed_count,
        )

    # ------------------------------------------------------------------
    # _set_review_state — issue #918: give the decided outcome a real
    # effect on the PR's own reviewer-state UI (and any branch restriction
    # keyed off "changes requested"), not just heading text in the
    # comment.
    # ------------------------------------------------------------------
    def _set_review_state(self, event: PostEvent) -> None:
        """Best-effort: call Bitbucket's approve/request-changes endpoints
        for the bot account (`self.config.email`) to match `event`.

        Fail-soft, same posture as Code Insights posting: logged and
        appended to `self._errors`, never raised, never blocks the
        already-durable comment write above. Called after that PUT
        succeeds (state changes are secondary to the comment, same
        ordering Code Insights already follows).

        Bitbucket's REST API has no single "set state" call -- approving
        and requesting changes are each their own participant-state POST,
        and Bitbucket Cloud does not clear one when the other is called
        (confirmed against Atlassian's documented pull-request-participants
        API; there is no bulk/replace endpoint). So each transition first
        DELETEs whichever opposing state might be lingering from a prior
        run's decision, tolerating 404 (nothing to clear), then POSTs the
        new state. COMMENT clears both without setting either -- this is
        the "downgrade" case #918 asks for (a PR that previously had
        Critical findings and now has none shouldn't keep showing
        "Changes requested" from a stale prior run).
        """
        pr_url = self._pull_request_url()
        approve_url = f"{pr_url}/approve"
        request_changes_url = f"{pr_url}/request-changes"

        def _delete(url: str) -> None:
            resp = self.client.request("DELETE", url)
            if resp.status_code >= 400 and resp.status_code != 404:
                _log.warning(
                    "bitbucket: clearing prior review state failed for "
                    "%s/%s PR #%s (DELETE %s): HTTP %s: %s",
                    self.config.workspace, self.config.repo_slug,
                    self.config.pr_id, url, resp.status_code, resp.text[:200],
                )
                self._errors.append(
                    f"_set_review_state DELETE {url}: HTTP {resp.status_code}"
                )

        def _post(url: str) -> None:
            # Bitbucket's approve/request-changes POST endpoints return a
            # bare-text 400 (not even a JSON error body) when the request
            # carries `Content-Type: application/json` (this client's
            # default on every call, see build_client) with no body at all
            # -- live-verified against the real API. Passing an explicit
            # empty JSON object makes the Content-Type honest and the
            # endpoint accepts it; the endpoints themselves ignore body
            # content entirely regardless (participant state comes from the
            # authenticated user + URL alone), so `{}` carries no meaning
            # beyond satisfying that header/body agreement.
            resp = self.client.request("POST", url, json_body={})
            if resp.status_code >= 400:
                _log.warning(
                    "bitbucket: setting review state failed for %s/%s "
                    "PR #%s (POST %s): HTTP %s: %s",
                    self.config.workspace, self.config.repo_slug,
                    self.config.pr_id, url, resp.status_code, resp.text[:200],
                )
                self._errors.append(
                    f"_set_review_state POST {url}: HTTP {resp.status_code}"
                )

        if event == "APPROVE":
            _delete(request_changes_url)
            _post(approve_url)
        elif event == "REQUEST_CHANGES":
            _delete(approve_url)
            _post(request_changes_url)
        else:
            _delete(approve_url)
            _delete(request_changes_url)

    # ------------------------------------------------------------------
    # resolve_stale — marker-gated comment cleanup (no separate threads)
    # ------------------------------------------------------------------
    def resolve_stale(self, current_review_id: int | None = None) -> StaleResult:
        """Bitbucket has no review-thread concept; "stale" cleanup means
        deleting OLD summary-marker comments that aren't the current one
        (already handled by post_summary's duplicate cleanup).

        For belt-and-suspenders, we re-list and delete duplicates here too.
        Marker-gated via SUMMARY_MARKER_PREFIX (kind="summary").
        """
        comments = self._list_summary_comments()
        if len(comments) <= 1:
            return StaleResult()

        # Keep the most recent (first under sort=-updated_on); delete the rest
        # only if they pass the marker-gated ownership predicate.
        kept = comments[0]
        deleted = 0
        skipped = 0
        errors: list[str] = []
        for dup in comments[1:]:
            body = _comment_body(dup)
            # Bitbucket comments don't carry a uniform author field; rely on
            # the marker alone (kind="summary"). bot_login=None skips the
            # author check inside is_owned_by_us.
            if not is_owned_by_us(body, None, None, kind="summary"):
                skipped += 1
                continue
            dup_id = int(dup["id"])
            resp = self.client.request("DELETE", self._comment_url(dup_id))
            if resp.status_code < 400:
                deleted += 1
                self._comments_cache = None
            else:
                errors.append(
                    f"delete dup #{dup_id}: HTTP {resp.status_code}: "
                    f"{resp.text[:200]}"
                )
        del kept  # explicitly retained, never deleted
        return StaleResult(
            threads_resolved=deleted,
            reviews_dismissed=0,
            threads_skipped_no_marker=skipped,
            errors=tuple(errors),
        )


def _strip_base_url(url: str, base: str) -> str:
    if url.startswith(base):
        suffix = url[len(base):]
        return suffix or "/"
    return url


def _comment_body(item: dict[str, Any]) -> str:
    return ((item.get("content") or {}).get("raw")) or ""


# reporting.py's build_token_table_accordion() wraps the token-cost table in
# raw <details>/<summary> for GitHub/GitLab's native collapsible rendering.
# Bitbucket has neither: it escapes the tags to literal text, and — because
# the wrapper's closing </details> immediately follows the table with no
# blank line — its markdown table parser then absorbs that line (and
# whatever comes after it, up to the next real blank line) as spurious
# trailing table rows, corrupting the table and swallowing the footer that
# follows it in _render_combined_body (#703).
_DETAILS_WRAPPER_RE = re.compile(r"\A<details>\n<summary>(.*?)</summary>\n\n(.*)\n</details>\Z", re.DOTALL)


def _strip_details_wrapper(token_table_md: str) -> str:
    """Convert a reporting.py accordion string to Bitbucket-safe markdown.

    Replaces the <details>/<summary> wrapper with a plain bold heading, and
    always returns a string ending in a newline: _render_combined_body joins
    parts with "\\n", so a single trailing newline here becomes a real blank
    line at the join point, keeping whatever follows out of the table.

    Falls back to returning the input unchanged if it doesn't match the
    expected wrapper shape (e.g. already-plain text) rather than mangling
    something this function doesn't recognize.
    """
    match = _DETAILS_WRAPPER_RE.match(token_table_md)
    if not match:
        return token_table_md
    heading, table = match.group(1), match.group(2)
    return f"**{heading}**\n\n{table}\n"


def _blob_link(
    *, workspace: str, repo_slug: str, head_sha: str, file: str, line: int | None
) -> str:
    """Build a Bitbucket Cloud source-browser URL, anchored to a line.

    Per Atlassian's documented URI template (``src/{commitish}/{filepath}
    #{fileline}``), the line-anchor segment is the file's *basename* plus the
    line number, joined by a dash — NOT the full path (verified 2026-09-01
    against https://support.atlassian.com/bitbucket-cloud/docs/hyperlink
    -to-source-code-in-bitbucket/; a `#lines-N` scheme, closer to GitHub's,
    would have silently produced a dead anchor).
    """
    quoted_path = "/".join(quote(seg) for seg in file.split("/"))
    url = f"https://bitbucket.org/{workspace}/{repo_slug}/src/{head_sha}/{quoted_path}"
    if line is not None:
        basename = quote(file.rsplit("/", 1)[-1])
        url += f"#{basename}-{line}"
    return url


def _render_combined_body(
    *,
    existing_body: str,
    findings: Sequence[Finding],
    event: PostEvent,
    failed_agents: Sequence[str],
    agent_prompt: str,
    id_map: dict[str, int],
    prior_id_map: dict[str, int],
    workspace: str,
    repo_slug: str,
    head_sha: str,
    headline_findings: Sequence[Finding] | None = None,
    annotated_count: int = 0,
    annotated_fingerprints: frozenset[str] = frozenset(),
) -> str:
    """Render the combined summary+findings body for Bitbucket.

    ``findings`` is what actually renders as flat bullets below -- every
    active finding (issue #919), not just the ones that didn't land a Code
    Insights annotation. A finding whose fingerprint is in
    ``annotated_fingerprints`` renders a shortened bullet (no remediation
    sub-bullet, since that detail already lives in its annotation on the
    diff) rather than being omitted from the body entirely -- omitting it
    left the comment saying only "N additional findings shown inline",
    with no indication of what those findings actually were, since
    Bitbucket Code Insights annotations are far less discoverable than
    GitHub's real inline review-comment threads.
    ``headline_findings`` (defaults to ``findings`` when not given) is what
    "Overall Risk"/"Findings: N" describe -- kept separate from ``findings``
    for the same reason GitHub's headline_findings/render_findings split
    exists: a suppressed finding must not count toward either.
    ``annotated_count`` adds a one-line pointer noting how many of the
    findings above are also shown as inline annotations.

    Bitbucket has no <details> rendering, so remediation is rendered as a
    flat sub-bullet (per bash post-review-bitbucket.sh:281), and (unlike
    GitHub) all findings — including genuine out_of_diff analyzer findings —
    render in the flat findings_block below since there is no collapsed
    section to redirect them to. The headline risk/count, however, use the
    shared compute_headline() helper (vcs/_body.py) so "Overall Risk" agrees
    with GitHub's headline and with review.outcome.classify_review_outcome's
    actual APPROVE/REQUEST_CHANGES decision for the same findings. Prior to
    the #622 fix this counted every finding unconditionally, which happened
    to already agree with classify_review_outcome (no exclusion bug) but
    over-counted analyzer out-of-diff findings relative to GitHub — this
    fix brings the two providers into agreement.

    ``id_map``/``prior_id_map`` carry stable F-IDs and the "new since the
    prior review" signal (see module docstring / decisions #17-18 in the
    PR-comment-clutter plan): Bitbucket rebuilds the whole findings list on
    every run rather than only notifying on genuinely-new ones the way
    GitHub does, so findings are sorted new-first then by severity, and a
    finding absent from ``prior_id_map`` is flagged inline. ``prior_id_map``
    is empty both on a genuine first run and whenever no marker could be
    parsed from ``existing_body`` — in either case nothing is flagged new,
    since an all-new list on the very first render would carry no signal.
    """
    headline = compute_headline(
        headline_findings if headline_findings is not None else findings,
        failed_agents,
    )
    finding_total = headline.count
    risk = headline.risk

    has_prior_id_map = bool(prior_id_map)

    def _is_new(f: Finding) -> bool:
        return has_prior_id_map and fingerprint(f) not in prior_id_map

    sorted_findings = sorted(
        findings,
        key=lambda f: (0 if _is_new(f) else 1, _SEVERITY_RANK.get(f.severity, 99)),
    )

    def _render_bullet(f: Finding) -> str:
        loc_note = ""
        if f.file:
            url = _blob_link(
                workspace=workspace, repo_slug=repo_slug, head_sha=head_sha,
                file=f.file, line=f.line,
            )
            loc_note = f" [↗]({url})"
        bullet = format_body_finding(
            f,
            location_note=loc_note,
            finding_id=id_map.get(fingerprint(f)),
            include_remediation=fingerprint(f) not in annotated_fingerprints,
        )
        if _is_new(f):
            # Prepend after the leading "- " so the line still opens with a
            # valid Markdown list marker.
            bullet = f"- 🆕 {bullet[2:]}"
        return bullet

    # Heading + summary block.
    #
    # Gate on `not findings` (the raw list), NOT `finding_total == 0`.
    # finding_total excludes genuine out_of_diff findings (compute_headline's
    # headline-count convention, shared with GitHub's collapsed-section
    # logic) -- but per this function's own docstring, Bitbucket has no
    # collapsed section, so out_of_diff findings still render in the flat
    # findings_block below. Gating on finding_total here would blank
    # findings_block whenever every finding happens to be out_of_diff (e.g.
    # all-Low, all outside the diff), silently dropping real findings from
    # the rendered body while still claiming "no findings" -- reproducing
    # the exact class of bug #622 fixed, on Bitbucket specifically. Using
    # the raw `findings` list keeps this gate about whether there is
    # anything to render, not about the (deliberately narrower) headline
    # count.
    if event == "APPROVE" and not findings and not annotated_count:
        heading = "## AI Review: Approved"
        summary_block = (
            "No findings above the confidence threshold. The changes look good."
        )
        findings_block = ""
    elif event == "COMMENT" and risk == "Unknown" and not findings and not annotated_count:
        heading = "## AI Review: Incomplete"
        joined = ", ".join(failed_agents)
        summary_block = (
            "No findings above the confidence threshold, but one or more "
            f"agents failed: {joined}\n\n"
            "The review may be incomplete. Please verify manually or re-run "
            "the review."
        )
        findings_block = ""
    elif event == "APPROVE" and finding_total == 0:
        # findings is non-empty here (the `not findings` branch above already
        # caught the empty case) but every finding is out_of_diff, so
        # compute_headline()'s deliberately narrower count reads 0. Since
        # Bitbucket has no collapsed section to hide those findings in (see
        # this function's docstring), findings_block below still renders them
        # — say so explicitly rather than printing "Findings: 0" directly
        # above a non-empty list.
        heading = "## AI Review: Approved"
        summary_block = (
            f"{severity_icon(risk)} **Overall Risk:** {risk} | "
            "**Findings:** 0 in the diff\n\n"
            "No Critical or High findings in the diff. The changes look good "
            "— findings below are pre-existing issues on unchanged lines."
        )
        findings_block = "### Findings (informational)\n" + join_findings(
            _render_bullet(f) for f in sorted_findings
        )
    elif event == "APPROVE":
        heading = "## AI Review: Approved"
        summary_block = (
            f"{severity_icon(risk)} **Overall Risk:** {risk} | "
            f"**Findings:** {finding_total}\n\n"
            "No Critical or High findings. The changes look good — Medium/Low "
            "findings are informational only."
        )
        findings_block = "### Findings (informational)\n" + join_findings(
            _render_bullet(f) for f in sorted_findings
        )
    elif finding_total == 0:
        # Reachable for event == "COMMENT" with a non-empty, all-out_of_diff
        # finding set (risk == "None", not "Unknown", so the branch above
        # doesn't catch it) — same rationale as the APPROVE+finding_total==0
        # branch above: don't print "Findings: 0" beside a rendered list.
        heading = "## AI Review Findings"
        summary_block = (
            f"{severity_icon(risk)} **Overall Risk:** {risk} | "
            "**Findings:** 0 in the diff"
        )
        findings_block = "### Findings\n" + join_findings(
            _render_bullet(f) for f in sorted_findings
        )
    else:
        heading = "## AI Review Findings"
        summary_block = (
            f"{severity_icon(risk)} **Overall Risk:** {risk} | "
            f"**Findings:** {finding_total}"
        )
        findings_block = "### Findings\n" + join_findings(
            _render_bullet(f) for f in sorted_findings
        )

    if annotated_count:
        # issue #919: every finding renders in findings_block above now
        # (shortened, not omitted, when also annotated), so this is purely
        # informational -- a pointer to the diff view, not a "this is where
        # the content actually is" apology.
        plural = "" if annotated_count == 1 else "s"
        is_are = "is" if annotated_count == 1 else "are"
        summary_block += (
            f"\n\n{annotated_count} of the finding{plural} above {is_are} also "
            "shown as inline Code Insights annotations on the diff."
        )

    # Preserve the marker line + the walkthrough/summary text from the
    # existing comment. The marker line is always the first line of the
    # existing body. `_extract_walkthrough` isolates only the true
    # walkthrough content -- see its docstring for why a naive "everything
    # after the heading" extraction re-nests the whole prior comment on
    # every incremental run (the bug this fixes).
    head_lines = existing_body.split("\n", 1)
    marker_line = head_lines[0] if head_lines else ""
    original_summary_text = _extract_walkthrough(existing_body)

    pr_summary_block = f"\n### Summary\n{original_summary_text}\n" if original_summary_text else ""

    # Findings before the walkthrough: if the body is truncated at the byte
    # limit, the actionable content survives and the walkthrough is what
    # gets cut, not the other way around (findings used to sit after a
    # potentially-large walkthrough table and could be silently
    # guillotined). The token table is NOT rendered here at all -- see
    # post_findings, which reserves room for it and appends it after
    # truncation instead (#728): findings_block alone can exceed the whole
    # byte budget, so no position in this pre-truncation string can
    # guarantee the table survives.
    parts: list[str] = [marker_line, heading, "", summary_block]
    if findings_block:
        parts.append(findings_block)
    if pr_summary_block:
        parts.append(pr_summary_block)
    if agent_prompt and findings:
        parts.append(agent_prompt)
    # Footer is NOT appended here -- post_findings appends it after the
    # token table (itself appended after truncation, see #728 above), so
    # the visible reading order stays content -> token table -> footer
    # regardless of whether truncation occurred.
    return "\n".join(parts)


# Section-boundary needles `_extract_walkthrough` cuts the carried-forward
# walkthrough text at. All can legitimately follow the "### Summary" heading
# in a body this function itself rendered: "### Findings" and "### Findings
# (informational)" (findings_block; both variants start with the shorter
# needle), the mode-independent USAGE_MARKER_HIDDEN (#758) -- present at the
# start of the usage block in every token-usage-display mode (full/compact/
# off) going forward -- and the agent-prompt <details> block (unused by any
# current caller -- see ai_pr_review/vcs/protocol.py -- but cheap to guard
# against a future one).
#
# The bold-heading and raw-<details> forms stay as a fallback (not the
# primary anchor any more) for the same reason gitlab.py's upsert also
# checks the legacy TOKEN_TABLE_OPEN_MARKER: a comment posted by the version
# of this code running before this upgrade carries the pre-#758 form with no
# USAGE_MARKER_HIDDEN in it at all, and without this fallback the first
# post-upgrade incremental run would extract too much (or too little) of the
# walkthrough from that one carried-forward comment.
_WALKTHROUGH_BOUNDARIES: Final[tuple[str, ...]] = (
    "\n### Findings",
    "\n" + USAGE_MARKER_HIDDEN,
    "\n**Token usage by agent**",
    "\n<details>\n<summary>Token usage by agent</summary>",
    "\n<details>\n<summary>🤖 Prompt for AI agents</summary>",
)


def _extract_walkthrough(existing_body: str) -> str:
    """Return only the walkthrough/summary text carried forward from a prior
    rendered comment, discarding findings, token table, and agent-prompt
    content that may also be present.

    On the very first cycle, `existing_body` was written by `post_summary`
    alone and contains nothing but the marker line and the raw pr-summarizer
    output (no "## AI Review" heading has ever been rendered yet) -- the
    whole thing, footer-stripped, IS the walkthrough.

    #886 hardening: the returned text is re-sanitized with
    `sanitize_display_text` before being handed back, even though
    `post_summary` already sanitizes pr-summarizer output before it's first
    posted. Two reasons this still matters here: (1) a comment posted before
    that sanitization existed carries forward unsanitized, potentially
    forged, marker-shaped text indefinitely, since this is the only place
    that text gets re-embedded into a new body; (2) on an incremental run,
    `post_summary` is a no-op (the pr-summarizer is skipped entirely), so
    this carried-forward walkthrough is the *only* copy of that text this
    cycle touches at all.

    On every later cycle, `existing_body` is whatever `_render_combined_body`
    rendered last time, which always carries a "## AI Review*" heading. If
    that render also had a non-empty walkthrough, it lives under its own
    "### Summary" heading (written by this same function, below); this
    function must extract ONLY that subsection, stopping at whichever
    section boundary comes next. Falling back to "everything after the
    heading" here is exactly the bug this exists to prevent: on an
    incremental run (pr-summarizer skipped, so `post_summary` is a no-op),
    `existing_body` is the FULL prior render -- findings, token table, and
    all -- and treating all of that as "the walkthrough" nests the entire
    previous comment inside the new one, every push.
    """
    head_lines = existing_body.split("\n", 1)
    if len(head_lines) < 2:
        return ""
    rest = head_lines[1]
    if "\n---\n*AI Review" in rest:
        rest = rest.split("\n---\n*AI Review", 1)[0]

    if not rest.startswith("## AI Review"):
        # Anchored to the start of `rest`, not "appears anywhere" -- a
        # walkthrough carried forward from a genuine first run could contain
        # an LLM-authored line that happens to start with "## AI Review"
        # further down (steerable by the diff content it summarizes); only
        # the very first line reliably indicates a prior post_findings
        # render, since that heading is always what `_render_combined_body`
        # writes immediately after the marker line.
        return sanitize_display_text(rest.strip())

    if "\n### Summary\n" not in rest:
        # A prior render exists but its walkthrough was empty -- propagate
        # that emptiness rather than swallowing the findings/token-table
        # content that actually follows the heading in this body.
        return ""
    rest = rest.split("\n### Summary\n", 1)[1]
    cut = min(
        (idx for idx in (rest.find(b) for b in _WALKTHROUGH_BOUNDARIES) if idx != -1),
        default=-1,
    )
    if cut != -1:
        rest = rest[:cut]
    return sanitize_display_text(rest.strip())


# ---------------------------------------------------------------------------
# Summary upsert + skip + watermark advance
# ---------------------------------------------------------------------------


def _post_summary_impl(
    provider: BitbucketProvider, summary_body: str, head_sha: str
) -> SummaryResult:
    if not summary_body.strip():
        return SummaryResult(
            comment_id=None, created=False, updated=False, error="empty summary body"
        )

    marker = build_summary_marker(head_sha, hidden=True)
    truncated = truncate_body(summary_body, limit=_MAX_BITBUCKET_BODY_SIZE)
    body = f"{marker}\n{truncated}\n\n{_FOOTER}"

    # Carry forward the id-map/verdicts/acks hidden markers from whatever
    # summary comment already exists (live-verified 2026-09-22, #874
    # follow-up): post_summary always runs before post_findings (AC5
    # ordering), and post_findings reads THIS write's result back as its
    # own "prior state" baseline (existing_body). Without this, every
    # post_summary call silently reset that baseline to empty -- F-IDs got
    # freshly renumbered on EVERY run (assemble_id_map always saw an empty
    # prior_id_map), and any verdict/ack state a prior run's post_findings
    # had persisted was invisible to apply_pending_verdicts, so an
    # already-acked command comment was reprocessed and re-replied-to on
    # every subsequent run, forever. This predates #874 -- the id-map
    # marker mechanism has silently never provided real F-ID stability on
    # Bitbucket -- but had no visible consequence until #874 gave Bitbucket
    # its first feature that actually depends on cross-run persistence.
    #
    # This write only needs to preserve the prior markers long enough for
    # post_findings (later in the same call chain, same run) to read and
    # re-derive its own authoritative versions from them -- it is never the
    # last word on their contents.
    existing_list = provider._list_summary_comments()
    if existing_list:
        prior_body = _comment_body(existing_list[0])
        carry_forward = ""
        prior_id_map = extract_id_map(prior_body)
        if prior_id_map:
            carry_forward += _hidden_marker_separator(
                body + carry_forward
            ) + build_id_map_marker(prior_id_map, hidden=True)
        prior_verdicts = extract_verdicts(prior_body)
        if prior_verdicts:
            carry_forward += _hidden_marker_separator(
                body + carry_forward
            ) + build_verdicts_marker(prior_verdicts, hidden=True)
        prior_acks = extract_acks(prior_body)
        if prior_acks:
            carry_forward += _hidden_marker_separator(
                body + carry_forward
            ) + build_acks_marker(sorted(prior_acks))
        if carry_forward:
            if len((body + carry_forward).encode("utf-8")) <= _MAX_BITBUCKET_BODY_SIZE:
                body += carry_forward
            else:
                # This is an intermediate write, not the final one -- degrade
                # by omitting the carry-forward rather than failing the PUT
                # outright. post_findings (immediately following, same run)
                # will still re-derive and re-append its own id-map/verdicts
                # correctly from THIS run's own findings; only cross-run
                # continuity for this one cycle is what's lost (a verdict or
                # ack not re-derivable from a still-present, still-unacked
                # command comment).
                _log.warning(
                    "bitbucket: carried-forward id-map/verdicts/acks markers "
                    "(%d bytes) would push the summary comment past the byte "
                    "budget for %s/%s PR #%s; omitting them from this "
                    "intermediate write",
                    len(carry_forward.encode("utf-8")),
                    provider.config.workspace, provider.config.repo_slug,
                    provider.config.pr_id,
                )
                provider._errors.append(
                    "post_summary: carried-forward id-map/verdicts/acks "
                    "markers too large to fit; omitted for this cycle"
                )

    return upsert_comment(
        list_existing=provider._list_summary_comments,
        item_id=lambda item: int(item["id"]),
        payload={"content": {"raw": body}},
        update_verb="PUT",
        item_url=provider._comment_url,
        create_url=provider._comments_url,
        request=provider._write_request,
        errors=provider._errors,
        update_label="update summary",
        create_label="create summary",
    )


def _list_skip_comments_bb(provider: BitbucketProvider) -> list[dict[str, Any]]:
    """Return all PR comments whose body contains SKIP_MARKER."""
    results: list[dict[str, Any]] = []
    url: str | None = provider._comments_url()
    params: dict[str, Any] | None = {"pagelen": 100, "sort": "-updated_on"}
    while url:
        resp = provider.client.request("GET", url, params=params)
        if resp.status_code >= 400:
            provider._errors.append(
                f"list_skip_comments: HTTP {resp.status_code}: {resp.text[:200]}"
            )
            return results
        data = resp.json() or {}
        for item in data.get("values") or []:
            body = _comment_body(item)
            if has_skip_marker(body):
                results.append(item)
        next_url = data.get("next")
        if not isinstance(next_url, str) or not next_url:
            break
        url = _strip_base_url(next_url, provider.config.base_url)
        params = None
    return results


def _post_skip_impl(
    provider: BitbucketProvider, reason: str, *, findings: Sequence[Finding] = ()
) -> SummaryResult:
    raw = f"**AI Review skipped.** {reason.strip() or 'No changes to review.'}"
    raw += render_skip_findings_section(findings)
    raw = truncate_body(raw, limit=_MAX_BITBUCKET_BODY_SIZE)
    raw = append_skip_marker(
        raw,
        inline_marker=INLINE_MARKER_HIDDEN,
        skip_marker=SKIP_MARKER_HIDDEN,
    )
    return upsert_comment(
        list_existing=lambda: _list_skip_comments_bb(provider),
        item_id=lambda item: int(item["id"]),
        payload={"content": {"raw": raw}},
        update_verb="PUT",
        item_url=provider._comment_url,
        create_url=provider._comments_url,
        request=provider._write_request,
        errors=provider._errors,
        update_label="update skip comment",
        create_label="skip comment",
    )


def _advance_sha_impl(provider: BitbucketProvider, new_sha: str) -> bool:
    return advance_sha_marker(
        list_existing=provider._list_summary_comments,
        item_id=lambda item: int(item["id"]),
        extract_body=_comment_body,
        make_payload=lambda body: {"content": {"raw": body}},
        update_verb="PUT",
        item_url=provider._comment_url,
        request=provider._write_request,
        errors=provider._errors,
        new_sha=new_sha,
        context_hint_prefix="bitbucket_comment",
    )
